// packages/components-react/src/pages/InlineNotification.tsx
/* Auto Generated File */
import { PInlineNotification } from '@porsche-design-system/components-react';

export const InlineNotificationPage = (): JSX.Element => {
  return (
    <>
      <div className="playground light" title="should show inline-notification info on light background">
        <PInlineNotification heading="Some neutral heading" description="Some description" />
      </div>

      <div className="playground light" title="should show inline-notification info with state neutral on light background">
        <PInlineNotification
          state="neutral"
          heading="Some neutral heading"
          description="Some description"
         />
      </div>

      <div className="playground dark" title="should show inline-notification info on dark background">
        <PInlineNotification
          heading="Some neutral heading"
          description="Some description"
          theme="dark"
         />
      </div>

      <div className="playground dark" title="should show inline-notification info with state neutral on dark background">
        <PInlineNotification
          state="neutral"
          heading="Some neutral heading"
          description="Some description"
          theme="dark"
         />
      </div>

      <div className="playground light" title="should show inline-notification warning on light background">
        <PInlineNotification
          heading="Some warning heading"
          description="Some description"
          state="warning"
         />
      </div>

      <div className="playground dark" title="should show inline-notification warning on dark background">
        <PInlineNotification
          heading="Some warning heading"
          description="Some description"
          state="warning"
          theme="dark"
         />
      </div>

      <div className="playground light" title="should show inline-notification success on light background">
        <PInlineNotification
          heading="Some success heading"
          description="Some description"
          state="success"
         />
      </div>

      <div className="playground dark" title="should show inline-notification success on dark background">
        <PInlineNotification
          heading="Some success heading"
          description="Some description"
          state="success"
          theme="dark"
         />
      </div>

      <div className="playground light" title="should show inline-notification error on light background">
        <PInlineNotification
          heading="Some error heading"
          description="Some description"
          state="error"
         />
      </div>

      <div className="playground dark" title="should show inline-notification error on dark background">
        <PInlineNotification
          heading="Some error heading"
          description="Some description"
          state="error"
          theme="dark"
         />
      </div>

      <div className="playground light" title="should show inline-notification with slotted content on light background">
        <PInlineNotification>
          <span slot="heading">Some slotted heading</span>
          Some slotted description with a <a href="https://www.porsche.com/">LINK</a> element.
        </PInlineNotification>
      </div>

      <div className="playground dark" title="should show inline-notification with slotted content on dark background">
        <PInlineNotification theme="dark">
          <span slot="heading">Some slotted heading</span>
          Some slotted description with a <a href="https://www.porsche.com/">LINK</a> element.
        </PInlineNotification>
      </div>

      <div className="playground light" title="should show inline-notification with action button on light background">
        <PInlineNotification
          heading="Some heading with action button"
          description="Some description"
          actionLabel="Some action label"
         />
      </div>

      <div className="playground dark" title="should show inline-notification with action button on dark background">
        <PInlineNotification
          heading="Some heading with action button"
          description="Some description"
          actionLabel="Some action label"
          theme="dark"
         />
      </div>

      <div className="playground light" title="should show inline-notification with loading action button on light background">
        <PInlineNotification
          heading="Some heading with action button"
          description="Some description"
          actionLabel="Some loading action label"
          actionLoading={true}
         />
      </div>

      <div className="playground dark" title="should show inline-notification with loading action button on dark background">
        <PInlineNotification
          heading="Some heading with action button"
          description="Some description"
          actionLabel="Some loading action label"
          actionLoading={true}
          theme="dark"
         />
      </div>

      <div className="playground light" title="should show inline-notification in persistent mode on light background">
        <PInlineNotification
          heading="Some persistent heading"
          description="Some description"
          persistent={true}
         />
      </div>

      <div className="playground dark" title="should show inline-notification in persistent mode on dark background">
        <PInlineNotification
          heading="Some persistent heading"
          description="Some description"
          persistent={true}
          theme="dark"
         />
      </div>

      <div
        className="playground light"
        title="should show inline-notification in persistent mode with action button on light background"
      >
        <PInlineNotification
          heading="Some persistent heading with action button"
          description="Some description"
          persistent={true}
          actionLabel="Some action label with custom icon"
          actionIcon="refresh"
         />
      </div>

      <div
        className="playground dark"
        title="should show inline-notification in persistent mode with action button on dark background"
      >
        <PInlineNotification
          heading="Some persistent heading with action button"
          description="Some description"
          persistent={true}
          actionLabel="Some action label with custom icon"
          actionIcon="refresh"
          theme="dark"
         />
      </div>

      <div
        className="playground light"
        title="should show inline-notification with multiline heading and description on light background"
      >
        <PInlineNotification
          style={{ width: '15rem' }}
          heading="Some heading with a very long text across multiple lines"
          description="Some description with a very long text across multiple lines"
          actionLabel="Some action label with custom icon"
         />
      </div>
    </>
  );
};

// packages/components-angular/src/app/pages/inline-notification.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-inline-notification',
  template: `
    <div class="playground light" title="should show inline-notification info on light background">
      <p-inline-notification [heading]="'Some neutral heading'" [description]="'Some description'"></p-inline-notification>
    </div>

    <div class="playground dark" title="should show inline-notification info on dark background">
      <p-inline-notification
        [heading]="'Some neutral heading'"
        [description]="'Some description'"
        [theme]="'dark'"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification warning on light background">
      <p-inline-notification
        [heading]="'Some warning heading'"
        [description]="'Some description'"
        [state]="'warning'"
      ></p-inline-notification>
    </div>

    <div class="playground dark" title="should show inline-notification warning on dark background">
      <p-inline-notification
        [heading]="'Some warning heading'"
        [description]="'Some description'"
        [state]="'warning'"
        [theme]="'dark'"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification success on light background">
      <p-inline-notification
        [heading]="'Some success heading'"
        [description]="'Some description'"
        [state]="'success'"
      ></p-inline-notification>
    </div>

    <div class="playground dark" title="should show inline-notification success on dark background">
      <p-inline-notification
        [heading]="'Some success heading'"
        [description]="'Some description'"
        [state]="'success'"
        [theme]="'dark'"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification error on light background">
      <p-inline-notification
        [heading]="'Some error heading'"
        [description]="'Some description'"
        [state]="'error'"
      ></p-inline-notification>
    </div>

    <div class="playground dark" title="should show inline-notification error on dark background">
      <p-inline-notification
        [heading]="'Some error heading'"
        [description]="'Some description'"
        [state]="'error'"
        [theme]="'dark'"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification with slotted content on light background">
      <p-inline-notification>
        <span slot="heading">Some slotted heading</span>
        Some slotted description with a <a [href]="'https://www.porsche.com/'">LINK</a> element.
      </p-inline-notification>
    </div>

    <div class="playground dark" title="should show inline-notification with slotted content on dark background">
      <p-inline-notification [theme]="'dark'">
        <span slot="heading">Some slotted heading</span>
        Some slotted description with a <a [href]="'https://www.porsche.com/'">LINK</a> element.
      </p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification with action button on light background">
      <p-inline-notification
        [heading]="'Some heading with action button'"
        [description]="'Some description'"
        [actionLabel]="'Some action label'"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification with action button on dark background">
      <p-inline-notification
        [heading]="'Some heading with action button'"
        [description]="'Some description'"
        [actionLabel]="'Some action label'"
        [theme]="'dark'"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification with loading action button on light background">
      <p-inline-notification
        [heading]="'Some heading with action button'"
        [description]="'Some description'"
        [actionLabel]="'Some loading action label'"
        [actionLoading]="true"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification with loading action button on dark background">
      <p-inline-notification
        [heading]="'Some heading with action button'"
        [description]="'Some description'"
        [actionLabel]="'Some loading action label'"
        [actionLoading]="true"
        [theme]="'dark'"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification in persistent mode on light background">
      <p-inline-notification
        [heading]="'Some persistent heading'"
        [description]="'Some description'"
        [persistent]="true"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification in persistent mode on dark background">
      <p-inline-notification
        [heading]="'Some persistent heading'"
        [description]="'Some description'"
        [persistent]="true"
        [theme]="'dark'"
      ></p-inline-notification>
    </div>

    <div
      class="playground light"
      title="should show inline-notification in persistent mode with action button on light background"
    >
      <p-inline-notification
        [heading]="'Some persistent heading with action button'"
        [description]="'Some description'"
        [persistent]="true"
        [actionLabel]="'Some action label with custom icon'"
        [actionIcon]="'refresh'"
      ></p-inline-notification>
    </div>

    <div
      class="playground dark"
      title="should show inline-notification in persistent mode with action button on dark background"
    >
      <p-inline-notification
        [heading]="'Some persistent heading with action button'"
        [description]="'Some description'"
        [persistent]="true"
        [actionLabel]="'Some action label with custom icon'"
        [actionIcon]="'refresh'"
        [theme]="'dark'"
      ></p-inline-notification>
    </div>

    <div class="playground light" title="should show inline-notification with multiline heading and description">
      <p-inline-notification
        style="width: 15rem"
        [heading]="'Some heading with a very long text across multiple lines'"
        [description]="'Some description with a very long text across multiple lines'"
        [actionLabel]="'Some action label with custom icon'"
      ></p-inline-notification>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InlineNotificationComponent {}
