// packages/components-react/projects/nextjs/pages/modal-fullscreen-breakpoint.tsx
/* Auto Generated File */
import type { NextPage } from 'next';
import { PContentWrapper, PModal } from '@porsche-design-system/components-react/ssr';

const ModalFullscreenBreakpointPage: NextPage = (): JSX.Element => {
  const style = `
    .playground {
      height: 500px;
      padding: 0;
      transform: translate3d(0, 0, 0);
    }
  `;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: style }} />

      <div className="playground light" title="should show fullscreen breakpoint modal on light background">
        <PContentWrapper width="basic">
          <div style={{ background: 'deeppink', height: '100vh' }} />
        </PContentWrapper>
        <PModal
          heading="Some Heading with a very long title across multiple lines"
          open={true}
          fullscreen={{ base: true, xs: false, s: true, m: false, l: true, xl: false }}
        >
          Some Content
        </PModal>
      </div>

      <div className="visualize-grid">
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
      </div>
    </>
  );
};

export default ModalFullscreenBreakpointPage;

// packages/components-angular/src/app/pages/modal-fullscreen-breakpoint.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-modal-fullscreen-breakpoint',
  styles: [
    `
      .playground {
        height: 500px;
        padding: 0;
        transform: translate3d(0, 0, 0);
      }
    `,
  ],
  template: `
    <div class="playground light" title="should show fullscreen breakpoint modal on light background">
      <p-content-wrapper [width]="'basic'">
        <div style="background: deeppink; height: 100vh"></div>
      </p-content-wrapper>
      <p-modal
        [heading]="'Some Heading with a very long title across multiple lines'"
        [open]="true"
        [fullscreen]="{ base: true, xs: false, s: true, m: false, l: true, xl: false }"
      >
        Some Content
      </p-modal>
    </div>

    <div class="visualize-grid">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ModalFullscreenBreakpointComponent {}
