// packages/components-react/src/pages/TextList.tsx
/* Auto Generated File */
import { PTextList, PTextListItem } from '@porsche-design-system/components-react';

export const TextListPage = (): JSX.Element => {
  return (
    <>
      <div className="playground light" title="should show text list type=unordered on light background">
        <PTextList>
          <PTextListItem>Unordered root list item</PTextListItem>
          <PTextListItem>
            Unordered root list item
            <PTextList>
              <PTextListItem>Unordered nested list item</PTextListItem>
              <PTextListItem>Unordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Unordered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground dark" title="should show text list type=unordered on dark background">
        <PTextList theme="dark">
          <PTextListItem>Unordered root list item</PTextListItem>
          <PTextListItem>
            Unordered root list item
            <PTextList theme="dark">
              <PTextListItem>Unordered nested list item</PTextListItem>
              <PTextListItem>Unordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Unordered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground light" title="should show text list type=numbered on light background">
        <PTextList type="numbered">
          <PTextListItem>Numbered root list item</PTextListItem>
          <PTextListItem>
            Numbered root list item
            <PTextList type="numbered">
              <PTextListItem>Numbered nested list item</PTextListItem>
              <PTextListItem>Numbered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Numbered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground dark" title="should show text list type=numbered on dark background">
        <PTextList type="numbered" theme="dark">
          <PTextListItem>Numbered root list item</PTextListItem>
          <PTextListItem>
            Numbered root list item
            <PTextList type="numbered" theme="dark">
              <PTextListItem>Numbered nested list item</PTextListItem>
              <PTextListItem>Numbered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Numbered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground light" title="should show text list type=alphabetically on light background">
        <PTextList type="alphabetically">
          <PTextListItem>Alphabetically root list item</PTextListItem>
          <PTextListItem>
            Alphabetically root list item
            <PTextList type="alphabetically">
              <PTextListItem>Alphabetically nested list item</PTextListItem>
              <PTextListItem>Alphabetically nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Alphabetically root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground dark" title="should show text list type=alphabetically on dark background">
        <PTextList type="alphabetically" theme="dark">
          <PTextListItem>Alphabetically root list item</PTextListItem>
          <PTextListItem>
            Alphabetically root list item
            <PTextList type="alphabetically" theme="dark">
              <PTextListItem>Alphabetically nested list item</PTextListItem>
              <PTextListItem>Alphabetically nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Alphabetically root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground light" title="should show ordered text list numbered on light background">
        <PTextList listType="ordered">
          <PTextListItem>
            Numbered, ordered root list item
            <PTextList listType="unordered">
              <PTextListItem>Unordered nested list item</PTextListItem>
              <PTextListItem>Unordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>
            Numbered, ordered root list item
            <PTextList listType="ordered">
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground dark" title="should show ordered text list numbered on dark background">
        <PTextList listType="ordered" theme="dark">
          <PTextListItem>
            Numbered, ordered root list item
            <PTextList listType="unordered" theme="dark">
              <PTextListItem>Unordered nested list item</PTextListItem>
              <PTextListItem>Unordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>
            Numbered, ordered root list item
            <PTextList listType="ordered" theme="dark">
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground light" title="should show ordered text list alphabetically on light background">
        <PTextList listType="ordered" orderType="alphabetically">
          <PTextListItem>
            Alphabetically, ordered root list item
            <PTextList listType="unordered">
              <PTextListItem>Unordered nested list item</PTextListItem>
              <PTextListItem>Unordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>
            Alphabetically, ordered root list item
            <PTextList listType="ordered" orderType="alphabetically">
              <PTextListItem>Alphabetically, ordered nested list item</PTextListItem>
              <PTextListItem>Alphabetically, ordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Alphabetically, ordered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground dark" title="should show ordered text list alphabetically on dark background">
        <PTextList listType="ordered" orderType="alphabetically" theme="dark">
          <PTextListItem>
            Alphabetically, ordered root list item
            <PTextList listType="unordered" theme="dark">
              <PTextListItem>Unordered nested list item</PTextListItem>
              <PTextListItem>Unordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>
            Alphabetically, ordered root list item
            <PTextList listType="ordered" orderType="alphabetically" theme="dark">
              <PTextListItem>Alphabetically, ordered nested list item</PTextListItem>
              <PTextListItem>Alphabetically, ordered nested list item</PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Alphabetically, ordered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground light" title="should handle edge cases">
        <PTextList listType="ordered">
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
          <PTextListItem>
            Numbered, ordered root list item
            <PTextList listType="ordered">
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>Numbered, ordered nested list item</PTextListItem>
              <PTextListItem>
                Numbered, ordered nested list item
                <PTextList listType="ordered">
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                  <PTextListItem>Numbered, ordered nested list item</PTextListItem>
                </PTextList>
              </PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>Numbered, ordered root list item</PTextListItem>
        </PTextList>
      </div>

      <div className="playground light" title="should show multiline text list">
        <PTextList listType="ordered" style={{ width: '15rem' }}>
          <PTextListItem>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua. Cursus mattis molestie a iaculis.
            <PTextList listType="ordered">
              <PTextListItem>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                magna aliqua. Cursus mattis molestie a iaculis.
              </PTextListItem>
              <PTextListItem>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                magna aliqua. Cursus mattis molestie a iaculis.
              </PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua. Cursus mattis molestie a iaculis.
            <PTextList>
              <PTextListItem>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                magna aliqua. Cursus mattis molestie a iaculis.
              </PTextListItem>
              <PTextListItem>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                magna aliqua. Cursus mattis molestie a iaculis.
              </PTextListItem>
            </PTextList>
          </PTextListItem>
          <PTextListItem>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua. Cursus mattis molestie a iaculis.
            <PTextList listType="ordered" orderType="alphabetically">
              <PTextListItem>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                magna aliqua. Cursus mattis molestie a iaculis.
              </PTextListItem>
              <PTextListItem>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                magna aliqua. Cursus mattis molestie a iaculis.
              </PTextListItem>
            </PTextList>
          </PTextListItem>
        </PTextList>
      </div>

      <div className="playground light" title="should apply custom styles for dedicated slotted content">
        <PTextList>
          <PTextListItem>
            <span>
              Some slotted and deeply nested <a href="#">anchor</a>, <b>bold</b>, <strong>strong</strong>,
              {' '}<em>emphasized</em> and <i>italic</i> text.
            </span>
          </PTextListItem>
        </PTextList>
      </div>

      <div className="playground dark" title="should apply custom styles for dedicated slotted content">
        <PTextList theme="dark">
          <PTextListItem>
            <span>
              Some slotted and deeply nested <a href="#">anchor</a>, <b>bold</b>, <strong>strong</strong>,
              {' '}<em>emphasized</em> and <i>italic</i> text.
            </span>
          </PTextListItem>
        </PTextList>
      </div>
    </>
  );
};

// packages/components-angular/src/app/pages/text-list.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-text-list',
  template: `
    <div class="playground light" title="should show unordered text list on light background">
      <p-text-list>
        <p-text-list-item>Unordered root list item</p-text-list-item>
        <p-text-list-item>
          Unordered root list item
          <p-text-list>
            <p-text-list-item>Unordered nested list item</p-text-list-item>
            <p-text-list-item>Unordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>Unordered root list item</p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground dark" title="should show unordered text list on dark background">
      <p-text-list [theme]="'dark'">
        <p-text-list-item>Unordered root list item</p-text-list-item>
        <p-text-list-item>
          Unordered root list item
          <p-text-list [theme]="'dark'">
            <p-text-list-item>Unordered nested list item</p-text-list-item>
            <p-text-list-item>Unordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>Unordered root list item</p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground light" title="should show ordered text list Numbered, on light background">
      <p-text-list [listType]="'ordered'">
        <p-text-list-item>
          Numbered, ordered root list item
          <p-text-list [listType]="'unordered'">
            <p-text-list-item>Unordered nested list item</p-text-list-item>
            <p-text-list-item>Unordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>
          Numbered, ordered root list item
          <p-text-list [listType]="'ordered'">
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground dark" title="should show ordered text list Numbered, on dark background">
      <p-text-list [listType]="'ordered'" [theme]="'dark'">
        <p-text-list-item>
          Numbered, ordered root list item
          <p-text-list [listType]="'unordered'" [theme]="'dark'">
            <p-text-list-item>Unordered nested list item</p-text-list-item>
            <p-text-list-item>Unordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>
          Numbered, ordered root list item
          <p-text-list [listType]="'ordered'" [theme]="'dark'">
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground light" title="should show ordered text list alphabetically on light background">
      <p-text-list [listType]="'ordered'" [orderType]="'alphabetically'">
        <p-text-list-item>
          Alphabetically, ordered root list item
          <p-text-list [listType]="'unordered'">
            <p-text-list-item>Unordered nested list item</p-text-list-item>
            <p-text-list-item>Unordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>
          Alphabetically, ordered root list item
          <p-text-list [listType]="'ordered'" [orderType]="'alphabetically'">
            <p-text-list-item>Alphabetically, ordered nested list item</p-text-list-item>
            <p-text-list-item>Alphabetically, ordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>Alphabetically, ordered root list item</p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground dark" title="should show ordered text list alphabetically on dark background">
      <p-text-list [listType]="'ordered'" [orderType]="'alphabetically'" [theme]="'dark'">
        <p-text-list-item>
          Alphabetically, ordered root list item
          <p-text-list [listType]="'unordered'" [theme]="'dark'">
            <p-text-list-item>Unordered nested list item</p-text-list-item>
            <p-text-list-item>Unordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>
          Alphabetically, ordered root list item
          <p-text-list [listType]="'ordered'" [orderType]="'alphabetically'" [theme]="'dark'">
            <p-text-list-item>Alphabetically, ordered nested list item</p-text-list-item>
            <p-text-list-item>Alphabetically, ordered nested list item</p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>Alphabetically, ordered root list item</p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground light" title="should handle edge cases">
      <p-text-list [listType]="'ordered'">
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
        <p-text-list-item>
          Numbered, ordered root list item
          <p-text-list [listType]="'ordered'">
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
            <p-text-list-item>
              Numbered, ordered nested list item
              <p-text-list [listType]="'ordered'">
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
                <p-text-list-item>Numbered, ordered nested list item</p-text-list-item>
              </p-text-list>
            </p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>Numbered, ordered root list item</p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground light" title="should show multiline text list">
      <p-text-list [listType]="'ordered'" style="width: 15rem">
        <p-text-list-item>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Cursus mattis molestie a iaculis.
          <p-text-list [listType]="'ordered'">
            <p-text-list-item>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua. Cursus mattis molestie a iaculis.
            </p-text-list-item>
            <p-text-list-item>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua. Cursus mattis molestie a iaculis.
            </p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Cursus mattis molestie a iaculis.
          <p-text-list>
            <p-text-list-item>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua. Cursus mattis molestie a iaculis.
            </p-text-list-item>
            <p-text-list-item>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua. Cursus mattis molestie a iaculis.
            </p-text-list-item>
          </p-text-list>
        </p-text-list-item>
        <p-text-list-item>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Cursus mattis molestie a iaculis.
          <p-text-list [listType]="'ordered'" [orderType]="'alphabetically'">
            <p-text-list-item>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua. Cursus mattis molestie a iaculis.
            </p-text-list-item>
            <p-text-list-item>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua. Cursus mattis molestie a iaculis.
            </p-text-list-item>
          </p-text-list>
        </p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground light" title="should apply custom styles for dedicated slotted content">
      <p-text-list>
        <p-text-list-item>
          <span>
            Some slotted and deeply nested <a [href]="'#'">anchor</a>, <b>bold</b>, <strong>strong</strong>,
            <em>emphasized</em> and <i>italic</i> text.
          </span>
        </p-text-list-item>
      </p-text-list>
    </div>

    <div class="playground dark" title="should apply custom styles for dedicated slotted content">
      <p-text-list [theme]="'dark'">
        <p-text-list-item>
          <span>
            Some slotted and deeply nested <a [href]="'#'">anchor</a>, <b>bold</b>, <strong>strong</strong>,
            <em>emphasized</em> and <i>italic</i> text.
          </span>
        </p-text-list-item>
      </p-text-list>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TextListComponent {}
