// packages/components-angular/src/app/styles/styles-focus-example.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-styles-focus-example',
  styles: [
    `
      @import '@porsche-design-system/components-js/styles/scss';

      // Wrapper
      .wrapper {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: flex-start;
        gap: $pds-grid-gap;
        padding: $pds-spacing-fluid-medium;

        &--light {
          background: $pds-theme-light-background-base;
          color: $pds-theme-light-primary;
        }

        &--dark {
          background: $pds-theme-dark-background-base;
          color: $pds-theme-dark-primary;
        }
      }

      // Typography
      .heading {
        @include pds-heading-medium;
        text-align: center;
        width: 100%;
        margin: 0;
      }

      // Paragraph
      .paragraph {
        @include pds-text-small;
        margin: 0;
        max-width: 15rem;
      }

      // Native Button
      .native-button {
        @include pds-text-small;
        @include pds-focus;
      }

      // Native Anchor
      .native-anchor {
        @include pds-text-small;
        @include pds-focus;
        color: inherit;
      }
    `,
  ],
  template: `
    <div>
      <div class="wrapper wrapper--light">
        <h3 class="heading">Focus Light (only visible by keyboard navigation)</h3>
        <button class="native-button">Some Button</button>
        <a href="#" class="native-anchor">Some Anchor</a>
        <p class="paragraph">
          Lorem Ipsum
          <a href="#" class="native-anchor">is simply dummy text of the printing</a> and typesetting industry.
        </p>
      </div>
      <div class="wrapper wrapper--dark">
        <h3 class="heading">Focus Dark (only visible by keyboard navigation)</h3>
        <button class="native-button">Some Button</button>
        <a href="#" class="native-anchor">Some Anchor</a>
        <p class="paragraph">
          Lorem Ipsum <a href="#" class="native-anchor">is simply dummy text of the printing</a> and typesetting
          industry.
        </p>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class StylesFocusExampleComponent {}

// packages/components-react/src/styles/StylesFocusExample.tsx
import styled from 'styled-components';
import {
  getFocusStyle,
  gridGap,
  headingMediumStyle,
  spacingFluidMedium,
  textSmallStyle,
  themeDarkBackgroundBase,
  themeDarkPrimary,
  themeLightBackgroundBase,
  themeLightPrimary,
} from '@porsche-design-system/components-react/styles';

// Wrapper
const Wrapper = styled.div({
  display: 'flex',
  flexWrap: 'wrap',
  justifyContent: 'center',
  alignItems: 'flex-start',
  gap: gridGap,
  padding: spacingFluidMedium,
});

const WrapperLight = styled(Wrapper)({
  background: themeLightBackgroundBase,
  color: themeLightPrimary,
});

const WrapperDark = styled(Wrapper)({
  background: themeDarkBackgroundBase,
  color: themeDarkPrimary,
});

// Typography
const Heading = styled.h3({
  ...headingMediumStyle,
  textAlign: 'center',
  width: '100%',
  margin: 0,
});

const Paragraph = styled.p({
  ...textSmallStyle,
  margin: 0,
  maxWidth: '15rem',
});

// Button
const NativeButton = styled.button({
  ...textSmallStyle,
  ...getFocusStyle(),
});

// Anchor
const NativeAnchor = styled.a({
  ...textSmallStyle,
  ...getFocusStyle(),
  color: 'inherit',
});

export const StylesFocusExample = (): JSX.Element => {
  return (
    <>
      <WrapperLight>
        <Heading>Focus Light (only visible by keyboard navigation)</Heading>
        <NativeButton>Some Button</NativeButton>
        <NativeAnchor href="#">Some Anchor</NativeAnchor>
        <Paragraph>
          Lorem Ipsum <NativeAnchor href="#">is simply dummy text of the printing</NativeAnchor> and typesetting
          industry.
        </Paragraph>
      </WrapperLight>
      <WrapperDark>
        <Heading>Focus Dark (only visible by keyboard navigation)</Heading>
        <NativeButton>Some Button</NativeButton>
        <NativeAnchor href="#">Some Anchor</NativeAnchor>
        <Paragraph>
          Lorem Ipsum <NativeAnchor href="#">is simply dummy text of the printing</NativeAnchor> and typesetting
          industry.
        </Paragraph>
      </WrapperDark>
    </>
  );
};
