// packages/components-angular/src/app/styles/styles-motion-expand-example.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-styles-motion-expand-example',
  styles: [
    `
      @use '@porsche-design-system/components-angular/styles' as *;

      // Wrapper
      .wrapper {
        display: flex;
        gap: $pds-grid-gap;
        padding: $pds-spacing-fluid-medium;
        flex-wrap: wrap;
        justify-content: center;
      }

      // Typography
      .heading {
        @include pds-heading-medium;
        color: $pds-theme-light-primary;
        text-align: center;
        width: 100%;
        margin: 0;
      }

      // Tile
      .tile {
        color: $pds-theme-light-primary;
        background: $pds-theme-light-background-surface;
        border-radius: $pds-border-radius-large;
        cursor: pointer;
        width: 200px;
        height: 40px;
        transition: height;
        transition-duration: $pds-motion-duration-short;
        transition-timing-function: $pds-motion-easing-in;
      }

      .active {
        height: 160px;
        transition: height;
        transition-duration: $pds-motion-duration-moderate;
        transition-timing-function: $pds-motion-easing-base;
      }
    `,
  ],
  template: `
    <div>
      <div class="wrapper">
        <h3 class="heading">Expand</h3>
        <div class="tile" (click)="onClick($event)"></div>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class StylesMotionExpandExampleComponent {
  onClick = (e: MouseEvent): void => {
    (e.target as HTMLDivElement).classList.toggle('active');
  };
}

// packages/components-react/src/styles/StylesMotionExpandExample.tsx
import styled from 'styled-components';
import {
  borderRadiusLarge,
  gridGap,
  headingMediumStyle,
  motionDurationModerate,
  motionDurationShort,
  motionEasingBase,
  motionEasingIn,
  spacingFluidMedium,
  themeLightBackgroundSurface,
  themeLightPrimary,
} from '@porsche-design-system/components-react/styles';

// Wrapper
const Wrapper = styled.div({
  display: 'flex',
  gap: gridGap,
  padding: spacingFluidMedium,
  flexWrap: 'wrap',
  justifyContent: 'center',
});

// Typography
const Heading = styled.h3({
  ...headingMediumStyle,
  color: themeLightPrimary,
  textAlign: 'center',
  width: '100%',
  margin: 0,
});

// Tile
const MotionExpand = styled.div({
  color: themeLightPrimary,
  background: themeLightBackgroundSurface,
  borderRadius: borderRadiusLarge,
  cursor: 'pointer',
  width: '200px',
  height: '40px',
  transition: 'height',
  transitionDuration: motionDurationShort,
  transitionTimingFunction: motionEasingIn,
});

export const StylesMotionExpandExample = (): JSX.Element => {
  return (
    <>
      <style>{`
        .active {
          height: 160px;
          transition: height;
          transition-duration: ${motionDurationModerate};
          transition-timing-function: ${motionEasingBase};
        }
      `}</style>
      <Wrapper>
        <Heading>Expand</Heading>
        <MotionExpand onClick={(e) => (e.target as HTMLDivElement).classList.toggle('active')}></MotionExpand>
      </Wrapper>
    </>
  );
};
