// packages/components-react/projects/nextjs/components/Toast.tsx
'use client';

import { PToast, useToastManager } from '@porsche-design-system/components-react/ssr';
import { useEffect } from 'react';

export const Toast = ({ text }: { text: string }) => {
  const { addMessage } = useToastManager();
  useEffect(() => {
    addMessage({ text });
  }, [addMessage, text]);

  return <PToast />;
};

// packages/components-vue/src/components/ToastComponent.vue
<script setup lang="ts">
  import { PToast, useToastManager } from '@porsche-design-system/components-vue';
  import { onMounted } from 'vue';

  const { addMessage } = useToastManager();

  onMounted(() => {
    addMessage({ text: 'some message' });
  });
</script>

<template>
  <PToast />
</template>
