// packages/components-react/projects/react-wrapper/skill/references/components/p-carousel/examples/DynamicSlides.tsx
import React from 'react';
import { PButton, PCarousel } from '@porsche-design-system/components-react';
import { useCallback, useState } from 'react';

export const Example = () => {
  const [amountOfSlides, setAmountOfSlides] = useState(3);
  const onAddClick = useCallback(() => setAmountOfSlides((prev) => prev + 1), []);
  const onRemoveClick = useCallback(() => setAmountOfSlides((prev) => (prev === 0 ? 0 : prev - 1)), []);

  const slideStyle = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#00b0f4',
    height: '150px',
  };

  return (
    <>
      <PCarousel slidesPerPage={2} heading="Some Heading">
        {Array.from(Array(amountOfSlides)).map((_, i) => (
          <div style={slideStyle} key={i} children={`Slide ${i + 1}`} />
        ))}
      </PCarousel>

      <div className="flex gap-fluid-sm mt-fluid-sm">
        <PButton type="button" onClick={onAddClick} children="Add slide" />
        <PButton type="button" onClick={onRemoveClick} children="Remove last slide" />
      </div>
    </>
  );
};

// packages/components-angular/projects/angular-wrapper/skill/references/components/p-carousel/examples/DynamicSlides.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
    <p-carousel [slidesPerPage]="2" [heading]="'Some Heading'">
      @for (_ of [].constructor(amountOfSlides); track _; let i = $index) {
        <div>Slide {{ i + 1 }}</div>
      }
    </p-carousel>
    <div class="flex gap-fluid-sm mt-fluid-sm">
      <p-button type="button" (click)="amountOfSlides = amountOfSlides + 1">Add slide</p-button>
      <p-button type="button" (click)="amountOfSlides = amountOfSlides === 0 ? 0 : amountOfSlides - 1">
        Remove last slide
      </p-button>
    </div>
    `,
  styles: `
    @use '@porsche-design-system/components-angular/scss' as *;

    p-carousel div {
      display: flex;
      align-items: center;
      justify-content: center;
      background: #00b0f4;
      height: 150px;
      color: $color-primary;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class ExampleComponent {
  amountOfSlides = 3;
}
