// packages/components-angular/src/app/pages/modal-fullscreen.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-modal-fullscreen',
  styles: [
    `
      .playground {
        height: 500px;
        padding: 0;
        transform: translate3d(0, 0, 0);
      }
    `,
  ],
  template: `
    <div class="playground light" title="should show fullscreen modal on light background">
      <p-modal [heading]="'Some Heading with a very long title across multiple lines'" [open]="true" [fullscreen]="true">
        Some Content
      </p-modal>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ModalFullscreenComponent {}

// packages/components-react/projects/nextjs/pages/modal-fullscreen.tsx
/* Auto Generated File */
import type { NextPage } from 'next';
import { PModal } from '@porsche-design-system/components-react/ssr';

const ModalFullscreenPage: NextPage = (): JSX.Element => {
  const style = `
    .playground {
      height: 500px;
      padding: 0;
      transform: translate3d(0, 0, 0);
    }
  `;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: style }} />

      <div className="playground light" title="should show fullscreen modal on light background">
        <PModal heading="Some Heading with a very long title across multiple lines" open={true} fullscreen={true}>
          Some Content
        </PModal>
      </div>
    </>
  );
};

export default ModalFullscreenPage;
