// packages/components-angular/src/app/pages/modal-full-width-slot.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-modal-full-width-slot',
  styles: [
    `
      .playground {
        height: 500px;
        padding: 0;
        transform: translate3d(0, 0, 0);
      }
    `,
  ],
  template: `
    <div class="playground light" title="should display a full width div when using .stretch-to-full-modal-width">
      <p-content-wrapper>
        <div style="background: deeppink; height: 100vh"></div>
      </p-content-wrapper>
      <p-modal [open]="true" [aria]="{ 'aria-label': 'Some Heading' }">
        <div class="stretch-to-full-modal-width" style="background: deeppink; height: 60px"></div>
        <p-text>Some Content between two full width slotted divs</p-text>
        <div class="stretch-to-full-modal-width" style="background: deeppink; height: 60px"></div>
        <p-text>Some Content between two full width slotted divs</p-text>
        <div class="stretch-to-full-modal-width" style="background: deeppink; height: 60px"></div>
      </p-modal>
    </div>

    <div class="visualize-grid">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ModalFullWidthSlotComponent {}

// packages/components-react/projects/nextjs/pages/modal-full-width-slot.tsx
/* Auto Generated File */
import type { NextPage } from 'next';
import { PContentWrapper, PModal, PText } from '@porsche-design-system/components-react/ssr';

const ModalFullWidthSlotPage: NextPage = (): JSX.Element => {
  const style = `
    .playground {
      height: 500px;
      padding: 0;
      transform: translate3d(0, 0, 0);
    }
  `;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: style }} />

      <div className="playground light" title="should display a full width div when using .stretch-to-full-modal-width">
        <PContentWrapper>
          <div style={{ background: 'deeppink', height: '100vh' }} />
        </PContentWrapper>
        <PModal open={true} aria={{ 'aria-label': 'Some Heading' }}>
          <div className="stretch-to-full-modal-width" style={{ background: 'deeppink', height: '60px' }} />
          <PText>Some Content between two full width slotted divs</PText>
          <div className="stretch-to-full-modal-width" style={{ background: 'deeppink', height: '60px' }} />
          <PText>Some Content between two full width slotted divs</PText>
          <div className="stretch-to-full-modal-width" style={{ background: 'deeppink', height: '60px' }} />
        </PModal>
      </div>

      <div className="visualize-grid">
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
        <span />
      </div>
    </>
  );
};

export default ModalFullWidthSlotPage;
