// packages/components-angular/src/app/pages/model-signature.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-model-signature',
  template: `
    <div class="playground light" title="should render for model 718">
      <p-model-signature [model]="'718'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model 911">
      <p-model-signature [model]="'911'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model boxster">
      <p-model-signature [model]="'boxster'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model cayenne">
      <p-model-signature [model]="'cayenne'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model cayman">
      <p-model-signature [model]="'cayman'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model macan">
      <p-model-signature [model]="'macan'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model panamera">
      <p-model-signature [model]="'panamera'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model taycan">
      <p-model-signature [model]="'taycan'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model turbo">
      <p-model-signature [model]="'turbo'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color primary">
      <p-model-signature [model]="'911'" [color]="'primary'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color contrast-low">
      <p-model-signature [model]="'911'" [color]="'contrast-low'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color contrast-medium">
      <p-model-signature [model]="'911'" [color]="'contrast-medium'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color contrast-high">
      <p-model-signature [model]="'911'" [color]="'contrast-high'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color inherit">
      <p-model-signature
        [model]="'911'"
        [color]="'inherit'"
        style="filter: invert(24%) sepia(70%) saturate(5969%) hue-rotate(316deg) brightness(102%) contrast(102%)"
      ></p-model-signature>
    </div>

    <div class="playground light" title="should render for size small">
      <p-model-signature [model]="'911'" [size]="'small'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for size inherit">
      <p-model-signature [model]="'911'" [size]="'inherit'" style="height: 100px"></p-model-signature>
    </div>

    <div class="playground light" title="should not exceed parents width">
      <div style="width: 180px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" style="background: lightblue"></p-model-signature>
      </div>
      <br />
      <div style="width: 180px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" [size]="'inherit'" style="background: lightblue; height: 40px"></p-model-signature>
      </div>
    </div>

    <div
      class="playground light"
      title="should not exceed max-width of model-signature itself, although parent provides more width"
    >
      <div style="width: 272px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" style="background: lightblue"></p-model-signature>
      </div>
      <br />
      <div style="width: 272px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" [size]="'inherit'" style="background: lightblue; height: 40px"></p-model-signature>
      </div>
    </div>

    <div class="playground light" title="should not exceed parents height">
      <div style="height: 10px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" style="background: lightblue"></p-model-signature>
      </div>
      <br />
      <div style="height: 10px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" [size]="'inherit'" style="background: lightblue; height: 40px"></p-model-signature>
      </div>
    </div>

    <div
      class="playground light"
      title="should not exceed max-height of model-signature itself, although parent provides more height"
    >
      <div style="height: 100px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" style="background: lightblue"></p-model-signature>
      </div>
      <br />
      <div style="height: 100px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" [size]="'inherit'" style="background: lightblue; height: 40px"></p-model-signature>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ModelSignatureComponent {}

// packages/components-react/projects/nextjs/pages/model-signature.tsx
/* Auto Generated File */
import type { NextPage } from 'next';
import { PModelSignature } from '@porsche-design-system/components-react/ssr';

const ModelSignaturePage: NextPage = (): JSX.Element => {
  return (
    <>
      <div className="playground light" title="should render for model 718">
        <PModelSignature model="718" />
      </div>

      <div className="playground light" title="should render for model 911">
        <PModelSignature model="911" />
      </div>

      <div className="playground light" title="should render for model boxster">
        <PModelSignature model="boxster" />
      </div>

      <div className="playground light" title="should render for model cayenne">
        <PModelSignature model="cayenne" />
      </div>

      <div className="playground light" title="should render for model cayman">
        <PModelSignature model="cayman" />
      </div>

      <div className="playground light" title="should render for model macan">
        <PModelSignature model="macan" />
      </div>

      <div className="playground light" title="should render for model panamera">
        <PModelSignature model="panamera" />
      </div>

      <div className="playground light" title="should render for model taycan">
        <PModelSignature model="taycan" />
      </div>

      <div className="playground light" title="should render for model turbo">
        <PModelSignature model="turbo" />
      </div>

      <div className="playground light" title="should render for color primary">
        <PModelSignature model="911" color="primary" />
      </div>

      <div className="playground light" title="should render for color contrast-low">
        <PModelSignature model="911" color="contrast-low" />
      </div>

      <div className="playground light" title="should render for color contrast-medium">
        <PModelSignature model="911" color="contrast-medium" />
      </div>

      <div className="playground light" title="should render for color contrast-high">
        <PModelSignature model="911" color="contrast-high" />
      </div>

      <div className="playground light" title="should render for color inherit">
        <PModelSignature
          model="911"
          color="inherit"
          style={{ filter: 'invert(24%) sepia(70%) saturate(5969%) hue-rotate(316deg) brightness(102%) contrast(102%)' }}
         />
      </div>

      <div className="playground light" title="should render for size small">
        <PModelSignature model="911" size="small" />
      </div>

      <div className="playground light" title="should render for size inherit">
        <PModelSignature model="911" size="inherit" style={{ height: '100px' }} />
      </div>

      <div className="playground light" title="should not exceed parents width">
        <div style={{ width: '180px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" style={{ background: 'lightblue' }} />
        </div>
        <br />
        <div style={{ width: '180px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" size="inherit" style={{ background: 'lightblue', height: '40px' }} />
        </div>
      </div>

      <div
        className="playground light"
        title="should not exceed max-width of model-signature itself, although parent provides more width"
      >
        <div style={{ width: '272px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" style={{ background: 'lightblue' }} />
        </div>
        <br />
        <div style={{ width: '272px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" size="inherit" style={{ background: 'lightblue', height: '40px' }} />
        </div>
      </div>

      <div className="playground light" title="should not exceed parents height">
        <div style={{ height: '10px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" style={{ background: 'lightblue' }} />
        </div>
        <br />
        <div style={{ height: '10px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" size="inherit" style={{ background: 'lightblue', height: '40px' }} />
        </div>
      </div>

      <div
        className="playground light"
        title="should not exceed max-height of model-signature itself, although parent provides more height"
      >
        <div style={{ height: '100px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" style={{ background: 'lightblue' }} />
        </div>
        <br />
        <div style={{ height: '100px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" size="inherit" style={{ background: 'lightblue', height: '40px' }} />
        </div>
      </div>
    </>
  );
};

export default ModelSignaturePage;
