// packages/components-angular/src/app/pages/toast-basic-dark.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { ToastManager } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-toast-basic-dark',
  styles: [
    `
      .playground {
        height: 300px;
        padding: 0;
        transform: translateX(0);
        border: 1px solid deeppink;
      }
    `,
  ],
  template: `
    <div class="playground dark" title="should render toast neutral on dark background">
      <p-toast [theme]="'dark'"></p-toast>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToastBasicDarkComponent implements OnInit {
  constructor(private toastManager: ToastManager) {}

  ngOnInit() {
    this.toastManager.addMessage({ text: 'Some message' });
  }
}

// packages/components-react/projects/nextjs/pages/toast-basic-dark.tsx
/* Auto Generated File */
import type { NextPage } from 'next';
import { PToast, useToastManager } from '@porsche-design-system/components-react/ssr';
import { useEffect } from 'react';

const ToastBasicDarkPage: NextPage = (): JSX.Element => {
  const { addMessage } = useToastManager();
  useEffect(() => {
    addMessage({ text: 'Some message' });
  }, [addMessage]);

  const style = `
    .playground {
      height: 300px;
      padding: 0;
      transform: translateX(0);
      border: 1px solid deeppink;
    }
  `;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: style }} />

      <div className="playground dark" title="should render toast neutral on dark background">
        <PToast theme="dark" />
      </div>
    </>
  );
};

export default ToastBasicDarkPage;
