// packages/storefront/src/components/footer/Footer.tsx
import React from "react";
import { Link } from "react-router-dom";
import style from "./footer.module.scss";
import { Divider } from "@porsche/ui-kit-react";
import { Text } from "@porscheui/ui-kit-react";

export const Footer: React.FunctionComponent = () => {
  return (
    <footer className={style.footer}>
      <Divider spacing="small" />
      <Text type="small" align="center">
        © 2019 Dr. Ing. h.c. F. Porsche AG.
        <br />
        <a href="https://www.porsche.com/international/legal-notice/">Legal notice</a> /{" "}
        <a href="https://www.porsche.com/international/legal-notice/">Imprint</a> /{" "}
        <Link to="/general/license">License</Link>.
      </Text>
    </footer>
  );
};

// packages/storefront/src/components/Footer.vue
<template>
  <footer class="footer">
    <p-text size="x-small" align="center">
      <span>© 2020 Dr. Ing. h.c. F. Porsche AG.</span>
      <br />
      <a href="https://www.porsche.com/international/legal-notice/">Legal notice</a>
      <span> / </span>
      <a href="https://www.porsche.com/international/legal-notice/">Imprint</a>
      <span> / </span>
      <router-link :to="`/license`">License</router-link>
    </p-text>
  </footer>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';

@Component
export default class Footer extends Vue {
}
</script>
