// packages/components-vue/src/examples/AGGridExample.vue
<script setup lang="ts">
  import { AgGridVue } from 'ag-grid-vue3'; // Vue Data Grid Component
  import { dataAdvanced } from '@porsche-design-system/shared';
  import 'ag-grid-enterprise/styles/ag-grid.css';
  import '@porsche-design-system/components-js/ag-grid/theme-light.css';

  const ImageUrlRendererer = {
    template: `
      <img :src="cellValue.replace('/porsche-design-system/', '/dummyasset/')" width="80" height="45" alt="" />
    `,
    setup(props) {
      return {
        cellValue: props.params.value,
      };
    },
  };

  const columnDefs = [
    {
      field: 'imageUrl',
      cellRenderer: ImageUrlRendererer,
    },
    {
      field: 'model',
    },
    {
      field: 'date',
    },
    {
      field: 'interest',
    },
    {
      field: 'vin',
    },
    {
      field: 'purchaseIntention',
    },
    {
      field: 'status',
    },
    {
      field: 'comment',
    },
    {
      field: 'leadId',
    },
  ];
  // Configurations applied to all columns
  const defaultColDef = {
    filter: true,
    editable: true,
  };
</script>

<template>
  <ag-grid-vue
    :rowData="dataAdvanced"
    :columnDefs="columnDefs"
    :defaultColDef="defaultColDef"
    style="height: 80vh"
    class="ag-theme-quartz"
  >
  </ag-grid-vue>
</template>

// packages/components-react/src/examples/AGGridExample.tsx
import { AgGridReact } from 'ag-grid-react';
import { dataAdvanced, type DataAdvanced } from '@porsche-design-system/shared';
import { ColDef } from 'ag-grid-enterprise';
import 'ag-grid-enterprise/styles/ag-grid.css';
import '@porsche-design-system/components-js/ag-grid/theme-light.css';

const ImageUrlRendererer = ({ value }: { value: string }) => {
  return (
    <img
      src={value.replace('/porsche-design-system/', '/dummyasset/')}
      style={{
        marginInlineEnd: '8px',
        objectFit: 'contain',
      }}
      width="80"
      height="45"
      alt=""
    />
  );
};

const columnDefs: ColDef<DataAdvanced>[] = [
  {
    field: 'imageUrl',
    cellRenderer: ImageUrlRendererer,
  },
  {
    field: 'model',
  },
  {
    field: 'date',
  },
  {
    field: 'interest',
  },
  {
    field: 'vin',
  },
  {
    field: 'purchaseIntention',
  },
  {
    field: 'status',
  },
  {
    field: 'comment',
  },
  {
    field: 'leadId',
  },
];
// Configurations applied to all columns
const defaultColDef = {
  filter: true,
  editable: true,
};

export const AGGridExamplePage = (): JSX.Element => {
  return (
    <div className="ag-theme-quartz" style={{ height: '80vh' }}>
      <AgGridReact rowData={dataAdvanced} columnDefs={columnDefs} defaultColDef={defaultColDef} pagination={true} />
    </div>
  );
};
