// packages/components-angular/src/app/examples/banner-example.component.ts
import { ChangeDetectionStrategy, Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-banner-example',
  template: `
    <p-button type="button" (click)="onOpen()">Open Banner</p-button>
    <p-banner
      [open]="isBannerOpen"
      [heading]="'Some Heading'"
      [headingTag]="'h3'"
      [description]="'Some Description'"
      (dismiss)="onDismiss()"
    >
    </p-banner>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class BannerExampleComponent {
  isBannerOpen = false;

  onOpen() {
    this.isBannerOpen = true;
  }
  onDismiss() {
    this.isBannerOpen = false;
  }
}

// packages/components-react/src/examples/BannerExample.tsx
import { PBanner, PButton } from '@porsche-design-system/components-react';
import { useCallback, useState } from 'react';

export const BannerExamplePage = () => {
  const [isBannerOpen, setIsBannerOpen] = useState(false);

  const onOpen = useCallback(() => {
    setIsBannerOpen(true);
  }, []);

  const onDismiss = useCallback(() => {
    setIsBannerOpen(false);
  }, []);

  return (
    <>
      <PButton type="button" onClick={onOpen}>
        Open Banner
      </PButton>
      <PBanner
        open={isBannerOpen}
        heading="Some Heading"
        headingTag="h3"
        description="Some Description"
        onDismiss={onDismiss}
      />
    </>
  );
};
