// packages/components-angular/src/app/examples/banner-inline-example-action-button.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-banner-inline-example-action-button',
  template: `
    <p-banner-inline
      [heading]="'Some banner-inline heading'"
      [description]="'Some banner-inline description.'"
      [actionLabel]="'Retry'"
      [actionIcon]="'reset'"
      [actionLoading]="isLoading"
      (action)="onAction()"
    ></p-banner-inline>
    <p-button (click)="onAction()">Reset</p-button>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BannerInlineExampleActionButtonComponent {
  isLoading = false;

  onAction() {
    this.isLoading = !this.isLoading;
  }
}

// packages/components-react/src/examples/BannerInlineExampleActionButton.tsx
import { useCallback, useState } from 'react';
import { PBannerInline, PButton } from '@porsche-design-system/components-react';

export const BannerInlineExampleActionButtonPage = (): JSX.Element => {
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const onAction = useCallback(() => setIsLoading((prevValue) => !prevValue), []);

  return (
    <>
      <PBannerInline
        heading="Some banner-inline heading"
        description="Some banner-inline description."
        actionLabel="Retry"
        actionIcon="reset"
        actionLoading={isLoading}
        onAction={onAction}
      />
      <PButton onClick={onAction}>Reset</PButton>
    </>
  );
};
