// packages/components-vue/src/examples/InputPasswordExampleForm.vue
<template>
  <form @submit.prevent="onSubmit" @reset.prevent="onReset" class="flex flex-col gap-fluid-sm">
    <PInputPassword
      v-model:value="form.myInputPassword"
      :name="'myInputPassword'"
      :label="'Some Label'"
      :toggle="true"
    />
    <div class="flex gap-fluid-sm">
      <PButton type="submit">Submit</PButton>
      <PButton type="reset">Reset</PButton>
    </div>
    <PText>Last submitted data: {{ submittedValue }}</PText>
  </form>
</template>

<script setup lang="ts">
import { PButton, PInputPassword, PText } from '@porsche-design-system/components-vue';
import { reactive, ref } from 'vue';

const form = reactive({
  myInputPassword: '',
});

const submittedValue = ref();

const onSubmit = () => {
  submittedValue.value = JSON.stringify(form);
};

const onReset = () => {
  form.myInputPassword = '';
};
</script>

// packages/components-react/src/examples/InputPasswordExampleForm.tsx
import {
  type InputPasswordInputEvent,
  PButton,
  PInputPassword,
  type PInputPasswordProps,
  PText,
} from '@porsche-design-system/components-react';
import { type FormEvent, useState } from 'react';

export const InputPasswordExampleFormPage = () => {
  const [form, setForm] = useState<{ myInputPassword: PInputPasswordProps['value'] }>({ myInputPassword: '' });
  const [lastSubmittedData, setLastSubmittedData] = useState<any>();

  const onInput = (e: InputPasswordInputEvent) => {
    const { name, value } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const onSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLastSubmittedData(JSON.stringify(form));
  };

  const onReset = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setForm({ myInputPassword: '' });
  };

  return (
    <>
      <form onSubmit={onSubmit} onReset={onReset} className="flex flex-col gap-fluid-sm">
        <PInputPassword
          name="myInputPassword"
          label="Some Label"
          toggle={true}
          value={form.myInputPassword}
          onInput={onInput}
        />
        <div className="flex gap-fluid-sm">
          <PButton type="submit">Submit</PButton>
          <PButton type="reset">Reset</PButton>
        </div>
        <PText>Last submitted data: {lastSubmittedData}</PText>
      </form>
    </>
  );
};
