// packages/components-vue/src/examples/InputUrlExampleForm.vue
<template>
  <form @submit.prevent="onSubmit" @reset.prevent="onReset" class="flex flex-col gap-fluid-sm">
    <PInputUrl
      v-model:value="form.myInputUrl"
      :name="'myInputUrl'"
      :label="'Some Label'"
      :indicator="true"
    />
    <div class="flex gap-fluid-sm">
      <PButton type="submit">Submit</PButton>
      <PButton type="reset">Reset</PButton>
    </div>
    <PText>Last submitted data: {{ submittedValue }}</PText>
  </form>
</template>

<script setup lang="ts">
import { PButton, PInputUrl, PText } from '@porsche-design-system/components-vue';
import { reactive, ref } from 'vue';

const form = reactive({
  myInputUrl: '',
});

const submittedValue = ref();

const onSubmit = () => {
  submittedValue.value = JSON.stringify(form);
};

const onReset = () => {
  form.myInputUrl = '';
};
</script>

// packages/components-react/src/examples/InputUrlExampleForm.tsx
import {
  type InputUrlInputEvent,
  PButton,
  PInputUrl,
  type PInputUrlProps,
  PText,
} from '@porsche-design-system/components-react';
import { type FormEvent, useState } from 'react';

export const InputUrlExampleFormPage = () => {
  const [form, setForm] = useState<{ myInputUrl: PInputUrlProps['value'] }>({ myInputUrl: '' });
  const [lastSubmittedData, setLastSubmittedData] = useState<any>();

  const onInput = (e: InputUrlInputEvent) => {
    const { name, value } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const onSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLastSubmittedData(JSON.stringify(form));
  };

  const onReset = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setForm({ myInputUrl: '' });
  };

  return (
    <>
      <form onSubmit={onSubmit} onReset={onReset} className="flex flex-col gap-fluid-sm">
        <PInputUrl name="myInputUrl" label="Some Label" indicator={true} value={form.myInputUrl} onInput={onInput} />
        <div className="flex gap-fluid-sm">
          <PButton type="submit">Submit</PButton>
          <PButton type="reset">Reset</PButton>
        </div>
        <PText>Last submitted data: {lastSubmittedData}</PText>
      </form>
    </>
  );
};
