// packages/components-vue/src/examples/InputPasswordExampleControlled.vue
<script setup lang="ts">
import {
  type InputPasswordInputEventDetail,
  PInputPassword,
  type PInputPasswordProps,
  PText,
} from '@porsche-design-system/components-vue';
import { computed, ref } from 'vue';

const value = ref<PInputPasswordProps['value']>('');

const onInput = (e: CustomEvent<InputPasswordInputEventDetail>) => {
  value.value = (e.target as HTMLInputElement).value;
};

const debugText = computed(() => {
  return `Value: ${value.value}`;
});
</script>

<template>
  <PInputPassword :name="'some-name'" :label="'Some Label'" :value="value" @input="onInput" />
  <PText>{{ debugText }}</PText>
</template>

// packages/components-react/src/examples/InputPasswordExampleControlled.tsx
import {
  type InputPasswordInputEventDetail,
  PInputPassword,
  type PInputPasswordProps,
  PText,
} from '@porsche-design-system/components-react';
import { useState } from 'react';

export const InputPasswordControlledExamplePage = () => {
  const [value, setValue] = useState<PInputPasswordProps['value']>('');

  const onInput = (e: CustomEvent<InputPasswordInputEventDetail>) => {
    setValue((e.detail.target as HTMLInputElement).value);
  };

  return (
    <>
      <PInputPassword
        name="some-name"
        label="Some Label"
        value={value}
        onInput={(e) => onInput(e as CustomEvent<InputPasswordInputEventDetail>)}
      />
      <PText>Value: {value}</PText>
    </>
  );
};
