// packages/components-vue/src/examples/InputEmailExampleForm.vue
<template>
  <form @submit.prevent="onSubmit" @reset.prevent="onReset" class="flex flex-col gap-fluid-sm">
    <PInputEmail
      v-model:value="form.myInputEmail"
      :name="'myInputEmail'"
      :label="'Some Label'"
      :indicator="true"
    />
    <div class="flex gap-fluid-sm">
      <PButton type="submit">Submit</PButton>
      <PButton type="reset">Reset</PButton>
    </div>
    <PText>Last submitted data: {{ submittedValue }}</PText>
  </form>
</template>

<script setup lang="ts">
import { PButton, PInputEmail, PText } from '@porsche-design-system/components-vue';
import { reactive, ref } from 'vue';

const form = reactive({
  myInputEmail: '',
});

const submittedValue = ref();

const onSubmit = () => {
  submittedValue.value = JSON.stringify(form);
};

const onReset = () => {
  form.myInputEmail = '';
};
</script>

// packages/components-react/src/examples/InputEmailExampleForm.tsx
import {
  type InputEmailInputEvent,
  PButton,
  PInputEmail,
  type PInputEmailProps,
  PText,
} from '@porsche-design-system/components-react';
import { type FormEvent, useState } from 'react';

export const InputEmailExampleFormPage = () => {
  const [form, setForm] = useState<{ myInputEmail: PInputEmailProps['value'] }>({ myInputEmail: '' });
  const [lastSubmittedData, setLastSubmittedData] = useState<any>();

  const onInput = (e: InputEmailInputEvent) => {
    const { name, value } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const onSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLastSubmittedData(JSON.stringify(form));
  };

  const onReset = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setForm({ myInputEmail: '' });
  };

  return (
    <>
      <form onSubmit={onSubmit} onReset={onReset} className="flex flex-col gap-fluid-sm">
        <PInputEmail
          name="myInputEmail"
          label="Some Label"
          indicator={true}
          value={form.myInputEmail}
          onInput={onInput}
        />
        <div className="flex gap-fluid-sm">
          <PButton type="submit">Submit</PButton>
          <PButton type="reset">Reset</PButton>
        </div>
        <PText>Last submitted data: {lastSubmittedData}</PText>
      </form>
    </>
  );
};
