// packages/components-vue/src/examples/InputEmailExampleControlled.vue
<script setup lang="ts">
import {
  type InputEmailInputEventDetail,
  PInputEmail,
  type PInputEmailProps,
  PText,
} from '@porsche-design-system/components-vue';
import { computed, ref } from 'vue';

const value = ref<PInputEmailProps['value']>('abc');

const onInput = (e: CustomEvent<InputEmailInputEventDetail>) => {
  value.value = (e.target as HTMLInputElement).value;
};

const debugText = computed(() => {
  return `Value: ${value.value}`;
});
</script>

<template>
  <PInputEmail :name="'some-name'" :label="'Some Label'" :value="value" @input="onInput" />
  <PText>{{ debugText }}</PText>
</template>

// packages/components-react/src/examples/InputEmailExampleControlled.tsx
import {
  type InputEmailInputEventDetail,
  PInputEmail,
  type PInputEmailProps,
  PText,
} from '@porsche-design-system/components-react';
import { useState } from 'react';

export const InputEmailControlledExamplePage = () => {
  const [value, setValue] = useState<PInputEmailProps['value']>('');

  const onInput = (e: CustomEvent<InputEmailInputEventDetail>) => {
    setValue((e.detail.target as HTMLInputElement).value);
  };

  return (
    <>
      <PInputEmail
        name="some-name"
        label="Some Label"
        value={value}
        onInput={(e) => onInput(e as CustomEvent<InputEmailInputEventDetail>)}
      />
      <PText>Value: {value}</PText>
    </>
  );
};
