// packages/components-vue/src/examples/LinkTileExampleHyphens.vue
<script setup lang="ts">
import { PLinkTile, PSelect, PSelectOption, type SelectChangeEventDetail } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const selectedValue = ref<string | number | null | undefined>('auto');

const onUpdate = (e: CustomEvent<SelectChangeEventDetail>) => {
  selectedValue.value = e.detail.value;
};
</script>

<template>
  <PSelect label="Select hyphens" name="hyphens" :value="selectedValue" @update="onUpdate">
    <PSelectOption value="auto">style="hyphens: auto;"</PSelectOption>
    <PSelectOption value="manual">style="hyphens: manual;"</PSelectOption>
    <PSelectOption value="none">style="hyphens: none;"</PSelectOption>
  </PSelect>

  <PLinkTile
    href="https://porsche.com"
    label="Some label"
    description="An extra&shy;ordinarily Porsche"
    :compact="true"
    size="inherit"
    :style="{ maxWidth: '400px', fontSize: '45px', hyphens: selectedValue }"
    class="mt-fluid-sm"
  >
  <img src="http://localhost:3002/lights.jpg" alt="Some image description" />
  </PLinkTile>
</template>

// packages/components-react/src/examples/LinkTileExampleHyphens.tsx
import { PLinkTile, PSelect, PSelectOption, SelectChangeEventDetail } from '@porsche-design-system/components-react';
import { Property } from 'csstype';
import { useState } from 'react';

export const LinkTileExampleHyphensPage = () => {
  const [hyphens, setHyphens] = useState<Property.Hyphens>('auto');

  const onChange = (e: CustomEvent<SelectChangeEventDetail>) => {
    setHyphens(e.detail.value as Property.Hyphens);
  };

  return (
    <>
      <PSelect label="Select hyphens" name="hyphens" value={hyphens} onChange={onChange}>
        <PSelectOption value="auto">style="hyphens: auto;"</PSelectOption>
        <PSelectOption value="manual">style="hyphens: manual;"</PSelectOption>
        <PSelectOption value="none">style="hyphens: none;"</PSelectOption>
      </PSelect>

      <PLinkTile
        href="https://porsche.com"
        label="Some label"
        description="An extra&shy;ordinarily Porsche"
        compact={true}
        size="inherit"
        style={{ colorScheme: 'dark', maxWidth: '400px', fontSize: '45px', hyphens }}
        className="mt-fluid-sm"
      >
        <img src="http://localhost:3002/lights.jpg" alt="Some image description" />
      </PLinkTile>
    </>
  );
};
