// packages/components-vue/src/examples/MultiSelectExampleAsyncFilter.vue
<template>
  <PMultiSelect
    name="async-search-select"
    label="Async Search"
    :value="value"
    @change="onChange"
    @toggle="onToggle"
  >
    <PInputSearch
      slot="filter"
      name="search"
      clear
      indicator
      compact
      autocomplete="off"
      :loading="loading"
      :value="searchValue"
      @input="onInput"
      @blur.stop
      @change.stop
    />

    <!-- Initial skeleton loading -->
    <template v-if="initialLoading && !error">
      <div v-for="i in 9" :key="i" slot="options-status" class="skeleton h-[40px]" />
    </template>

    <!-- Options -->
    <PMultiSelectOption v-for="opt in options" :key="opt.value" :value="opt.value">
      {{ opt.label }}
    </PMultiSelectOption>

    <!-- No filter results -->
    <div
      v-if="!initialLoading && options.length === 0 && !error"
      slot="options-status"
      class="text-contrast-medium cursor-not-allowed py-static-sm px-[12px]"
      role="status"
    >
      <span aria-hidden="true">–</span>
      <span class="sr-only">No results found</span>
    </div>

    <!-- Error state -->
    <div
      v-if="error"
      slot="options-status"
      class="flex gap-static-sm py-static-sm px-[12px]"
      role="alert"
    >
      <PIcon name="information" color="error" />
      <span class="text-error">{{ error }}</span>
    </div>
  </PMultiSelect>
</template>

<script setup lang="ts">
import {
  type InputSearchInputEventDetail,
  type MultiSelectChangeEventDetail,
  type MultiSelectToggleEventDetail,
  PIcon,
  PInputSearch,
  PMultiSelect,
  PMultiSelectOption,
  type PMultiSelectProps,
} from '@porsche-design-system/components-vue';
import { ref } from 'vue';

function useDebounce<T>(callback: (value: T) => void, delay = 400) {
  let timer: number | undefined;
  return (value: T) => {
    if (timer) clearTimeout(timer);
    timer = window.setTimeout(() => callback(value), delay);
  };
}

const value = ref<PMultiSelectProps['value']>([]);
const options = ref<{ value: string; label: string }[]>([]);
const searchValue = ref('');
const initialLoading = ref(false);
const loading = ref(false);
const error = ref<string | null>(null);

const hasLoadedOnce = ref(false);
let currentFetchId = 0;

// 💡 Consider using Vue Query or SWRV for data fetching.
async function fetchOptions(term?: string, isInitial?: boolean) {
  const fetchId = ++currentFetchId;
  if (isInitial) initialLoading.value = true;
  else loading.value = true;

  try {
    const url = term
      ? `https://jsonplaceholder.typicode.com/users?username_like=${term}`
      : `https://jsonplaceholder.typicode.com/users`;
    const res = await fetch(url);
    const data: { id: number; name: string; username: string }[] = await res.json();

    if (fetchId !== currentFetchId) return; // ignore stale fetch

    options.value = data.map((user) => ({
      value: user.id.toString(),
      label: `${user.name} (${user.username})`,
    }));
    error.value = null;
    hasLoadedOnce.value = true;
  } catch (err) {
    console.error('Failed to fetch options', err);
    options.value = [];
    error.value = 'Failed to load options';
  } finally {
    if (isInitial) initialLoading.value = false;
    else loading.value = false;
  }
}

const debouncedFetch = useDebounce((term?: string) => fetchOptions(term), 400);

function onInput(e: CustomEvent<InputSearchInputEventDetail>) {
  const term = (e.target as HTMLInputElement).value;
  searchValue.value = term;
  debouncedFetch(term.trim() || undefined);
}

function onChange(e: CustomEvent<MultiSelectChangeEventDetail>) {
  // Can be called from bubbling onChange event of PInputSearch, ignore those
  if (e.detail.name) {
    value.value = e.detail.value;
  }
}

function onToggle(e: CustomEvent<MultiSelectToggleEventDetail>) {
  if (e.detail.open && !hasLoadedOnce.value) {
    fetchOptions(undefined, true);
  }
}
</script>

// packages/components-react/src/examples/MultiSelectExampleAsyncFilter.tsx
import {
  type InputSearchInputEventDetail,
  type MultiSelectChangeEventDetail,
  type MultiSelectToggleEventDetail,
  PIcon,
  PInputSearch,
  PMultiSelect,
  PMultiSelectOption,
  type PMultiSelectProps,
} from '@porsche-design-system/components-react';
import { useCallback, useRef, useState } from 'react';

const useDebounce = <T,>(callback: (value: T) => void, delay = 400) => {
  const timer = useRef<number | undefined>(undefined);
  return (value: T) => {
    if (timer.current) clearTimeout(timer.current);
    timer.current = window.setTimeout(() => callback(value), delay);
  };
};

export const MultiSelectExampleAsyncFilter = () => {
  const [value, setValue] = useState<PMultiSelectProps['value']>([]);
  const [options, setOptions] = useState<{ value: string; label: string }[]>([]);

  const [searchValue, setSearchValue] = useState('');
  const [initialLoading, setInitialLoading] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const hasLoadedOnce = useRef(false);
  const currentFetchId = useRef(0);

  // 💡Consider using a data-fetching library like React Query or SWR here.
  // They provide built-in caching, deduplication, retries, and loading/error state management,
  // which would make this async logic cleaner and more reliable than manual fetch handling.
  const fetchOptions = useCallback(async (term?: string, isInitial?: boolean) => {
    const fetchId = ++currentFetchId.current;
    isInitial ? setInitialLoading(true) : setLoading(true);
    try {
      const url = term
        ? `https://jsonplaceholder.typicode.com/users?username_like=${term}`
        : `https://jsonplaceholder.typicode.com/users`;

      const res = await fetch(url);
      const data: { id: number; name: string; username: string }[] = await res.json();

      // Ignore stale results
      if (fetchId !== currentFetchId.current) return;

      const newOptions = data.map((user) => ({
        value: user.id.toString(),
        label: `${user.name} (${user.username})`,
      }));

      setOptions(newOptions);
      setError(null);
      hasLoadedOnce.current = true;
    } catch (err) {
      console.error('Failed to fetch options', err);
      setOptions([]);
      setError('Failed to load options');
    } finally {
      isInitial ? setInitialLoading(false) : setLoading(false);
    }
  }, []);

  const debouncedFetch = useDebounce(fetchOptions, 400);

  const onInput = (e: CustomEvent<InputSearchInputEventDetail>) => {
    const term = (e.target as HTMLElement & { value: string }).value;
    setSearchValue(term);
    debouncedFetch(term.trim() || undefined);
  };

  const onChange = (e: CustomEvent<MultiSelectChangeEventDetail>) => {
    setValue((e.target as HTMLElement & { value: string[] }).value);
  };

  const onToggle = async (e: CustomEvent<MultiSelectToggleEventDetail>) => {
    if (e.detail.open && !hasLoadedOnce.current) {
      fetchOptions(undefined, true);
    }
  };

  return (
    <PMultiSelect name="async-search-select" label="Async Search" value={value} onChange={onChange} onToggle={onToggle}>
      <PInputSearch
        slot="filter"
        name="search"
        value={searchValue}
        loading={loading}
        clear
        indicator
        compact
        autoComplete="off"
        onInput={onInput}
        // Prevent bubbling
        onBlur={(e: any) => e.stopPropagation()}
        onChange={(e: any) => e.stopPropagation()}
      />

      {/* Initial skeleton loading */}
      {initialLoading &&
        !error &&
        Array.from({ length: 9 }).map((_, i) => <div key={i} slot="options-status" className="skeleton h-[40px]" />)}

      {/* Options */}
      {options.map((opt) => (
        <PMultiSelectOption key={opt.value} value={opt.value}>
          {opt.label}
        </PMultiSelectOption>
      ))}

      {/* No filter results */}
      {!initialLoading && options.length === 0 && !error && (
        <div
          slot="options-status"
          className="text-contrast-medium cursor-not-allowed py-static-sm px-[12px]"
          role="status"
        >
          <span aria-hidden="true">–</span>
          <span className="sr-only">No results found</span>
        </div>
      )}

      {/* Error state */}
      {error && (
        <div slot="options-status" className="flex gap-static-sm py-static-sm px-[12px]" role="alert">
          <PIcon name="information" color="error" />
          <span className="text-error">{error}</span>
        </div>
      )}
    </PMultiSelect>
  );
};
