// packages/components-vue/src/examples/SelectExampleDynamic.vue
<script setup lang="ts">
import {
  PButton,
  PInputText,
  PSelect,
  PSelectOption,
  type PSelectProps,
  type SelectChangeEventDetail,
} from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const selectedValue = ref<PSelectProps['value']>('1');
const inputValue = ref<string>('');
const optionCount = ref<number>(3);

const onSetValue = () => {
  selectedValue.value = inputValue.value;
};

const onResetValue = () => {
  selectedValue.value = '1';
  inputValue.value = '';
};

const onChange = (e: CustomEvent<SelectChangeEventDetail>) => {
  selectedValue.value = e.detail.value;
  inputValue.value = String(e.detail.value ?? '');
};

const onAddOption = () => {
  optionCount.value++;
};

const onRemoveOption = () => {
  if (optionCount.value > 0) {
    optionCount.value--;
  }
};
</script>

<template>
  <div class="flex flex-col gap-fluid-sm">
    <PInputText label="Value:" name="input-value" v-model:value="inputValue" placeholder="e.g. 1" />
    <div class="flex gap-fluid-sm">
      <PButton type="button" @click="onSetValue" :compact="true">Set Value</PButton>
      <PButton type="button" @click="onResetValue" :compact="true">Reset value</PButton>
    </div>
    <PSelect :name="'options'" :label="'Some Label'" :value="selectedValue" @change="onChange">
      <PSelectOption v-for="idx in optionCount" :key="idx" :value="`${idx}`"> Option {{ idx }} </PSelectOption>
    </PSelect>
    <div class="flex gap-fluid-sm">
      <PButton type="button" @click="onAddOption" :compact="true">Add option</PButton>
      <PButton type="button" @click="onRemoveOption" :compact="true">Remove last option</PButton>
    </div>
  </div>
</template>

// packages/components-react/src/examples/SelectExampleDynamic.tsx
import {
  type InputTextInputEventDetail,
  PButton,
  PInputText,
  PSelect,
  PSelectOption,
  type PSelectProps,
  SelectChangeEventDetail,
} from '@porsche-design-system/components-react';
import { useState } from 'react';

export const SelectExampleDynamicPage = () => {
  const [selectedValue, setSelectedValue] = useState<PSelectProps['value']>('1');
  const [inputValue, setInputValue] = useState('');
  const [optionCount, setOptionCount] = useState(3);

  const onChangeInput = (e: CustomEvent<InputTextInputEventDetail>) => {
    setInputValue((e.detail.target as HTMLInputElement).value);
  };

  const onSetValue = () => {
    setSelectedValue(inputValue);
  };

  const onResetValue = () => {
    setSelectedValue('1');
    setInputValue('');
  };

  const onChange = (e: CustomEvent<SelectChangeEventDetail>) => {
    setSelectedValue(e.detail.value);
    setInputValue(String(e.detail.value ?? ''));
  };

  const onAddOption = () => {
    setOptionCount((prev) => prev + 1);
  };

  const onRemoveOption = () => {
    if (optionCount > 0) {
      setOptionCount((prev) => prev - 1);
    }
  };

  return (
    <div className="flex flex-col gap-fluid-sm">
      <PInputText
        name="input-value"
        label="Value:"
        placeholder="e.g. 1,2"
        value={inputValue}
        onInput={(e) => onChangeInput(e as CustomEvent<InputTextInputEventDetail>)}
      />
      <div className="flex gap-fluid-sm">
        <PButton type="button" onClick={onSetValue} compact={true}>
          Set Value
        </PButton>
        <PButton type="button" onClick={onResetValue} compact={true}>
          Reset value
        </PButton>
      </div>
      <PSelect name="options" label="Some Label" value={selectedValue} onChange={onChange}>
        {[...Array(optionCount).keys()].map((idx) => (
          <PSelectOption key={idx} value={`${idx + 1}`}>
            Option {idx + 1}
          </PSelectOption>
        ))}
      </PSelect>
      <div className="flex gap-fluid-sm">
        <PButton type="button" onClick={onAddOption} compact={true}>
          Add option
        </PButton>
        <PButton type="button" onClick={onRemoveOption} compact={true}>
          Remove last option
        </PButton>
      </div>
    </div>
  );
};
