// packages/components-vue/src/examples/TableExampleAdvanced.vue
<script setup lang="ts">
  import { dataAdvanced, headAdvanced } from '@porsche-design-system/shared';
  import {
    PButtonPure,
    PHeading,
    PTable,
    PTableBody,
    PTableCell,
    PTableHead,
    PTableHeadCell,
    PTableHeadRow,
    PTableRow,
    PText,
  } from '@porsche-design-system/components-vue';
  import type { DataAdvanced } from '@porsche-design-system/shared';
  import { ref } from 'vue';

  import type { TableChangeEvent } from '@porsche-design-system/components-vue';

  const head = ref(headAdvanced);
  const data = ref(dataAdvanced);

  const onChange = (e: CustomEvent<TableChangeEvent>): void => {
    const { id, direction } = e as TableChangeEvent & { id: keyof DataAdvanced };
    head.value = head.value.map((item) => ({ ...item, active: false, ...(item.id === id && e) }));
    data.value = [...data.value].sort((a, b) =>
      direction === 'asc' ? a[id].localeCompare(b[id]) : b[id].localeCompare(a[id])
    );
  };
</script>

<template>
  <PTable @change="onChange">
    <PHeading :slot="'caption'" :size="'large'"> Some visual caption </PHeading>
    <PTableHead>
      <PTableHeadRow>
        <PTableHeadCell v-for="(item, index) in head" :key="index" :sort="item" :hideLabel="item.hideLabel">
          {{ item.name }}
        </PTableHeadCell>
      </PTableHeadRow>
    </PTableHead>
    <PTableBody>
      <PTableRow v-for="(item, index) in data" :key="index">
        <PTableCell>
          <div :style="{ display: 'flex' }">
            <img :src="item.imageUrl" :width="80" :height="45" :style="{ marginRight: '.5rem' }" alt="" />
            <div>
              <PText :weight="'semi-bold'">{{ item.model }}</PText>
              <PText :size="'x-small'">{{ item.date }}</PText>
            </div>
          </div>
        </PTableCell>
        <PTableCell>{{ item.interest }}</PTableCell>
        <PTableCell>
          <a :href="'https://porsche.com'">{{ item.vin }}</a>
        </PTableCell>
        <PTableCell>{{ item.purchaseIntention }}</PTableCell>
        <PTableCell>{{ item.status }}</PTableCell>
        <PTableCell :multiline="true" :style="{ minWidth: '10rem' }">
          {{ item.comment }}
        </PTableCell>
        <PTableCell>{{ item.leadId }}</PTableCell>
        <PTableCell>
          <PButtonPure :icon="'edit'" :style="{ padding: '.5rem' }"> Edit </PButtonPure>
          <PButtonPure :icon="'delete'" :style="{ padding: '.5rem' }"> Delete </PButtonPure>
        </PTableCell>
      </PTableRow>
    </PTableBody>
  </PTable>
</template>

// packages/components-react/src/examples/TableExampleAdvanced.tsx
import type { TableChangeEvent } from '@porsche-design-system/components-react';
import {
  PButtonPure,
  PHeading,
  PTable,
  PTableBody,
  PTableCell,
  PTableHead,
  PTableHeadCell,
  PTableHeadRow,
  PTableRow,
  PText,
} from '@porsche-design-system/components-react';
import { useCallback, useState } from 'react';
import { dataAdvanced, DataAdvanced, headAdvanced } from '@porsche-design-system/shared';

export const TableExampleAdvancedPage = (): JSX.Element => {
  const [head, setHead] = useState(headAdvanced);
  const [data, setData] = useState(dataAdvanced);

  const onUpdate = useCallback((e: CustomEvent<TableChangeEvent>) => {
    const { id, direction } = e.detail as TableChangeEvent & { id: keyof DataAdvanced };
    setHead((prev) => prev.map((item) => ({ ...item, active: false, ...(item.id === id && e.detail) })));
    setData((prev) =>
      [...prev].sort((a, b) => {
        return direction === 'asc' ? a[id].localeCompare(b[id]) : b[id].localeCompare(a[id]);
      })
    );
  }, []);

  return (
    <PTable onUpdate={onUpdate}>
      <PHeading slot="caption" size="large">
        Some visual caption
      </PHeading>
      <PTableHead>
        <PTableHeadRow>
          {head.map((item, i) => (
            <PTableHeadCell key={i} sort={item} hideLabel={item.hideLabel}>
              {item.name}
            </PTableHeadCell>
          ))}
        </PTableHeadRow>
      </PTableHead>
      <PTableBody>
        {data.map((item, i) => (
          <PTableRow key={i}>
            <PTableCell>
              <div style={{ display: 'flex' }}>
                <img src={item.imageUrl} width={80} height={45} style={{ marginRight: '.5rem' }} alt="" />
                <div>
                  <PText weight="semi-bold">{item.model}</PText>
                  <PText size="x-small">{item.date}</PText>
                </div>
              </div>
            </PTableCell>
            <PTableCell>{item.interest}</PTableCell>
            <PTableCell>
              <a href="https://porsche.com">{item.vin}</a>
            </PTableCell>
            <PTableCell>{item.purchaseIntention}</PTableCell>
            <PTableCell>{item.status}</PTableCell>
            <PTableCell multiline={true} style={{ minWidth: '10rem' }}>
              {item.comment}
            </PTableCell>
            <PTableCell>{item.leadId}</PTableCell>
            <PTableCell>
              <PButtonPure icon="edit" style={{ padding: '.5rem' }}>
                Edit
              </PButtonPure>
              <PButtonPure icon="delete" style={{ padding: '.5rem' }}>
                Delete
              </PButtonPure>
            </PTableCell>
          </PTableRow>
        ))}
      </PTableBody>
    </PTable>
  );
};
