// packages/components-vue/src/examples/TextareaExampleControlled.vue
<script setup lang="ts">
import { PText, PTextarea, type TextareaInputEventDetail } from '@porsche-design-system/components-vue';
import { computed, ref } from 'vue';

const value = ref<string>('');

const onInput = (e: CustomEvent<TextareaInputEventDetail>) => {
  value.value = (e.target as HTMLTextAreaElement).value;
};

const debugText = computed(() => {
  return `Value: ${value.value}`;
});
</script>

<template>
  <PTextarea :name="'some-name'" :label="'Some Label'" :value="value" @input="onInput" />
  <PText>{{ debugText }}</PText>
</template>

// packages/components-react/src/examples/TextareaExampleControlled.tsx
import { useState } from 'react';
import { PText, type PTextareaProps } from '@porsche-design-system/components-react';
import { PTextarea } from '@porsche-design-system/components-react';
import { TextareaInputEventDetail } from '@porsche-design-system/components';

export const TextareaControlledExamplePage = (): JSX.Element => {
  const [value, setValue] = useState<PTextareaProps['value']>('');

  const onInput = (e: CustomEvent<TextareaInputEventDetail>) => {
    setValue((e.target as HTMLTextAreaElement).value);
  };

  const debugText = `Value: ${value}`;

  return (
    <>
      <PTextarea name="some-name" value={value} onInput={(e) => onInput(e as CustomEvent<TextareaInputEventDetail>)} />
      <PText>{debugText}</PText>
    </>
  );
};
