// packages/components-vue/src/examples/ToastExample.vue
<script setup lang="ts">
import { PToast, useToastManager } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const { addMessage } = useToastManager();
const counter = ref(1);

const onButtonClick = (): void => {
  addMessage({ text: `Some message ${counter.value}`, state: 'success' });
  counter.value = counter.value + 1;
};
</script>

<template>
  <button type="button" @click="onButtonClick">Queue Toast</button>
  <PToast />
</template>

// packages/components-react/src/examples/ToastExample.tsx
import { useToastManager, PToast } from '@porsche-design-system/components-react';
import { useState } from 'react';

export const ToastExample = (): JSX.Element => {
  const { addMessage } = useToastManager();
  const [counter, setCounter] = useState(1);

  const onButtonClick = () => {
    addMessage({ text: `Some message ${counter}`, state: 'success' });
    setCounter((prev) => prev + 1);
  };

  return (
    <>
      <button type="button" onClick={onButtonClick}>
        Queue Toast
      </button>
      <PToast />
    </>
  );
};
