// packages/components-vue/projects/vue-wrapper/skill/references/components/p-accordion/examples/StickySummary.vue
<script setup lang="ts">
  import { ref } from 'vue';
  import { PAccordion, PHeading, PText, type AccordionUpdateEventDetail } from '@porsche-design-system/components-vue';

  const open = ref(true);

  const onUpdate = (e: CustomEvent<AccordionUpdateEventDetail>) => {
    open.value = e.detail.open;
  }
</script>

<template>
  <PAccordion :open="open" :sticky="true" background="surface" class="[--p-accordion-summary-top:40px]" @update="onUpdate">
    <PHeading slot="summary" tag="h3" size="small" weight="semibold">
      Some summary
    </PHeading>
    <PText>
      Some details. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.
    </PText>
  </PAccordion>
</template>

// packages/components-react/projects/react-wrapper/skill/references/components/p-accordion/examples/StickySummary.tsx
import React from 'react';
import { useState } from 'react';
import { PAccordion, PHeading, PText, type AccordionUpdateEventDetail } from '@porsche-design-system/components-react';

export const Example = () => {
  const [open, setOpen] = useState(true);

  const onUpdate = (e: CustomEvent<AccordionUpdateEventDetail>) => {
    setOpen(e.detail.open);
  }

  return (
    <>
      <PAccordion open={open} sticky={true} background="surface" className="[--p-accordion-summary-top:40px]" onUpdate={onUpdate}>
        <PHeading slot="summary" tag="h3" size="small" weight="semibold">
          Some summary
        </PHeading>
        <PText>
          Some details. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.
        </PText>
      </PAccordion>
    </>
  )
}
