// packages/components-angular/projects/angular-wrapper/skill/references/components/p-fieldset/examples/SlottedLabel.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
      <p-fieldset>
        <span slot="label">
          Some legend label
        </span>
        <p-input-text label="Some label" name="some-name"></p-input-text>
      </p-fieldset>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule], // <-- PDS module is imported here
})
export class ExampleComponent {}

// packages/components-react/projects/react-wrapper/skill/references/components/p-fieldset/examples/SlottedLabel.tsx
import React from 'react';
import { PFieldset, PInputText } from '@porsche-design-system/components-react';

export const Example = () => {
  return (
    <>
      <PFieldset>
        <span slot="label">
          Some legend label
        </span>
        <PInputText label="Some label" name="some-name"></PInputText>
      </PFieldset>
    </>
  )
}
