// packages/components-angular/projects/angular-wrapper/skill/references/components/p-link-tile/examples/FooterSlot.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
      <div class="grid grid-cols-2 gap-static-md">
        <p-link-tile href="https://porsche.com" label="Some label" description="Some Description">
          <p-tag slot="header" color="background-frosted" [compact]="true">
            Some tag
          </p-tag>
          <img src="assets/lights.jpg" alt="Some image description" />
          <p-text slot="footer">
            Some footer text
          </p-text>
        </p-link-tile>
        <p-link-tile href="https://porsche.com" label="Some label" description="Some Description" [compact]="true">
          <p-tag slot="header" color="background-frosted" [compact]="true">
            Some tag
          </p-tag>
          <img src="assets/lights.jpg" alt="Some image description" />
          <p-text slot="footer">
            Some footer text
          </p-text>
        </p-link-tile>
      </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule], // <-- PDS module is imported here
})
export class ExampleComponent {}

// packages/components-vue/projects/vue-wrapper/skill/references/components/p-link-tile/examples/FooterSlot.vue
<script setup lang="ts">
  import { PLinkTile, PTag, PText } from '@porsche-design-system/components-vue';
</script>

<template>
  <div class="grid grid-cols-2 gap-static-md">
    <PLinkTile href="https://porsche.com" label="Some label" description="Some Description">
      <PTag slot="header" color="background-frosted" :compact="true">
        Some tag
      </PTag>
      <img src="assets/lights.jpg" alt="Some image description" />
      <PText slot="footer">
        Some footer text
      </PText>
    </PLinkTile>
    <PLinkTile href="https://porsche.com" label="Some label" description="Some Description" :compact="true">
      <PTag slot="header" color="background-frosted" :compact="true">
        Some tag
      </PTag>
      <img src="assets/lights.jpg" alt="Some image description" />
      <PText slot="footer">
        Some footer text
      </PText>
    </PLinkTile>
  </div>
</template>
