// packages/components-react/src/examples/CarouselExampleJumpToSlide.tsx
import { type CarouselUpdateEventDetail, PButton, PCarousel } from '@porsche-design-system/components-react';
import { type MouseEvent, useCallback, useState } from 'react';

export const CarouselExampleJumpToSlidePage = () => {
  const [activeSlideIndex, setActiveSlideIndex] = useState(1);
  const onUpdate = useCallback(
    (e: CustomEvent<CarouselUpdateEventDetail>) => setActiveSlideIndex(e.detail.activeIndex),
    []
  );
  const onButtonClick = useCallback(
    (e: MouseEvent<HTMLButtonElement> & { target: HTMLButtonElement }) =>
      setActiveSlideIndex(parseInt(e.target.innerText) - 1),
    []
  );

  const slideStyle = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#00b0f4',
    height: '150px',
  };

  return (
    <>
      <PCarousel heading="Some Heading" activeSlideIndex={activeSlideIndex} onUpdate={onUpdate}>
        <div style={slideStyle}>Slide 1</div>
        <div style={slideStyle}>Slide 2</div>
        <div style={slideStyle}>Slide 3</div>
      </PCarousel>

      <div className="flex gap-fluid-sm mt-fluid-sm">
        {Array.from(Array(3)).map((_, i) => (
          <PButton key={i} type="button" onClick={onButtonClick} disabled={activeSlideIndex === i}>
            {i + 1}
          </PButton>
        ))}
      </div>
    </>
  );
};

// packages/components-vue/src/examples/CarouselExampleJumpToSlide.vue
<script setup lang="ts">
import { type CarouselUpdateEventDetail, PButton, PCarousel } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const activeSlideIndex = ref(1);

const onUpdate = (e: CustomEvent<CarouselUpdateEventDetail>): void => {
  activeSlideIndex.value = e.detail.activeIndex;
};
const onButtonClick = (e: MouseEvent): void => {
  activeSlideIndex.value = parseInt((e.target as HTMLButtonElement).innerText) - 1;
};
</script>

<template>
  <PCarousel :heading="'Some Heading'" :activeSlideIndex="activeSlideIndex" @update="onUpdate">
    <div>Slide 1</div>
    <div>Slide 2</div>
    <div>Slide 3</div>
  </PCarousel>

  <div class="flex gap-fluid-sm mt-fluid-sm">
    <PButton
      v-for="(_, i) in Array.from(Array(3))"
      :key="i"
      type="button"
      @click="onButtonClick"
      :disabled="activeSlideIndex === i"
    >
      {{ i + 1 }}
    </PButton>
  </div>
</template>
<style scoped>
  p-carousel div {
    display: flex;
    align-items: center;
    justify-content: center;
    background: #00b0f4;
    height: 150px;
  }
</style>
