// packages/components-react/src/examples/CarouselExampleFocusOnCenterSlide.tsx
import { useState } from 'react';
import { PCarousel } from '@porsche-design-system/components-react';

export const CarouselExampleFocusOnCenterSlidePage = (): JSX.Element => {
  const [activeSlideIndex, setActiveSlideIndex] = useState(0);

  const slideStyles = {
    base: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: '#00b0f4',
      height: '150px',
      transition: 'background 0.3s ease',
    },
    active: {
      background: '#fc4040',
    },
    prevNext: {
      background: '#f7cb47',
    },
  };

  const getSlideStyle = (index: number) => {
    if (index === activeSlideIndex) {
      return { ...slideStyles.base, ...slideStyles.active };
    }
    if (index === activeSlideIndex - 1 || index === activeSlideIndex + 1) {
      return { ...slideStyles.base, ...slideStyles.prevNext };
    }
    return slideStyles.base;
  };

  const onCarouselUpdate = (newIndex: number) => {
    setActiveSlideIndex(newIndex);
  };
  return (
    <PCarousel
      slidesPerPage={3}
      heading="Some Heading"
      onUpdate={(e) => onCarouselUpdate(e.detail.activeIndex)}
      focusOnCenterSlide
      trimSpace={false}
      gradientColor="background-surface"
      // @ts-expect-error: ignore unknown property (TS2353)
      style={{ '--p-gradient-color-width': '25%' }}
    >
      {Array.from({ length: 6 }).map((_, i) => (
        <div style={getSlideStyle(i)} key={i}>
          {`Slide ${i + 1}`}
        </div>
      ))}
    </PCarousel>
  );
};

// packages/components-vue/src/examples/CarouselExampleFocusOnCenterSlide.vue
<script setup lang="ts">
import type { CarouselUpdateEventDetail } from '@porsche-design-system/components-vue';
import { PCarousel } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const activeSlideIndex = ref(0);

const getSlideClass = (index: number) => {
  return {
    'is-active': index === activeSlideIndex.value,
    'is-prev': index === activeSlideIndex.value - 1,
    'is-next': index === activeSlideIndex.value + 1,
  };
};

const onCarouselUpdate = (event: CustomEvent<CarouselUpdateEventDetail>) => {
  activeSlideIndex.value = event.detail.activeIndex;
};
</script>

<template>
  <PCarousel
    gradientColor="background-surface"
    :slidesPerPage="3"
    :focusOnCenterSlide="true"
    :trimSpace="false"
    :intl="{
      slideLabel: 'Slide %s von %s',
      prev: 'Vorheriger Slide',
      next: 'Nächster Slide',
      first: 'Zum ersten Slide',
      last: 'Zum letzten Slide',
    }"
    :heading="'Some heading'"
    @update="onCarouselUpdate"
    :style="{ '--p-gradient-color-width': '25%' }"
  >
    <div v-for="(_, i) in Array.from(Array(6))" :key="i" :class="getSlideClass(i)">Slide {{ i + 1 }}</div>
  </PCarousel>
</template>
<style scoped>
  p-carousel div {
    display: flex;
    align-items: center;
    justify-content: center;
    background: #00b0f4;
    color: #000;
    transition: background 0.3s ease;
    height: 150px;
  }

  .is-active {
    background: #fc4040 !important;
  }

  .is-prev,
  .is-next {
    background: #f7cb47 !important;
  }
</style>
