// packages/components-angular/src/app/examples/checkbox-example-controlled.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { type CheckboxUpdateEventDetail } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-checkbox-example-controlled',
  template: `
    <p-checkbox
      name="some-name"
      label="Some Label"
      value="some-value"
      [checked]="state['some-name']"
      (update)="onUpdate($event)"
    />
    <p-text>some-name: {{ state['some-name'] ? 'checked' : 'not checked' }}</p-text>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CheckboxExampleControlledComponent {
  state: { [key: string]: boolean } = {
    'some-name': true,
  };

  onUpdate({ detail: { name, checked } }: CustomEvent<CheckboxUpdateEventDetail>) {
    this.state[name] = checked;
  }
}

// packages/components-vue/src/examples/CheckboxExampleControlled.vue
<script setup lang="ts">
  import { PCheckbox, PText, type CheckboxUpdateEventDetail } from '@porsche-design-system/components-vue';
  import { ref } from 'vue';

  const state = ref<{ [key: string]: boolean }>({
    'some-name': true,
  });

  const onUpdate = (e: CheckboxUpdateEventDetail) => {
    state.value[e.name] = e.checked;
  };
</script>

<template>
  <PCheckbox
    :name="'some-name'"
    :label="'Some Label'"
    :checked="state['some-name']"
    :value="'some-value'"
    @update="onUpdate"
  />
  <PText>some-name: {{ state['some-name'] ? 'checked' : 'not checked' }}</PText>
</template>
