// packages/components-react/src/examples/CheckboxExampleControlled.tsx
import { type CheckboxChangeEventDetail, PCheckbox, PText } from '@porsche-design-system/components-react';
import { FormEvent, useState } from 'react';

export const CheckboxExampleControlledPage = (): JSX.Element => {
  const [state, setState] = useState({
    'some-name': true,
  });
  const onChange = (event: CustomEvent<CheckboxChangeEventDetail> | FormEvent<{}>) => {
    const { name, checked } = event.target as HTMLInputElement;
    setState((prev) => ({
      ...prev,
      [name]: checked,
    }));
  };
  return (
    <>
      <PCheckbox
        label="Some Label"
        name="some-name"
        checked={state['some-name']}
        value="some-value"
        onChange={(e) => onChange(e)}
      />
      <PText>some-name: {state['some-name'].toString()}</PText>
    </>
  );
};

// packages/components-vue/src/examples/CheckboxExampleControlled.vue
<script setup lang="ts">
import { type CheckboxChangeEventDetail, PCheckbox, PText } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const state = ref<{ [key: string]: boolean }>({
  'some-name': true,
});

const onChange = (e: CustomEvent<CheckboxChangeEventDetail>) => {
  const { name, checked } = e.target as HTMLInputElement;
  state.value[name] = checked;
};
</script>

<template>
  <PCheckbox
    :name="'some-name'"
    :label="'Some Label'"
    :checked="state['some-name']"
    :value="'some-value'"
    @change="onChange"
  />
  <PText>some-name: {{ state['some-name'] }}</PText>
</template>
