// packages/components-angular/src/app/examples/checkbox-example.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-checkbox-example',
  template: `
    <form (submit)="onSubmit($event)">
      <p-checkbox name="some-name" label="Some Label" value="some-value" />
      <button type="submit">Submit</button>
      <button type="reset">Reset</button>
    </form>

    <p-text>Last submitted data: {{ lastSubmittedData }}</p-text>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class CheckboxExampleComponent {
  lastSubmittedData: string = '';

  onSubmit(e: Event): void {
    e.preventDefault();
    const formData = new FormData(e.target as HTMLFormElement);
    this.lastSubmittedData = formData.get('some-name') as string;
  }
}

// packages/components-vue/src/examples/CheckboxExample.vue
<script setup lang="ts">
import { PCheckbox, PText } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const lastSubmittedData = ref('');
const onSubmit = (e: Event) => {
  const formData = new FormData(e.target as HTMLFormElement);
  lastSubmittedData.value = formData.get('some-name') as string;
};
</script>

<template>
  <form @submit.prevent="onSubmit">
    <PCheckbox :name="'some-name'" :label="'Some Label'" :value="'some-value'" />
    <button type="submit">Submit</button>
    <button type="reset">Reset</button>
  </form>

  <PText>Last submitted data: {{ lastSubmittedData }}</PText>
</template>
