// packages/components-react/src/examples/FlyoutExample.tsx
import { useCallback, useState } from 'react';
import { PButton, PText, PFlyout } from '@porsche-design-system/components-react';

export const FlyoutExamplePage = (): JSX.Element => {
  const [isFlyoutOpen, setIsFlyoutOpen] = useState<boolean>(false);
  const onOpen = useCallback(() => {
    setIsFlyoutOpen(true);
  }, []);
  const onDismiss = useCallback(() => {
    setIsFlyoutOpen(false);
  }, []);

  return (
    <>
      <PButton type="button" aria={{ 'aria-haspopup': 'dialog' }} onClick={onOpen}>
        Open Flyout
      </PButton>
      <PFlyout open={isFlyoutOpen} position="end" onDismiss={onDismiss}>
        <PText>Some content that dynamically scales the width of the flyout.</PText>
      </PFlyout>
    </>
  );
};

// packages/components-vue/src/examples/FlyoutExample.vue
<script setup lang="ts">
  import { PFlyout, PButton, PText } from '@porsche-design-system/components-vue';
  import { ref } from 'vue';

  const isFlyoutOpen = ref(false);
  const onOpen = (): void => {
    isFlyoutOpen.value = true;
  };
  const onDismiss = (): void => {
    isFlyoutOpen.value = false;
  };
</script>

<template>
  <PButton type="button" :aria="{ 'aria-haspopup': 'dialog' }" @click="onOpen">Open Flyout</PButton>
  <PFlyout :open="isFlyoutOpen" :position="'end'" @dismiss="onDismiss">
    <PText>Some content that dynamically scales the width of the flyout.</PText>
  </PFlyout>
</template>
