// packages/components-angular/src/app/examples/inline-notification-example-events.component.ts
import { ChangeDetectionStrategy, Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-inline-notification-example-events',
  template: `
    <p-button [type]="'button'" [compact]="true" (click)="onShow()">Show Inline Notification</p-button>
    @if (isActive) {
      <p-inline-notification
        [heading]="'Some heading'"
        [headingTag]="'h3'"
        [description]="'Some description.'"
        (dismiss)="onDismiss()"
      ></p-inline-notification>
    }
    `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class InlineNotificationExampleEventsComponent {
  isActive = false;

  onShow() {
    this.isActive = true;
  }
  onDismiss() {
    this.isActive = false;
  }
}

// packages/components-vue/src/examples/InlineNotificationExampleEvents.vue
<script setup lang="ts">
import { PButton, PInlineNotification } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const isActive = ref(false);
const onShow = (): void => {
  isActive.value = true;
};
const onDismiss = (): void => {
  isActive.value = false;
};
</script>

<template>
  <PButton :type="'button'" :compact="true" @click="onShow">Show Inline Notification</PButton>
  <PInlineNotification
    v-if="isActive"
    :heading="'Some heading'"
    :headingTag="'h4'"
    :description="'Some description.'"
    @dismiss="onDismiss"
  ></PInlineNotification>
</template>
