// packages/components-angular/src/app/examples/inline-notification-example-action-button.component.ts
import { ChangeDetectionStrategy, Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-inline-notification-example-action-button',
  template: `
    <p-inline-notification
      [heading]="'Some heading'"
      [headingTag]="'h4'"
      [description]="'Some description.'"
      [actionLabel]="'Retry'"
      [actionIcon]="'reset'"
      [actionLoading]="isLoading"
      (action)="onAction()"
    ></p-inline-notification>
    <p-button [type]="'button'" [compact]="true" (click)="onAction()">Reset \`actionLoading\`</p-button>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class InlineNotificationExampleActionButtonComponent {
  isLoading = false;

  onAction() {
    this.isLoading = !this.isLoading;
  }
}

// packages/components-vue/src/examples/InlineNotificationExampleActionButton.vue
<script setup lang="ts">
import { PButton, PInlineNotification } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const isLoading = ref(false);
const onAction = (): void => {
  isLoading.value = !isLoading.value;
};
</script>

<template>
  <PInlineNotification
    :heading="'Some heading'"
    :headingTag="'h3'"
    :description="'Some description.'"
    :actionLabel="'Retry'"
    :actionIcon="'reset'"
    :actionLoading="isLoading"
    @action="onAction"
  ></PInlineNotification>
  <PButton :type="'button'" :compact="true" @click="onAction">Reset `actionLoading`</PButton>
</template>
