// packages/components-react/src/examples/InputDateExampleControlled.tsx
import {
  type InputDateInputEventDetail,
  PInputDate,
  type PInputDateProps,
  PText,
} from '@porsche-design-system/components-react';
import { useState } from 'react';

export const InputDateControlledExamplePage = () => {
  const [value, setValue] = useState<PInputDateProps['value']>('');

  const onInput = (e: CustomEvent<InputDateInputEventDetail>) => {
    setValue((e.detail.target as HTMLInputElement).value);
  };

  return (
    <>
      <PInputDate
        name="some-name"
        label="Some Label"
        value={value}
        onInput={(e) => onInput(e as CustomEvent<InputDateInputEventDetail>)}
      />
      <PText>Value: {value}</PText>
    </>
  );
};

// packages/components-vue/src/examples/InputDateExampleControlled.vue
<script setup lang="ts">
import {
  type InputDateInputEventDetail,
  PInputDate,
  type PInputDateProps,
  PText,
} from '@porsche-design-system/components-vue';
import { computed, ref } from 'vue';

const value = ref<PInputDateProps['value']>('');

const onInput = (e: CustomEvent<InputDateInputEventDetail>) => {
  value.value = (e.target as HTMLInputElement).value;
};

const debugText = computed(() => {
  return `Value: ${value.value}`;
});
</script>

<template>
  <PInputDate :name="'some-name'" :label="'Some Label'" :value="value" @input="onInput" />
  <PText>{{ debugText }}</PText>
</template>
