// packages/components-angular/src/app/examples/link-tile-example-hyphens.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule, SelectUpdateEventDetail } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-link-tile-example-hyphens',
  template: `
    <p-select name="hyphens" label="Select hyphens" [value]="selectedValue" (update)="onUpdate($event)">
      <p-select-option value="auto">style="hyphens: auto;"</p-select-option>
      <p-select-option value="manual">style="hyphens: manual;"</p-select-option>
      <p-select-option value="none">style="hyphens: none;"</p-select-option>
    </p-select>

    <p-link-tile
      href="https://porsche.com"
      label="Some label"
      description="An extra&shy;ordinarily Porsche"
      [compact]="true"
      size="inherit"
      [style]="{ maxWidth: '400px', fontSize: '45px', hyphens: selectedValue }"
    >
      <img src="http://localhost:3002/lights.jpg" alt="Some image description" />
    </p-link-tile>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class LinkTileExampleHyphensComponent {
  selectedValue: string = 'auto';

  onUpdate(e: CustomEvent<SelectUpdateEventDetail>) {
    this.selectedValue = e.detail.value;
  }
}

// packages/components-vue/src/examples/LinkTileExampleHyphens.vue
<script setup lang="ts">
import { PLinkTile, PSelect, PSelectOption, type SelectChangeEventDetail } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const selectedValue = ref<string | number | null | undefined>('auto');

const onUpdate = (e: CustomEvent<SelectChangeEventDetail>) => {
  selectedValue.value = e.detail.value;
};
</script>

<template>
  <PSelect label="Select hyphens" name="hyphens" :value="selectedValue" @update="onUpdate">
    <PSelectOption value="auto">style="hyphens: auto;"</PSelectOption>
    <PSelectOption value="manual">style="hyphens: manual;"</PSelectOption>
    <PSelectOption value="none">style="hyphens: none;"</PSelectOption>
  </PSelect>

  <PLinkTile
    href="https://porsche.com"
    label="Some label"
    description="An extra&shy;ordinarily Porsche"
    :compact="true"
    size="inherit"
    :style="{ maxWidth: '400px', fontSize: '45px', hyphens: selectedValue }"
  >
  <img src="http://localhost:3002/lights.jpg" alt="Some image description" />
  </PLinkTile>
</template>
