// packages/components-react/src/examples/MultiSelectExampleDynamic.tsx
import {
  type InputTextInputEventDetail,
  type MultiSelectChangeEventDetail,
  PButton,
  PInputText,
  PMultiSelect,
  PMultiSelectOption,
  type PMultiSelectProps,
} from '@porsche-design-system/components-react';
import { useState } from 'react';

export const MultiSelectExampleDynamicPage = () => {
  const [selectedValues, setSelectedValues] = useState<PMultiSelectProps['value']>([]);
  const [inputValue, setInputValue] = useState('');
  const [optionCount, setOptionCount] = useState(3);

  const onChangeInput = (e: CustomEvent<InputTextInputEventDetail>) => {
    setInputValue((e.detail.target as HTMLInputElement).value);
  };

  const onSetValue = () => {
    setSelectedValues(inputValue.split(','));
  };

  const onResetValue = () => {
    setSelectedValues([]);
    setInputValue('');
  };

  const onChange = (e: CustomEvent<MultiSelectChangeEventDetail>) => {
    setSelectedValues(e.detail.value);
    setInputValue(e.detail.value.join(','));
  };

  const onAddOption = () => {
    setOptionCount((prev) => prev + 1);
  };

  const onRemoveOption = () => {
    if (optionCount > 0) {
      setOptionCount((prev) => prev - 1);
    }
  };

  return (
    <>
      <PInputText
        name="input-value"
        label="Value:"
        placeholder="e.g. 1,2"
        value={inputValue}
        onInput={(e) => onChangeInput(e as CustomEvent<InputTextInputEventDetail>)}
      />
      <PButton type="button" onClick={onSetValue} compact={true}>
        Set Value
      </PButton>
      <PButton type="button" onClick={onResetValue} compact={true}>
        Reset value
      </PButton>

      <PMultiSelect name="options" label="Some Label" value={selectedValues} onChange={onChange}>
        {[...Array(optionCount).keys()].map((idx) => (
          <PMultiSelectOption key={idx} value={`${idx + 1}`}>
            Option {idx + 1}
          </PMultiSelectOption>
        ))}
      </PMultiSelect>

      <PButton type="button" onClick={onAddOption} compact={true}>
        Add option
      </PButton>
      <PButton type="button" onClick={onRemoveOption} compact={true}>
        Remove last option
      </PButton>
    </>
  );
};

// packages/components-vue/src/examples/MultiSelectExampleDynamic.vue
<script setup lang="ts">
import {
  type MultiSelectChangeEventDetail,
  PButton,
  PInputText,
  PMultiSelect,
  PMultiSelectOption,
  type PMultiSelectProps,
} from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const selectedValues = ref<PMultiSelectProps['value']>([]);
const inputValue = ref('');
const optionCount = ref(3);

const onSetValue = () => {
  selectedValues.value = inputValue.value.split(',');
};

const onResetValue = () => {
  selectedValues.value = [];
  inputValue.value = '';
};

const onChange = (e: CustomEvent<MultiSelectChangeEventDetail>) => {
  selectedValues.value = e.detail.value;
  inputValue.value = e.detail.value.join(',');
};

const onAddOption = () => {
  optionCount.value++;
};

const onRemoveOption = () => {
  if (optionCount.value > 0) {
    optionCount.value--;
  }
};
</script>

<template>
  <div class="flex flex-col gap-fluid-sm">
    <PInputText label="Value:" name="input-value" type="text" v-model="inputValue" placeholder="e.g. 1,2" />
    <div class="flex gap-fluid-sm">
      <PButton type="button" @click="onSetValue" :compact="true">Set Value</PButton>
      <PButton type="button" @click="onResetValue" :compact="true">Reset value</PButton>
    </div>

    <PMultiSelect :name="'options'" :label="'Some Label'" :value="selectedValues" @change="onChange">
      <PMultiSelectOption v-for="idx in optionCount" :key="idx" :value="`${idx}`">
        Option {{ idx }}
      </PMultiSelectOption>
    </PMultiSelect>
    <div class="flex gap-fluid-sm">
      <PButton type="button" @click="onAddOption" :compact="true">Add option</PButton>
      <PButton type="button" @click="onRemoveOption" :compact="true">Remove last option</PButton>
    </div>
  </div>
</template>
