// packages/components-angular/src/app/examples/radio-group-example-form.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { PorscheDesignSystemModule, type PRadioGroupProps } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-radio-group-example-form',
  template: `
    <form [formGroup]="form" (ngSubmit)="onSubmit()" class="flex flex-col gap-fluid-sm">
      <p-radio-group formControlName="myRadioGroup" [label]="'Some Label'">
        <p-radio-group-option label="Option A" value="a"></p-radio-group-option>
        <p-radio-group-option label="Option B" value="b"></p-radio-group-option>
        <p-radio-group-option label="Option C" value="c"></p-radio-group-option>
        <p-radio-group-option label="Option D" value="d"></p-radio-group-option>
        <p-radio-group-option label="Option E" value="e"></p-radio-group-option>
        <p-radio-group-option label="Option F" value="f"></p-radio-group-option>
      </p-radio-group>
      <div class="flex gap-fluid-sm">
        <p-button type="submit">Submit</p-button>
        <p-button type="reset">Reset</p-button>
      </div>
      <p-text>Last submitted data: {{ submittedValue }}</p-text>
    </form>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule, FormsModule, ReactiveFormsModule], // <-- PDS module is imported here
})
export class RadioGroupExampleFormComponent {
  form = new FormGroup({
    myRadioGroup: new FormControl<PRadioGroupProps['value']>(null),
  });

  submittedValue: any = undefined;

  onSubmit(): void {
    this.submittedValue = JSON.stringify(this.form.value);
  }
}

// packages/components-vue/src/examples/RadioGroupExampleForm.vue
<template>
  <form @submit.prevent="onSubmit" @reset.prevent="onReset" class="flex flex-col gap-fluid-sm">
    <PRadioGroup v-model:value="form.myRadioGroup" :name="'myRadioGroup'" :label="'Some Label'">
      <PRadioGroupOption label="Option A" :value="'a'"></PRadioGroupOption>
      <PRadioGroupOption label="Option B" :value="'b'"></PRadioGroupOption>
      <PRadioGroupOption label="Option C" :value="'c'"></PRadioGroupOption>
      <PRadioGroupOption label="Option D" :value="'d'"></PRadioGroupOption>
      <PRadioGroupOption label="Option E" :value="'e'"></PRadioGroupOption>
      <PRadioGroupOption label="Option F" :value="'f'"></PRadioGroupOption>
    </PRadioGroup>
    <div class="flex gap-fluid-sm">
      <PButton type="submit">Submit</PButton>
      <PButton type="reset">Reset</PButton>
    </div>
    <PText>Last submitted data: {{ submittedValue }}</PText>
  </form>
</template>

<script setup lang="ts">
import {
  PButton,
  PRadioGroup,
  PRadioGroupOption,
  type PRadioGroupProps,
  PText,
} from '@porsche-design-system/components-vue';
import { reactive, ref } from 'vue';

const form = reactive<{ myRadioGroup: PRadioGroupProps['value'] }>({
  myRadioGroup: null,
});

const submittedValue = ref();

const onSubmit = () => {
  submittedValue.value = JSON.stringify(form);
};

const onReset = () => {
  form.myRadioGroup = null;
};
</script>
