// packages/components-angular/src/app/examples/table-example-basic.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { dataBasic, headBasic } from '@porsche-design-system/shared';

@Component({
  selector: 'table-example-basic',
  template: `
    <p-table caption="Some caption">
      <p-table-head>
        <p-table-head-row>
          <p-table-head-cell *ngFor="let item of head">{{ item }}</p-table-head-cell>
        </p-table-head-row>
      </p-table-head>
      <p-table-body>
        <p-table-row *ngFor="let item of data">
          <p-table-cell>{{ item.model }}</p-table-cell>
          <p-table-cell>{{ item.date }}</p-table-cell>
          <p-table-cell>{{ item.interest }}</p-table-cell>
          <p-table-cell>{{ item.status }}</p-table-cell>
          <p-table-cell>{{ item.leadId }}</p-table-cell>
        </p-table-row>
      </p-table-body>
    </p-table>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TableExampleBasic {
  public head = headBasic;
  public data = dataBasic;
}

// packages/components-vue/src/examples/TableExampleBasic.vue
<script setup lang="ts">
  import {
    PTable,
    PTableBody,
    PTableCell,
    PTableHead,
    PTableHeadCell,
    PTableHeadRow,
    PTableRow,
  } from '@porsche-design-system/components-vue';
  import { dataBasic, headBasic } from '@porsche-design-system/shared/data/table-data-basic';
</script>

<template>
  <PTable :caption="'Some caption'">
    <PTableHead>
      <PTableHeadRow>
        <PTableHeadCell v-for="(item, i) in headBasic" :key="i">{{ item }}</PTableHeadCell>
      </PTableHeadRow>
    </PTableHead>
    <PTableBody>
      <PTableRow v-for="(item, i) in dataBasic" :key="i">
        <PTableCell>{{ item.model }}</PTableCell>
        <PTableCell>{{ item.date }}</PTableCell>
        <PTableCell>{{ item.interest }}</PTableCell>
        <PTableCell>{{ item.status }}</PTableCell>
        <PTableCell>{{ item.leadId }}</PTableCell>
      </PTableRow>
    </PTableBody>
  </PTable>
</template>
