// packages/components-react/src/examples/TextFieldWrapperExampleSearch.tsx
import { PText, PTextFieldWrapper } from '@porsche-design-system/components-react';
import { useCallback, useState } from 'react';
import type { ChangeEvent } from 'react';

export const TextFieldWrapperExampleSearchPage = (): JSX.Element => {
  const [isLoading, setIsLoading] = useState(false);
  const [value, setValue] = useState('');

  const onAction = useCallback(() => {
    setIsLoading(true);

    // simulate async request
    setTimeout(() => {
      setValue('Stuttgart, Baden-Württemberg');
      setIsLoading(false);
    }, 3000);
  }, []);

  const onInput = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => {
      setValue(e.target.value);
      if (isLoading) {
        setIsLoading(false);
      }
    },
    [] // eslint-disable-line react-hooks/exhaustive-deps
  );

  return (
    <>
      <PTextFieldWrapper
        label="Search location"
        hideLabel
        actionIcon="locate"
        actionLoading={isLoading}
        onAction={onAction}
      >
        <input type="search" value={value} placeholder={isLoading ? 'Locating...' : ''} onInput={onInput} />
      </PTextFieldWrapper>
      <PText children={'Value: ' + value} />
    </>
  );
};

// packages/components-vue/src/examples/TextFieldWrapperExampleSearch.vue
<script setup lang="ts">
import { PText, PTextFieldWrapper } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const isLoading = ref(false);
const value = ref('');

const onAction = (): void => {
  isLoading.value = true;

  // simulate async request
  setTimeout(() => {
    value.value = 'Stuttgart, Baden-Württemberg';
    isLoading.value = false;
  }, 3000);
};

const onInput = (e: Event) => {
  value.value = (e.target as HTMLInputElement).value;
  if (isLoading.value) {
    isLoading.value = false;
  }
};
</script>

<template>
  <PTextFieldWrapper
    :label="'Search location'"
    :hideLabel="true"
    :actionIcon="'locate'"
    :actionLoading="isLoading"
    @action="onAction"
  >
    <input type="search" :value="value" :placeholder="isLoading ? 'Locating...' : ''" @input="onInput" />
  </PTextFieldWrapper>
  <PText>Value: {{ value }}</PText>
</template>
