// packages/components-vue/src/examples/ButtonTileExampleHyphens.vue
<script setup lang="ts">
import {
  PButtonTile,
  PSelect,
  PSelectOption,
  type SelectChangeEventDetail,
} from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const selectedValue = ref('auto');

const onChange = (e: CustomEvent<SelectChangeEventDetail>) => {
  selectedValue.value = e.detail.value;
};
</script>

<template>
  <PSelect label="Select hyphens" name="hyphens" :value="selectedValue" @change="onChange">
    <PSelectOption value="auto">style="hyphens: auto;"</PSelectOption>
    <PSelectOption value="manual">style="hyphens: manual;"</PSelectOption>
    <PSelectOption value="none">style="hyphens: none;"</PSelectOption>
  </PSelect>

  <PButtonTile
    label="Some label"
    description="An extra&shy;ordinarily Porsche"
    :compact="true"
    size="inherit"
    :style="{ maxWidth: '400px', fontSize: '45px', hyphens: selectedValue }"
  >
  <img src="http://localhost:3002/lights.jpg" alt="Some image description" />
  </PButtonTile>
</template>

// packages/components-angular/src/app/examples/button-tile-example-hyphens.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import {
  PorscheDesignSystemModule,
  PSelect,
  type SelectChangeEventDetail,
} from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-button-tile-example-hyphens',
  template: `
    <p-select name="hyphens" label="Select hyphens" [value]="selectedValue" (change)="onChange($event)">
      <p-select-option value="auto">style="hyphens: auto;"</p-select-option>
      <p-select-option value="manual">style="hyphens: manual;"</p-select-option>
      <p-select-option value="none">style="hyphens: none;"</p-select-option>
    </p-select>

    <p-button-tile
      label="Some label"
      description="An extra&shy;ordinarily Porsche"
      [compact]="true"
      size="inherit"
      [style]="{ maxWidth: '400px', fontSize: '45px', hyphens: selectedValue }"
    >
      <img src="http://localhost:3002/lights.jpg" alt="Some image description" />
    </p-button-tile>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class ButtonTileExampleHyphensComponent {
  selectedValue: PSelect['value'] = 'auto';

  onChange(e: CustomEvent<SelectChangeEventDetail>) {
    this.selectedValue = e.detail.value;
  }
}
