// packages/components-vue/src/examples/CarouselExampleJumpToSlide.vue
<script setup lang="ts">
import { type CarouselUpdateEventDetail, PButton, PCarousel } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const activeSlideIndex = ref(1);

const onUpdate = (e: CustomEvent<CarouselUpdateEventDetail>): void => {
  activeSlideIndex.value = e.detail.activeIndex;
};
const onButtonClick = (e: MouseEvent): void => {
  activeSlideIndex.value = parseInt((e.target as HTMLButtonElement).innerText) - 1;
};
</script>

<template>
  <PCarousel :heading="'Some Heading'" :activeSlideIndex="activeSlideIndex" @update="onUpdate">
    <div>Slide 1</div>
    <div>Slide 2</div>
    <div>Slide 3</div>
  </PCarousel>

  <PButton
    v-for="(_, i) in Array.from(Array(3))"
    :key="i"
    type="button"
    @click="onButtonClick"
    :disabled="activeSlideIndex === i"
  >
    {{ i + 1 }}
  </PButton>
</template>
<style scoped>
  p-carousel div {
    display: flex;
    align-items: center;
    justify-content: center;
    background: #00b0f4;
    height: 150px;
  }
</style>

// packages/components-angular/src/app/examples/carousel-example-jump-to-slide.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CarouselUpdateEventDetail, PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-carousel-example-jump-to-slide',
  template: `
    <p-carousel [heading]="'Some Heading'" [activeSlideIndex]="activeSlideIndex" (update)="onUpdate($event)">
      <div>Slide 1</div>
      <div>Slide 2</div>
      <div>Slide 3</div>
    </p-carousel>

    @for (_ of [].constructor(3); track _; let i = $index) {
      <p-button
        type="button"
        (click)="onButtonClick($event)"
        [disabled]="activeSlideIndex === i"
        >
        {{ i + 1 }}
      </p-button>
    }
    `,
  styles: `
    @use '@porsche-design-system/components-angular/scss' as *;

    p-carousel div {
      display: flex;
      align-items: center;
      justify-content: center;
      background: #00b0f4;
      height: 150px;
      color: $color-primary;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class CarouselExampleJumpToSlideComponent {
  activeSlideIndex = 1;

  onUpdate(e: CustomEvent<CarouselUpdateEventDetail>) {
    this.activeSlideIndex = e.detail.activeIndex;
  }
  onButtonClick(e: MouseEvent) {
    this.activeSlideIndex = parseInt((e.target as HTMLButtonElement).innerText) - 1;
  }
}
