// packages/components-vue/src/examples/InputWeekExampleForm.vue
<template>
  <form @submit.prevent="onSubmit" @reset.prevent="onReset" class="flex flex-col gap-fluid-sm">
    <PInputWeek v-model:value="form.myInputWeek" :name="'myInputWeek'" :label="'Some Label'" />
    <div class="flex gap-fluid-sm">
      <PButton type="submit">Submit</PButton>
      <PButton type="reset">Reset</PButton>
    </div>
    <PText>Last submitted data: {{ submittedValue }}</PText>
  </form>
</template>

<script setup lang="ts">
  import { PButton, PInputWeek, PText } from '@porsche-design-system/components-vue';
  import { reactive, ref } from 'vue';

  const form = reactive({
    myInputWeek: '',
  });

  const submittedValue = ref();

  const onSubmit = () => {
    submittedValue.value = JSON.stringify(form);
  };

  const onReset = () => {
    form.myInputWeek = '';
  };
</script>

// packages/components-angular/src/app/examples/input-week-example-form.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-input-week-example-form',
  template: `
    <form [formGroup]="form" (ngSubmit)="onSubmit()" class="flex flex-col gap-fluid-sm">
      <p-input-week formControlName="myInputWeek" [label]="'Some Label'" />
      <div class="flex gap-fluid-sm">
        <p-button type="submit">Submit</p-button>
        <p-button type="reset">Reset</p-button>
      </div>
      <p-text>Last submitted data: {{ submittedValue }}</p-text>
    </form>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule, FormsModule, ReactiveFormsModule], // <-- PDS module is imported here
})
export class InputWeekExampleFormComponent {
  form = new FormGroup({
    myInputWeek: new FormControl<string>(''),
  });

  submittedValue: any = undefined;

  onSubmit(): void {
    this.submittedValue = JSON.stringify(this.form.value);
  }
}
