// packages/components-vue/src/examples/LinkTileProductExample.vue
<script setup lang="ts">
import { type LinkTileProductLikeEventDetail, PLinkTileProduct, PTag } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const liked = ref(false);

const handleLike = (e: CustomEvent<LinkTileProductLikeEventDetail>): void => {
  liked.value = !e.detail.liked;
};
</script>

<template>
  <PLinkTileProduct
    :heading="'Some product name'"
    :price="'1.911,00 €'"
    :description="'Some description'"
    :href="'https://porsche.com'"
    :liked="liked"
    @like="handleLike"
  >
    <slot name="header">
      <PTag :color="'background-base'">New</PTag>
    </slot>
    <img src="http://localhost:3002/placeholder_800x900.svg" width="800" height="900" alt="Some alt text" />
  </PLinkTileProduct>
</template>

// packages/components-angular/src/app/examples/link-tile-product-example.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import type { LinkTileProductLikeEventDetail } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-link-tile-product-example',
  template: `
    <p-link-tile-product
      [heading]="'Some product name'"
      [price]="'1.911,00 €'"
      [description]="'Some description'"
      [href]="'https://porsche.com'"
      [liked]="liked"
      (like)="handleLike($event)"
    >
      <p-tag slot="header" [color]="'background-base'">New</p-tag>
      <img src="http://localhost:3002/placeholder_800x900.svg" width="800" height="900" alt="Some alt text" />
    </p-link-tile-product>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LinkTileProductExampleComponent {
  liked = false;
  handleLike(e: CustomEvent<LinkTileProductLikeEventDetail>) {
    this.liked = !e.detail.liked;
  }
}
