// packages/components-vue/src/examples/MultiSelectExample.vue
<script setup lang="ts">
import { PMultiSelect, PMultiSelectOption, PText } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const lastSubmittedData = ref('none');
const onSubmit = (e: Event) => {
  const formData = new FormData(e.target as HTMLFormElement);
  lastSubmittedData.value = Array.from(formData.values()).join(', ') || 'none';
};
</script>

<template>
  <form @submit.prevent="onSubmit">
    <PMultiSelect :name="'options'" :label="'Some Label'" :value="['a']">
      <PMultiSelectOption :value="'a'">Option A</PMultiSelectOption>
      <PMultiSelectOption :value="'b'">Option B</PMultiSelectOption>
      <PMultiSelectOption :value="'c'">Option C</PMultiSelectOption>
      <PMultiSelectOption :value="'d'">Option D</PMultiSelectOption>
      <PMultiSelectOption :value="'e'">Option E</PMultiSelectOption>
      <PMultiSelectOption :value="'f'">Option F</PMultiSelectOption>
    </PMultiSelect>
    <button type="submit">Submit</button>
    <button type="reset">Reset</button>
  </form>

  <PText>Last submitted data: {{ lastSubmittedData }}</PText>
</template>

// packages/components-angular/src/app/examples/multi-select-example.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-multi-select-example',
  template: `
    <form (submit)="onSubmit($event)">
      <p-multi-select name="options" label="Some Label" [value]="['a']">
        <p-multi-select-option value="a">Option A</p-multi-select-option>
        <p-multi-select-option value="b">Option B</p-multi-select-option>
        <p-multi-select-option value="c">Option C</p-multi-select-option>
        <p-multi-select-option value="d">Option D</p-multi-select-option>
        <p-multi-select-option value="e">Option E</p-multi-select-option>
        <p-multi-select-option value="f">Option F</p-multi-select-option>
      </p-multi-select>
      <p-button type="submit">Submit</p-button>
      <p-button type="reset">Reset</p-button>
    </form>

    <p-text>Last submitted data: {{ lastSubmittedData }}</p-text>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class MultiSelectExampleComponent {
  lastSubmittedData: string = 'none';

  onSubmit(e: Event): void {
    e.preventDefault();
    const formData = new FormData(e.target as HTMLFormElement);
    this.lastSubmittedData = Array.from(formData.getAll('options'))?.join(', ') || 'none';
  }
}
