// packages/components-vue/src/examples/PinCodeExampleControlled.vue
<script setup lang="ts">
  import type { PinCodeUpdateEvent } from '@porsche-design-system/components-vue';
  import { PPinCode, PText } from '@porsche-design-system/components-vue';
  import { ref } from 'vue';

  const length = ref(4);
  const currentValue = ref<string[]>([]);
  const isComplete = ref(currentValue.value?.join().length === length.value);

  const onUpdate = (e: PinCodeUpdateEvent): void => {
    currentValue.value = e.value;
    isComplete.value = e.value.join('').length === length.value;
  };
</script>

<template>
  <PPinCode :label="'Some Label'" :length="length" :value="currentValue" @update="onUpdate"></PPinCode>
  <PText>Current value: {{ currentValue }}</PText>
  <PText>Completely filled: {{ isComplete }}</PText>
</template>

// packages/components-angular/src/app/examples/pin-code-example-controlled.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import type { PinCodeUpdateEvent } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-pin-code-example-controlled',
  template: `
    <p-pin-code
      [label]="'Some Label'"
      [length]="length"
      [value]="currentValue"
      (update)="onUpdate($event)"
    ></p-pin-code>
    <p-text>Current value: [{{ currentValue }}]</p-text>
    <p-text>Completely filled: {{ isComplete }}</p-text>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PinCodeExampleControlledComponent {
  length = 4;
  currentValue = ['', '', '', ''];
  isComplete = false;

  onUpdate(e: CustomEvent<PinCodeUpdateEvent>) {
    this.currentValue = e.detail.value;
    this.isComplete = e.detail.value.join('').length === this.length;
  }
}
