// packages/components-vue/src/examples/PinCodeExample.vue
<script setup lang="ts">
  import { PButton, PPinCode, PText } from '@porsche-design-system/components-vue';
  import { ref } from 'vue';

  const lastSubmittedValue = ref('none');

  const onSubmit = (e: Event): void => {
    const formData = new FormData(e.target as HTMLFormElement);
    lastSubmittedValue.value = Array.from(formData.values()).join() || 'none';
  };
</script>

<template>
  <form @submit.prevent="onSubmit">
    <PPinCode :label="'Some Label'" name="pin-code"></PPinCode>
    <PButton type="submit">Submit</PButton>
    <PButton type="submit">Reset</PButton>
  </form>
  <PText>Last submitted data: {{ lastSubmittedValue }}</PText>
</template>

// packages/components-angular/src/app/examples/pin-code-example.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-pin-code-example',
  template: `
    <form (submit)="onSubmit($event)">
      <p-pin-code [label]="'Some Label'" [name]="'pin-code'"></p-pin-code>
      <p-button type="submit">Submit</p-button>
      <button type="reset">Reset</button>
    </form>
    <p-text>Last submitted data: {{ lastSubmittedValue }}</p-text>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class PinCodeExampleComponent {
  lastSubmittedValue = 'none';

  onSubmit(e: Event) {
    e.preventDefault();
    const formData = new FormData(e.target as HTMLFormElement);
    this.lastSubmittedValue = Array.from(formData.values()).join() || 'none';
  }
}
