// packages/components-vue/src/examples/PopoverExampleControlled.vue
<script setup lang="ts">
import { PButtonPure, PPopover } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const isPopoverOpen = ref(false);
const onOpen = (): void => {
  isPopoverOpen.value = true;
};
const onDismiss = (): void => {
  isPopoverOpen.value = false;
};
</script>

<template>
  <PPopover :open="isPopoverOpen" @dismiss="onDismiss">
    <PButtonPure slot="button" :hideLabel="true" :aria="{ 'aria-expanded': 'false' }" @click="onOpen" icon="information">
    More information
    </PButtonPure>
    Some additional content with some <a href="#">link</a>.
  </PPopover>
</template>

// packages/components-angular/src/app/examples/popover-example-controlled.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-popover-example-controlled',
  template: `
    <p-popover [open]="isPopoverOpen" (dismiss)="onDismiss()">
      <p-button-pure slot="button" [hideLabel]="true" [aria]="{ 'aria-expanded': 'false' }" (click)="onOpen()" icon="information">More information</p-button-pure>
      Some additional content with some <a href="#">link</a>.
    </p-popover>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class FlyoutExampleComponent {
  isPopoverOpen = false;

  onOpen() {
    this.isPopoverOpen = true;
  }
  onDismiss() {
    this.isPopoverOpen = false;
  }
}
