// packages/components-vue/src/examples/SelectExampleControlled.vue
<script setup lang="ts">
import { PSelect, PSelectOption, PText, type SelectChangeEventDetail } from '@porsche-design-system/components-vue';
import { computed, ref } from 'vue';

const selectedValue = ref<string | number | null | undefined>('a');

const onChange = (e: CustomEvent<SelectChangeEventDetail>) => {
  selectedValue.value = e.detail.value;
};

const debugText = computed(() => {
  return `Selected values: ${selectedValue.value}`;
});
</script>

<template>
  <PSelect :name="'options'" :label="'Some Label'" :value="selectedValue" @change="onChange">
    <PSelectOption :value="'a'">Option A</PSelectOption>
    <PSelectOption :value="'b'">Option B</PSelectOption>
    <PSelectOption :value="'c'">Option C</PSelectOption>
    <PSelectOption :value="'d'">Option D</PSelectOption>
    <PSelectOption :value="'e'">Option E</PSelectOption>
    <PSelectOption :value="'f'">Option F</PSelectOption>
  </PSelect>

  <PText>{{ debugText }}</PText>
</template>

// packages/components-angular/src/app/examples/select-example-controlled.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule, PSelect, SelectChangeEventDetail } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-select-example-controlled',
  template: `
    <p-select name="options" label="Some Label" [value]="selectedValue" (change)="onChange($event)">
      <p-select-option value="a">Option A</p-select-option>
      <p-select-option value="b">Option B</p-select-option>
      <p-select-option value="c">Option C</p-select-option>
      <p-select-option value="d">Option D</p-select-option>
      <p-select-option value="e">Option E</p-select-option>
      <p-select-option value="f">Option F</p-select-option>
    </p-select>

    <p-text>{{ debugText }}</p-text>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class SelectExampleControlledComponent {
  selectedValue: PSelect['value'] = 'a';
  get debugText(): string {
    return `Selected value: ${this.selectedValue}`;
  }

  onChange(e: CustomEvent<SelectChangeEventDetail>) {
    this.selectedValue = e.detail.value;
  }
}
