// packages/components-vue/src/examples/TextFieldWrapperExampleSearch.vue
<script setup lang="ts">
import { PText, PTextFieldWrapper } from '@porsche-design-system/components-vue';
import { ref } from 'vue';

const isLoading = ref(false);
const value = ref('');

const onAction = (): void => {
  isLoading.value = true;

  // simulate async request
  setTimeout(() => {
    value.value = 'Stuttgart, Baden-Württemberg';
    isLoading.value = false;
  }, 3000);
};

const onInput = (e: Event) => {
  value.value = (e.target as HTMLInputElement).value;
  if (isLoading.value) {
    isLoading.value = false;
  }
};
</script>

<template>
  <PTextFieldWrapper
    :label="'Search location'"
    :hideLabel="true"
    :actionIcon="'locate'"
    :actionLoading="isLoading"
    @action="onAction"
  >
    <input type="search" :value="value" :placeholder="isLoading ? 'Locating...' : ''" @input="onInput" />
  </PTextFieldWrapper>
  <PText>Value: {{ value }}</PText>
</template>

// packages/components-angular/src/app/examples/text-field-wrapper-example-search.component.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'text-field-wrapper-example-search',
  template: `
    <p-text-field-wrapper
      label="Search location"
      [hideLabel]="true"
      actionIcon="locate"
      [actionLoading]="isLoading"
      (action)="onAction()"
    >
      <input type="search" [value]="value" [placeholder]="isLoading ? 'Locating...' : ''" (input)="onInput($event)" />
    </p-text-field-wrapper>
    <p-text>Value: {{ value }}</p-text>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class TextFieldWrapperExampleSearchComponent {
  public value = '';
  public isLoading = false;

  constructor(private cdr: ChangeDetectorRef) {}

  public onAction() {
    this.isLoading = true;

    // simulate async request
    setTimeout(() => {
      this.value = 'Stuttgart, Baden-Württemberg';
      this.isLoading = false;
      this.cdr.markForCheck();
    }, 3000);
  }

  public onInput(e: Event) {
    this.value = (e.target as HTMLInputElement).value;
    if (this.isLoading) {
      this.isLoading = false;
    }
  }
}
