// packages/components-vue/projects/vue-wrapper/skill/references/components/p-display/examples/Semantics.vue
<script setup lang="ts">
  import { PDisplay } from '@porsche-design-system/components-vue';
</script>

<template>
  <PDisplay tag="h3">
    The quick brown fox jumps over the lazy dog
  </PDisplay>

  <PDisplay>
    <h3>
      The quick brown fox jumps over the lazy dog
    </h3>
  </PDisplay>
</template>

// packages/components-react/projects/react-wrapper/skill/references/components/p-display/examples/Semantics.tsx
import React from 'react';
import { PDisplay } from '@porsche-design-system/components-react';

export const Example = () => {
  return (
    <>
      <PDisplay tag="h3">
        The quick brown fox jumps over the lazy dog
      </PDisplay>

      <PDisplay>
        <h3>
          The quick brown fox jumps over the lazy dog
        </h3>
      </PDisplay>
    </>
  )
}
