// packages/components-angular/projects/angular-wrapper/skill/references/components/p-inline-notification/examples/EventHandling.ts
import { ChangeDetectionStrategy, Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
    <p-button [type]="'button'" [compact]="true" (click)="onShow()">Show Inline Notification</p-button>
    @if (isActive) {
      <p-inline-notification
        [heading]="'Some heading'"
        [headingTag]="'h3'"
        [description]="'Some description.'"
        (dismiss)="onDismiss()"
      ></p-inline-notification>
    }
    `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ExampleComponent {
  isActive = false;

  onShow() {
    this.isActive = true;
  }
  onDismiss() {
    this.isActive = false;
  }
}

// packages/components-react/projects/react-wrapper/skill/references/components/p-inline-notification/examples/EventHandling.tsx
import React from 'react';
import { PButton, PInlineNotification } from '@porsche-design-system/components-react';
import { useCallback, useState } from 'react';

export const Example = () => {
  const [isActive, setIsActive] = useState<boolean>(false);
  const onShow = useCallback(() => setIsActive(true), []);
  const onDismiss = useCallback(() => setIsActive(false), []);

  return (
    <>
      <PButton type="button" compact={true} onClick={onShow}>
        Show Inline Notification
      </PButton>
      {isActive && (
        <PInlineNotification
          heading="Some heading"
          headingTag="h3"
          description="Some description."
          onDismiss={onDismiss}
        />
      )}
    </>
  );
};
