// packages/components-angular/projects/angular-wrapper/skill/references/components/p-fieldset/examples/SlottedMessage.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
      <p-fieldset label="Some legend label" state="error">
        <p-input-text label="Some label" name="some-name"></p-input-text>
        <span slot="message">
          Some error message
        </span>
      </p-fieldset>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule], // <-- PDS module is imported here
})
export class ExampleComponent {}

// packages/components-vue/projects/vue-wrapper/skill/references/components/p-fieldset/examples/SlottedMessage.vue
<script setup lang="ts">
  import { PFieldset, PInputText } from '@porsche-design-system/components-vue';
</script>

<template>
  <PFieldset label="Some legend label" state="error">
    <PInputText label="Some label" name="some-name"></PInputText>
    <span slot="message">
      Some error message
    </span>
  </PFieldset>
</template>
