// packages/components-angular/projects/angular-wrapper/skill/references/components/p-checkbox/examples/Indeterminate.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
      <div class="flex flex-col gap-static-sm">
        <p-checkbox label="Some label" [indeterminate]="true"></p-checkbox>
        <p-checkbox label="Some label" [indeterminate]="true" [checked]="true"></p-checkbox>
      </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule], // <-- PDS module is imported here
})
export class ExampleComponent {}

// packages/components-vue/projects/vue-wrapper/skill/references/components/p-checkbox/examples/Indeterminate.vue
<script setup lang="ts">
  import { PCheckbox } from '@porsche-design-system/components-vue';
</script>

<template>
  <div class="flex flex-col gap-static-sm">
    <PCheckbox label="Some label" :indeterminate="true"></PCheckbox>
    <PCheckbox label="Some label" :indeterminate="true" :checked="true"></PCheckbox>
  </div>
</template>
