// packages/ui-kit-angular-test/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <p-headline variant="headline-2" tag="h2">Basic</p-headline>
    <hr>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">&lt;p-headline&gt;</p-headline>
      </p-grid-child>
      <p-grid-child size="10">
        <div class="playground light spacing-block">
          <p-headline variant="large-title" tag="h1">The quick brown fox jumps over the lazy dog</p-headline>
          <p-headline variant="headline-1" tag="h1">The quick brown fox jumps over the lazy dog</p-headline>
          <p-headline variant="headline-2" tag="h2">The quick brown fox jumps over the lazy dog</p-headline>
          <p-headline variant="headline-3" tag="h3">The quick brown fox jumps over the lazy dog</p-headline>
          <p-headline variant="headline-4" tag="h4">The quick brown fox jumps over the lazy dog</p-headline>
          <p-headline variant="headline-5" tag="h5">The quick brown fox jumps over the lazy dog</p-headline>
          <p-headline variant="headline-6" tag="h6">The quick brown fox jumps over the lazy dog</p-headline>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">&lt;p-text&gt;</p-headline>
      </p-grid-child>
      <p-grid-child size="10">
        <div class="playground light spacing-block">
          <p-text variant="copy">The quick brown fox jumps over the lazy dog</p-text>
          <p-text variant="small">The quick brown fox jumps over the lazy dog</p-text>
        </div>
        <div class="playground light spacing-block">
          <p-text color="porsche-black">Porsche Black</p-text>
          <p-text color="porsche-light" style="background: black; display: block;">Porsche Light</p-text>
          <p-text color="inherit" style="color: deeppink;">Inherited custom color</p-text>
        </div>
        <div class="playground light spacing-block">
          <p-text ellipsis="true">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
            invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
            dolores et ea rebum.
          </p-text>
        </div>
        <div class="playground light spacing-block">
          <p-text>Lorem ipsum dolor sit amet <a href="#">linked text</a> et, <b>bold text</b> &amp; <strong>strong
            text</strong></p-text>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-headline variant="headline-2">Action</p-headline>
    <hr>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">&lt;p-button-regular&gt;</p-headline>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground light spacing-inline">
          <p-button-regular variant="highlight">Click Here!</p-button-regular>
          <p-button-regular variant="highlight" disabled="true">Disabled</p-button-regular>
          <p-button-regular variant="highlight" loading="true">Loading...</p-button-regular>
        </div>
        <div class="playground light spacing-inline">
          <p-button-regular>Click Here!</p-button-regular>
          <p-button-regular disabled="true">Disabled</p-button-regular>
          <p-button-regular loading="true">Loading...</p-button-regular>
        </div>
        <div class="playground light spacing-inline">
          <p-button-regular variant="ghost">Click Here!</p-button-regular>
          <p-button-regular variant="ghost" disabled="true">Disabled</p-button-regular>
          <p-button-regular variant="ghost" loading="true">Loading...</p-button-regular>
        </div>
        <div class="playground light spacing-inline">
          <p-button-regular icon="phone">Click Here!</p-button-regular>
        </div>
        <div class="playground light spacing-inline">
          <p-button-regular small="true">Click Here!</p-button-regular>
          <p-button-regular small="true" variant="ghost">Click Here!</p-button-regular>
          <p-button-regular small="true" variant="highlight">Click Here!</p-button-regular>
        </div>
        <hr>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground dark spacing-inline">
          <p-button-regular theme="dark" variant="highlight">Click Here!</p-button-regular>
          <p-button-regular theme="dark" variant="highlight" disabled="true">Disabled</p-button-regular>
          <p-button-regular theme="dark" variant="highlight" loading="true">Loading...</p-button-regular>
        </div>
        <div class="playground dark spacing-inline">
          <p-button-regular theme="dark">Click Here!</p-button-regular>
          <p-button-regular theme="dark" disabled="true">Disabled</p-button-regular>
          <p-button-regular theme="dark" loading="true">Loading...</p-button-regular>
        </div>
        <div class="playground dark spacing-inline">
          <p-button-regular theme="dark" variant="ghost">Click Here!</p-button-regular>
          <p-button-regular theme="dark" variant="ghost" disabled="true">Disabled</p-button-regular>
          <p-button-regular theme="dark" variant="ghost" loading="true">Loading...</p-button-regular>
        </div>
        <div class="playground dark spacing-inline">
          <p-button-regular theme="dark" icon="phone">Click Here!</p-button-regular>
        </div>
        <div class="playground dark spacing-inline">
          <p-button-regular theme="dark" small="true">Click Here!</p-button-regular>
          <p-button-regular theme="dark" small="true" variant="ghost">Click Here!</p-button-regular>
          <p-button-regular theme="dark" small="true" variant="highlight">Click Here!</p-button-regular>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">&lt;p-button-icon&gt;</p-headline>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground light spacing-inline">
          <p-button-icon></p-button-icon>
          <p-button-icon disabled="true"></p-button-icon>
          <p-button-icon loading="true"></p-button-icon>
        </div>
        <div class="playground light spacing-inline">
          <p-button-icon variant="ghost"></p-button-icon>
          <p-button-icon variant="ghost" disabled="true"></p-button-icon>
          <p-button-icon variant="ghost" loading="true"></p-button-icon>
        </div>
        <div class="playground light spacing-inline">
          <p-button-icon variant="transparent"></p-button-icon>
          <p-button-icon variant="transparent" disabled="true"></p-button-icon>
          <p-button-icon variant="transparent" loading="true"></p-button-icon>
        </div>
        <div class="playground light spacing-inline">
          <p-button-icon icon="phone"></p-button-icon>
        </div>
        <hr>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground dark spacing-inline">
          <p-button-icon theme="dark"></p-button-icon>
          <p-button-icon theme="dark" disabled="true"></p-button-icon>
          <p-button-icon theme="dark" loading="true"></p-button-icon>
        </div>
        <div class="playground dark spacing-inline">
          <p-button-icon theme="dark" variant="ghost"></p-button-icon>
          <p-button-icon theme="dark" variant="ghost" disabled="true"></p-button-icon>
          <p-button-icon theme="dark" variant="ghost" loading="true"></p-button-icon>
        </div>
        <div class="playground dark spacing-inline">
          <p-button-icon theme="dark" variant="transparent"></p-button-icon>
          <p-button-icon theme="dark" variant="transparent" disabled="true"></p-button-icon>
          <p-button-icon theme="dark" variant="transparent" loading="true"></p-button-icon>
        </div>
        <div class="playground dark spacing-inline">
          <p-button-icon theme="dark" icon="phone"></p-button-icon>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">&lt;p-text-link&gt;</p-headline>
      </p-grid-child>
      <p-grid-child size="10">
        <div class="playground light spacing-inline">
          <p-text-link href="https://ui.porsche.com">Some link with default icon</p-text-link>
        </div>
        <div class="playground light spacing-inline">
          <p-text-link href="https://ui.porsche.com" color="porsche-black">Porsche Black</p-text-link>
          <p-text-link href="https://ui.porsche.com" color="porsche-light" style="background: black;">Porsche Light
          </p-text-link>
          <p-text-link href="https://ui.porsche.com" color="inherit" style="color: deeppink;">Inherited custom color
          </p-text-link>
        </div>
        <div class="playground light spacing-inline">
          <p-text-link href="https://ui.porsche.com" icon="delete">Some link with a custom icon</p-text-link>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-headline variant="headline-2">Content</p-headline>
    <hr>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">
          &lt;p-text-list&gt;<br>
          &lt;p-text-list-item&gt;
        </p-headline>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground light spacing-block">
          <p-text-list>
            <p-text-list-item>First level - Lorem ipsum dolor sit amet</p-text-list-item>
            <p-text-list-item>
              Lorem ipsum dolor sit amet <a href="#">linked text</a> et, <b>bold text</b> &amp; <strong>strong
              text</strong>
              <p-text-list>
                <p-text-list-item>Second level - Lorem ipsum dolor sit amet</p-text-list-item>
                <p-text-list-item>Lorem ipsum</p-text-list-item>
              </p-text-list>
            </p-text-list-item>
            <p-text-list-item>First level - Lorem ipsum dolor sit amet</p-text-list-item>
          </p-text-list>
        </div>
        <div class="playground light spacing-block">
          <p-text-list listType="ordered">
            <p-text-list-item>First level - Lorem ipsum dolor sit amet</p-text-list-item>
            <p-text-list-item>
              Lorem ipsum dolor sit amet <a href="#">linked text</a> et, <b>bold text</b> &amp; <strong>strong
              text</strong>
              <p-text-list listType="ordered">
                <p-text-list-item>Second level - Lorem ipsum dolor sit amet</p-text-list-item>
                <p-text-list-item>Lorem ipsum</p-text-list-item>
              </p-text-list>
            </p-text-list-item>
            <p-text-list-item>First level - Lorem ipsum dolor sit amet</p-text-list-item>
          </p-text-list>
        </div>
        <hr>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground dark spacing-block">
          <p-text-list color="porsche-light">
            <p-text-list-item>First level - Lorem ipsum dolor sit amet</p-text-list-item>
            <p-text-list-item>
              Lorem ipsum dolor sit amet <a href="#">linked text</a> et, <b>bold text</b> &amp; <strong>strong
              text</strong>
              <p-text-list>
                <p-text-list-item>Second level - Lorem ipsum dolor sit amet</p-text-list-item>
                <p-text-list-item>Lorem ipsum</p-text-list-item>
              </p-text-list>
            </p-text-list-item>
            <p-text-list-item>First level - Lorem ipsum dolor sit amet</p-text-list-item>
          </p-text-list>
        </div>
        <div class="playground dark spacing-block">
          <p-text-list listType="ordered" color="inherit" style="color: deeppink;">
            <p-text-list-item>First level - Lorem ipsum dolor sit amet</p-text-list-item>
            <p-text-list-item>
              Lorem ipsum dolor sit amet <a href="#">linked text</a> et, <b>bold text</b> &amp; <strong>strong
              text</strong>
              <p-text-list>
                <p-text-list-item>Second level - Lorem ipsum dolor sit amet</p-text-list-item>
                <p-text-list-item>Lorem ipsum</p-text-list-item>
              </p-text-list>
            </p-text-list-item>
            <p-text-list-item>First level - Lorem ipsum dolor sit amet</p-text-list-item>
          </p-text-list>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-headline variant="headline-2">Feedback</p-headline>
    <hr>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">&lt;p-spinner&gt;</p-headline>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground light spacing-inline">
          <p-spinner size="x-small" allyLabel="Loading"></p-spinner>
          <p-spinner size="small" allyLabel="Loading"></p-spinner>
          <p-spinner size="medium" allyLabel="Loading"></p-spinner>
          <p-spinner size="large" allyLabel="Loading"></p-spinner>
        </div>
        <hr>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground dark spacing-inline">
          <p-spinner theme="dark" size="x-small" allyLabel="Loading"></p-spinner>
          <p-spinner theme="dark" size="small" allyLabel="Loading"></p-spinner>
          <p-spinner theme="dark" size="medium" allyLabel="Loading"></p-spinner>
          <p-spinner theme="dark" size="large" allyLabel="Loading"></p-spinner>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-headline variant="headline-2">Icon</p-headline>
    <hr>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">&lt;p-icon&gt;</p-headline>
      </p-grid-child>
      <p-grid-child size="10">
        <div class="playground light spacing-inline">
          <p-icon source="car-next"></p-icon>
          <p-icon source="car-next" size="medium"></p-icon>
          <p-icon source="car-next" size="large"></p-icon>
          <p-icon source="car-next" size="large" color="neutral-grey-2"></p-icon>
          <p-icon source="car-next" size="large" color="inherit" style="color: deeppink;"></p-icon>
          <p-icon source="kaixin" size="large"></p-icon>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-headline variant="headline-2">Layout</p-headline>
    <hr>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">
          &lt;p-grid&gt;<br>
          &lt;p-grid-child&gt;
        </p-headline>
      </p-grid-child>
      <p-grid-child size="10">
        <div class="playground light spacing-block">
          <p-grid>
            <p-grid-child size="12"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="1"></p-grid-child>
            <p-grid-child size="11"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="2"></p-grid-child>
            <p-grid-child size="10"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="3"></p-grid-child>
            <p-grid-child size="9"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="4"></p-grid-child>
            <p-grid-child size="8"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="5"></p-grid-child>
            <p-grid-child size="7"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="6"></p-grid-child>
            <p-grid-child size="6"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="7"></p-grid-child>
            <p-grid-child size="5"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="8"></p-grid-child>
            <p-grid-child size="4"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="9"></p-grid-child>
            <p-grid-child size="3"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="10"></p-grid-child>
            <p-grid-child size="2"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child size="11"></p-grid-child>
            <p-grid-child size="1"></p-grid-child>
          </p-grid>
        </div>
        <div class="playground light spacing-block">
          <p-grid>
            <p-grid-child offset="1" size="11"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="2" size="10"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="3" size="9"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="4" size="8"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="5" size="7"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="6" size="6"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="7" size="5"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="8" size="4"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="9" size="3"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="10" size="2"></p-grid-child>
          </p-grid>
          <p-grid>
            <p-grid-child offset="11" size="1"></p-grid-child>
          </p-grid>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">
          &lt;p-flex&gt;<br>
          &lt;p-flex-item&gt;
        </p-headline>
      </p-grid-child>
      <p-grid-child size="10">
        <div class="playground light spacing-block">
          <p-flex>
            <p-flex-item width="one-quarter"></p-flex-item>
            <p-flex-item width="one-quarter"></p-flex-item>
            <p-flex-item width="one-quarter"></p-flex-item>
            <p-flex-item width="one-quarter"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item width="one-third"></p-flex-item>
            <p-flex-item width="one-third"></p-flex-item>
            <p-flex-item width="one-third"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item width="half"></p-flex-item>
            <p-flex-item width="half"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item width="two-thirds"></p-flex-item>
            <p-flex-item width="one-third"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item width="three-quarters"></p-flex-item>
            <p-flex-item width="one-quarter"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item width="full"></p-flex-item>
          </p-flex>
        </div>
        <div class="playground light spacing-block">
          <p-flex>
            <p-flex-item offset="one-quarter" width="three-quarters"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item offset="one-third" width="two-thirds"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item offset="half" width="half"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item offset="two-thirds" width="one-third"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item offset="three-quarters" width="one-quarter"></p-flex-item>
          </p-flex>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">Spacing</p-headline>
      </p-grid-child>
      <p-grid-child size="10">
        <div class="playground light spacing-inline">
          <div class="p-spacing-pt-4 p-spacing-pr-4"></div>
          <div class="p-spacing-pt-8 p-spacing-pr-8"></div>
          <div class="p-spacing-pt-16 p-spacing-pr-16"></div>
          <div class="p-spacing-pt-24 p-spacing-pr-24"></div>
          <div class="p-spacing-pt-32 p-spacing-pr-32"></div>
          <div class="p-spacing-pt-40 p-spacing-pr-40"></div>
          <div class="p-spacing-pt-48 p-spacing-pr-48"></div>
          <div class="p-spacing-pt-56 p-spacing-pr-56"></div>
          <div class="p-spacing-pt-64 p-spacing-pr-64"></div>
          <div class="p-spacing-pt-72 p-spacing-pr-72"></div>
          <div class="p-spacing-pt-80 p-spacing-pr-80"></div>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
    <p-headline variant="headline-2">Navigation</p-headline>
    <hr>
    <p-grid>
      <p-grid-child size="2">
        <p-headline variant="headline-4" tag="h4">&lt;p-pagination&gt;</p-headline>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground light spacing-block">
          <p-pagination totalItemsCount="500" itemsPerPage="25" activePage="1"></p-pagination>
        </div>
        <hr>
      </p-grid-child>
      <p-grid-child size="5">
        <div class="playground dark spacing-block">
          <p-pagination theme="dark" totalItemsCount="500" itemsPerPage="25" activePage="1"></p-pagination>
        </div>
        <hr>
      </p-grid-child>
    </p-grid>
  `,
  styles: []
})
export class AppComponent {
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<h2>Here are some links to help you start: </h2>
<ul>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://angular.io/tutorial">Tour of Heroes</a></h2>
  </li>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://angular.io/cli">CLI Documentation</a></h2>
  </li>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://blog.angular.io/">Angular blog</a></h2>
  </li>
  <p-button-regular (pClick)="onButtonClick()">Hello World</p-button-regular>
</ul>

// packages/ui-kit-react/src/App.tsx
import React from 'react';
import {
  PGrid,
  PGridChild,
  PFlex,
  PSpacing,
  PFlexItem,
  PMarque,
  PHeadline,
  PText,
  PButtonRegular,
  PButtonIcon,
  PTextLink,
  PTextList,
  PTextListItem,
  PSpinner,
  PIcon,
  PPagination
} from '@porsche-ui/ui-kit-react';

const App: React.FC = () => {
  return (
    <div id="app">
      <PHeadline variant="headline-2" tag="h2">Basic</PHeadline>
      <hr/>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-marque&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="10">
          <div className="playground light spacing-block">
            <PMarque />
            <PMarque trademark={false} />
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-headline&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="10">
          <div className="playground light spacing-block">
            <PHeadline variant="large-title" tag="h1">The quick brown fox jumps over the lazy dog</PHeadline>
            <PHeadline variant="headline-1" tag="h1">The quick brown fox jumps over the lazy dog</PHeadline>
            <PHeadline variant="headline-2" tag="h2">The quick brown fox jumps over the lazy dog</PHeadline>
            <PHeadline variant="headline-3" tag="h3">The quick brown fox jumps over the lazy dog</PHeadline>
            <PHeadline variant="headline-4" tag="h4">The quick brown fox jumps over the lazy dog</PHeadline>
            <PHeadline variant="headline-5" tag="h5">The quick brown fox jumps over the lazy dog</PHeadline>
            <PHeadline variant="headline-6" tag="h6">The quick brown fox jumps over the lazy dog</PHeadline>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-text&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="10">
          <div className="playground light spacing-block">
            <PText variant="copy">The quick brown fox jumps over the lazy dog</PText>
            <PText variant="small">The quick brown fox jumps over the lazy dog</PText>
          </div>
          <div className="playground light spacing-block">
            <PText color="porsche-black">Porsche Black</PText>
            <PText color="porsche-light" style={{background: 'black', display: 'block'}}>Porsche Light</PText>
            <PText color="inherit" style={{color: 'deeppink'}}>Inherited custom color</PText>
          </div>
          <div className="playground light spacing-block">
            <PText ellipsis={true}>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
              tempor
              invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
              dolores et ea rebum.
            </PText>
          </div>
          <div className="playground light spacing-block">
            <PText>Lorem ipsum dolor sit amet <a href="https://ui.porsche.com">linked text</a> et, <b>bold text</b> &amp; <strong>strong
              text</strong></PText>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PHeadline variant="headline-2">Action</PHeadline>
      <hr/>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-button-regular&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground light spacing-inline">
            <PButtonRegular variant="highlight">Click Here!</PButtonRegular>
            <PButtonRegular variant="highlight" disabled={true}>Disabled</PButtonRegular>
            <PButtonRegular variant="highlight" loading={true}>Loading...</PButtonRegular>
          </div>
          <div className="playground light spacing-inline">
            <PButtonRegular>Click Here!</PButtonRegular>
            <PButtonRegular disabled={true}>Disabled</PButtonRegular>
            <PButtonRegular loading={true}>Loading...</PButtonRegular>
          </div>
          <div className="playground light spacing-inline">
            <PButtonRegular variant="ghost">Click Here!</PButtonRegular>
            <PButtonRegular variant="ghost" disabled={true}>Disabled</PButtonRegular>
            <PButtonRegular variant="ghost" loading={true}>Loading...</PButtonRegular>
          </div>
          <div className="playground light spacing-inline">
            <PButtonRegular icon="phone">Click Here!</PButtonRegular>
          </div>
          <div className="playground light spacing-inline">
            <PButtonRegular small={true}>Click Here!</PButtonRegular>
            <PButtonRegular small={true} variant="ghost">Click Here!</PButtonRegular>
            <PButtonRegular small={true} variant="highlight">Click Here!</PButtonRegular>
          </div>
          <hr/>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground dark spacing-inline">
            <PButtonRegular theme="dark" variant="highlight">Click Here!</PButtonRegular>
            <PButtonRegular theme="dark" variant="highlight" disabled={true}>Disabled</PButtonRegular>
            <PButtonRegular theme="dark" variant="highlight" loading={true}>Loading...</PButtonRegular>
          </div>
          <div className="playground dark spacing-inline">
            <PButtonRegular theme="dark">Click Here!</PButtonRegular>
            <PButtonRegular theme="dark" disabled={true}>Disabled</PButtonRegular>
            <PButtonRegular theme="dark" loading={true}>Loading...</PButtonRegular>
          </div>
          <div className="playground dark spacing-inline">
            <PButtonRegular theme="dark" variant="ghost">Click Here!</PButtonRegular>
            <PButtonRegular theme="dark" variant="ghost" disabled={true}>Disabled</PButtonRegular>
            <PButtonRegular theme="dark" variant="ghost" loading={true}>Loading...</PButtonRegular>
          </div>
          <div className="playground dark spacing-inline">
            <PButtonRegular theme="dark" icon="phone">Click Here!</PButtonRegular>
          </div>
          <div className="playground dark spacing-inline">
            <PButtonRegular theme="dark" small={true}>Click Here!</PButtonRegular>
            <PButtonRegular theme="dark" small={true} variant="ghost">Click Here!</PButtonRegular>
            <PButtonRegular theme="dark" small={true} variant="highlight">Click Here!</PButtonRegular>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-button-icon&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground light spacing-inline">
            <PButtonIcon/>
            <PButtonIcon disabled={true}/>
            <PButtonIcon loading={true}/>
          </div>
          <div className="playground light spacing-inline">
            <PButtonIcon variant="ghost"/>
            <PButtonIcon variant="ghost" disabled={true}/>
            <PButtonIcon variant="ghost" loading={true}/>
          </div>
          <div className="playground light spacing-inline">
            <PButtonIcon variant="transparent"/>
            <PButtonIcon variant="transparent" disabled={true}/>
            <PButtonIcon variant="transparent" loading={true}/>
          </div>
          <div className="playground light spacing-inline">
            <PButtonIcon icon="phone"/>
          </div>
          <hr/>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground dark spacing-inline">
            <PButtonIcon theme="dark"/>
            <PButtonIcon theme="dark" disabled={true}/>
            <PButtonIcon theme="dark" loading={true}/>
          </div>
          <div className="playground dark spacing-inline">
            <PButtonIcon theme="dark" variant="ghost"/>
            <PButtonIcon theme="dark" variant="ghost" disabled={true}/>
            <PButtonIcon theme="dark" variant="ghost" loading={true}/>
          </div>
          <div className="playground dark spacing-inline">
            <PButtonIcon theme="dark" variant="transparent"/>
            <PButtonIcon theme="dark" variant="transparent" disabled={true}/>
            <PButtonIcon theme="dark" variant="transparent" loading={true}/>
          </div>
          <div className="playground dark spacing-inline">
            <PButtonIcon theme="dark" icon="phone"/>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-text-link&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="10">
          <div className="playground light spacing-inline">
            <PTextLink href="https://ui.porsche.com">Some link with default icon</PTextLink>
          </div>
          <div className="playground light spacing-inline">
            <PTextLink href="https://ui.porsche.com" color="porsche-black">Porsche Black</PTextLink>
            <PTextLink href="https://ui.porsche.com" color="porsche-light" style={{background: 'black'}}>Porsche
              Light
            </PTextLink>
            <PTextLink href="https://ui.porsche.com" color="inherit" style={{color: 'deeppink'}}>Inherited custom
              color
            </PTextLink>
          </div>
          <div className="playground light spacing-inline">
            <PTextLink href="https://ui.porsche.com" icon="delete">Some link with a custom icon</PTextLink>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PHeadline variant="headline-2">Content</PHeadline>
      <hr/>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">
            &lt;p-text-list&gt;<br/>
            &lt;p-text-list-item&gt;
          </PHeadline>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground light spacing-block">
            <PTextList>
              <PTextListItem>First level - Lorem ipsum dolor sit amet</PTextListItem>
              <PTextListItem>
                Lorem ipsum dolor sit amet <a href="https://ui.porsche.com">linked text</a> et, <b>bold text</b> &amp; <strong>strong
                text</strong>
                <PTextList>
                  <PTextListItem>Second level - Lorem ipsum dolor sit amet</PTextListItem>
                  <PTextListItem>Lorem ipsum</PTextListItem>
                </PTextList>
              </PTextListItem>
              <PTextListItem>First level - Lorem ipsum dolor sit amet</PTextListItem>
            </PTextList>
          </div>
          <div className="playground light spacing-block">
            <PTextList listType="ordered">
              <PTextListItem>First level - Lorem ipsum dolor sit amet</PTextListItem>
              <PTextListItem>
                Lorem ipsum dolor sit amet <a href="https://ui.porsche.com">linked text</a> et, <b>bold text</b> &amp; <strong>strong
                text</strong>
                <PTextList listType="ordered">
                  <PTextListItem>Second level - Lorem ipsum dolor sit amet</PTextListItem>
                  <PTextListItem>Lorem ipsum</PTextListItem>
                </PTextList>
              </PTextListItem>
              <PTextListItem>First level - Lorem ipsum dolor sit amet</PTextListItem>
            </PTextList>
          </div>
          <hr/>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground dark spacing-block">
            <PTextList color="porsche-light">
              <PTextListItem>First level - Lorem ipsum dolor sit amet</PTextListItem>
              <PTextListItem>
                Lorem ipsum dolor sit amet <a href="https://ui.porsche.com">linked text</a> et, <b>bold text</b> &amp; <strong>strong
                text</strong>
                <PTextList>
                  <PTextListItem>Second level - Lorem ipsum dolor sit amet</PTextListItem>
                  <PTextListItem>Lorem ipsum</PTextListItem>
                </PTextList>
              </PTextListItem>
              <PTextListItem>First level - Lorem ipsum dolor sit amet</PTextListItem>
            </PTextList>
          </div>
          <div className="playground dark spacing-block">
            <PTextList listType="ordered" color="inherit" style={{color: 'deeppink'}}>
              <PTextListItem>First level - Lorem ipsum dolor sit amet</PTextListItem>
              <PTextListItem>
                Lorem ipsum dolor sit amet <a href="https://ui.porsche.com">linked text</a> et, <b>bold text</b> &amp; <strong>strong
                text</strong>
                <PTextList>
                  <PTextListItem>Second level - Lorem ipsum dolor sit amet</PTextListItem>
                  <PTextListItem>Lorem ipsum</PTextListItem>
                </PTextList>
              </PTextListItem>
              <PTextListItem>First level - Lorem ipsum dolor sit amet</PTextListItem>
            </PTextList>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PHeadline variant="headline-2">Feedback</PHeadline>
      <hr/>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-spinner&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground light spacing-inline">
            <PSpinner size="x-small" allyLabel="Loading"/>
            <PSpinner size="small" allyLabel="Loading"/>
            <PSpinner size="medium" allyLabel="Loading"/>
            <PSpinner size="large" allyLabel="Loading"/>
          </div>
          <hr/>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground dark spacing-inline">
            <PSpinner theme="dark" size="x-small" allyLabel="Loading"/>
            <PSpinner theme="dark" size="small" allyLabel="Loading"/>
            <PSpinner theme="dark" size="medium" allyLabel="Loading"/>
            <PSpinner theme="dark" size="large" allyLabel="Loading"/>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PHeadline variant="headline-2">Icon</PHeadline>
      <hr/>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-icon&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="10">
          <div className="playground light spacing-inline">
            <PIcon source="car-next"/>
            <PIcon source="car-next" size="medium"/>
            <PIcon source="car-next" size="large"/>
            <PIcon source="car-next" size="large" color="neutral-grey-2"/>
            <PIcon source="car-next" size="large" color="inherit" style={{color: 'deeppink'}}/>
            <PIcon source="kaixin" size="large"/>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PHeadline variant="headline-2">Layout</PHeadline>
      <hr/>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">
            &lt;p-grid&gt;<br/>
            &lt;p-grid-child&gt;
          </PHeadline>
        </PGridChild>
        <PGridChild size="10">
          <div className="playground light spacing-block">
            <PGrid>
              <PGridChild size="12"/>
            </PGrid>
            <PGrid>
              <PGridChild size="1"/>
              <PGridChild size="11"/>
            </PGrid>
            <PGrid>
              <PGridChild size="2"/>
              <PGridChild size="10"/>
            </PGrid>
            <PGrid>
              <PGridChild size="3"/>
              <PGridChild size="9"/>
            </PGrid>
            <PGrid>
              <PGridChild size="4"/>
              <PGridChild size="8"/>
            </PGrid>
            <PGrid>
              <PGridChild size="5"/>
              <PGridChild size="7"/>
            </PGrid>
            <PGrid>
              <PGridChild size="6"/>
              <PGridChild size="6"/>
            </PGrid>
            <PGrid>
              <PGridChild size="7"/>
              <PGridChild size="5"/>
            </PGrid>
            <PGrid>
              <PGridChild size="8"/>
              <PGridChild size="4"/>
            </PGrid>
            <PGrid>
              <PGridChild size="9"/>
              <PGridChild size="3"/>
            </PGrid>
            <PGrid>
              <PGridChild size="10"/>
              <PGridChild size="2"/>
            </PGrid>
            <PGrid>
              <PGridChild size="11"/>
              <PGridChild size="1"/>
            </PGrid>
          </div>
          <div className="playground light spacing-block">
            <PGrid>
              <PGridChild offset="1" size="11"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="2" size="10"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="3" size="9"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="4" size="8"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="5" size="7"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="6" size="6"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="7" size="5"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="8" size="4"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="9" size="3"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="10" size="2"/>
            </PGrid>
            <PGrid>
              <PGridChild offset="11" size="1"/>
            </PGrid>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">
            &lt;p-flex&gt;<br/>
            &lt;p-flex-item&gt;
          </PHeadline>
        </PGridChild>
        <PGridChild size="10">
          <div className="playground light spacing-block">
            <PFlex>
              <PFlexItem width="one-quarter"/>
              <PFlexItem width="one-quarter"/>
              <PFlexItem width="one-quarter"/>
              <PFlexItem width="one-quarter"/>
            </PFlex>
            <PFlex>
              <PFlexItem width="one-third"/>
              <PFlexItem width="one-third"/>
              <PFlexItem width="one-third"/>
            </PFlex>
            <PFlex>
              <PFlexItem width="half"/>
              <PFlexItem width="half"/>
            </PFlex>
            <PFlex>
              <PFlexItem width="two-thirds"/>
              <PFlexItem width="one-third"/>
            </PFlex>
            <PFlex>
              <PFlexItem width="three-quarters"/>
              <PFlexItem width="one-quarter"/>
            </PFlex>
            <PFlex>
              <PFlexItem width="full"/>
            </PFlex>
          </div>
          <div className="playground light spacing-block">
            <PFlex>
              <PFlexItem offset="one-quarter" width="three-quarters"/>
            </PFlex>
            <PFlex>
              <PFlexItem offset="one-third" width="two-thirds"/>
            </PFlex>
            <PFlex>
              <PFlexItem offset="half" width="half"/>
            </PFlex>
            <PFlex>
              <PFlexItem offset="two-thirds" width="one-third"/>
            </PFlex>
            <PFlex>
              <PFlexItem offset="three-quarters" width="one-quarter"/>
            </PFlex>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">Spacing</PHeadline>
        </PGridChild>
        <PGridChild size="10">
          <div className="playground light spacing-inline">
            <PSpacing paddingTop={4} paddingLeft={4}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={8} paddingLeft={8}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={16} paddingLeft={16}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={24} paddingLeft={24}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={32} paddingLeft={32}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={40} paddingLeft={40}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={48} paddingLeft={48}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={56} paddingLeft={56}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={64} paddingLeft={64}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={72} paddingLeft={72}>
              <div/>
            </PSpacing>
            <PSpacing paddingTop={80} paddingLeft={80}>
              <div/>
            </PSpacing>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
      <PHeadline variant="headline-2">Navigation</PHeadline>
      <hr/>
      <PGrid>
        <PGridChild size="2">
          <PHeadline variant="headline-4" tag="h4">&lt;p-pagination&gt;</PHeadline>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground light spacing-block">
            <PPagination totalItemsCount={500} itemsPerPage={25} activePage={1}/>
          </div>
          <hr/>
        </PGridChild>
        <PGridChild size="5">
          <div className="playground dark spacing-block">
            <PPagination theme="dark" totalItemsCount={500} itemsPerPage={25} activePage={1}/>
          </div>
          <hr/>
        </PGridChild>
      </PGrid>
    </div>
  );
};

export default App;
