// packages/components-vue/projects/vue-wrapper/skill/references/components/p-tabs/examples/ActiveTab.vue
<script setup lang="ts">
  import { PTabs, PTabsItem, PText } from '@porsche-design-system/components-vue';
</script>

<template>
  <PTabs :activeTabIndex="1" :aria="{'aria-label': 'Some label for the tablist', 'aria-description': 'Some description for the tablist'}">
    <PTabsItem label="Tab One">
      <PText>
        Tab Content One
      </PText>
    </PTabsItem>
    <PTabsItem label="Tab Two">
      <PText>
        Tab Content Two
      </PText>
    </PTabsItem>
    <PTabsItem label="Tab Three">
      <PText>
        Tab Content Three
      </PText>
    </PTabsItem>
  </PTabs>
</template>

// packages/components-react/projects/react-wrapper/skill/references/components/p-tabs/examples/ActiveTab.tsx
import React from 'react';
import { PTabs, PTabsItem, PText } from '@porsche-design-system/components-react';

export const Example = () => {
  return (
    <>
      <PTabs activeTabIndex={1} aria={{'aria-label': 'Some label for the tablist', 'aria-description': 'Some description for the tablist'}}>
        <PTabsItem label="Tab One">
          <PText>
            Tab Content One
          </PText>
        </PTabsItem>
        <PTabsItem label="Tab Two">
          <PText>
            Tab Content Two
          </PText>
        </PTabsItem>
        <PTabsItem label="Tab Three">
          <PText>
            Tab Content Three
          </PText>
        </PTabsItem>
      </PTabs>
    </>
  )
}
