// packages/storefront/src/components/header/Header.tsx
import React from "react";
import { Link } from "react-router-dom";
import style from "./header.module.scss";
import { Logo } from "@porsche/ui-kit-react";
import { Text, Spacing } from "@porscheui/porsche-ui-kit";
import packageJson from "@porscheui/porsche-ui-kit/package.json";

export const Header: React.FunctionComponent = () => {
  return (
    <header>
      <Link className={style.logo} to={"/general/home"}>
        <Logo as="span" className={style.item} />
      </Link>
      <Spacing marginTop={16}>
        <Text type="headline-4" align="center" as="h1">
          Porsche UI Kit
        </Text>
        <Text type="small" align="center" as="p">
          Current Release: v{packageJson.version}
        </Text>
      </Spacing>
    </header>
  );
};

// packages/design-system/src/components/Header.vue
<template>
  <header class="header">
    <router-link class="link" to="/">
      <Marque/>
    </router-link>
    <p-headline class="p-spacing-mt--16" type="headline-4" level="1">Porsche UI Kit</p-headline>
    <p-text type="small">Current Release: {{version}}</p-text>
  </header>
</template>

<script lang="ts">
  import {Component, Vue} from 'vue-property-decorator';
  import Marque from '@/components/Marque.vue';
  // import {version} from '@porscheui/ui-kit-js/package.json';

  @Component({
    components: {
      Marque,
    },
  })
  export default class Header extends Vue {
    public version = '1.0.0-alpha.1';
  }
</script>

<style scoped lang="scss">
  .header {
    text-align: center;
  }

  .link {
    display: inline-block;
  }
</style>
