// packages/components-vue/projects/vue-wrapper/skill/references/components/p-checkbox/examples/Indeterminate.vue
<script setup lang="ts">
  import { PCheckbox } from '@porsche-design-system/components-vue';
</script>

<template>
  <div class="flex flex-col gap-static-sm">
    <PCheckbox label="Some label" :indeterminate="true"></PCheckbox>
    <PCheckbox label="Some label" :indeterminate="true" :checked="true"></PCheckbox>
  </div>
</template>

// packages/components-react/projects/react-wrapper/skill/references/components/p-checkbox/examples/Indeterminate.tsx
import React from 'react';
import { PCheckbox } from '@porsche-design-system/components-react';

export const Example = () => {
  return (
    <>
      <div className="flex flex-col gap-static-sm">
        <PCheckbox label="Some label" indeterminate={true}></PCheckbox>
        <PCheckbox label="Some label" indeterminate={true} checked={true}></PCheckbox>
      </div>
    </>
  )
}
