// packages/components-angular/projects/angular-wrapper/skill/references/components/p-ai-tag/examples/WithinInputSearch.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
      <p-input-search label="What's your favorite Fruit" description="Search for fruits" name="search">
        <p-ai-tag slot="end" variant="abbreviation"></p-ai-tag>
      </p-input-search>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule], // <-- PDS module is imported here
})
export class ExampleComponent {}

// packages/components-vue/projects/vue-wrapper/skill/references/components/p-ai-tag/examples/WithinInputSearch.vue
<script setup lang="ts">
  import { PAiTag, PInputSearch } from '@porsche-design-system/components-vue';
</script>

<template>
  <PInputSearch label="What's your favorite Fruit" description="Search for fruits" name="search">
    <PAiTag slot="end" variant="abbreviation"></PAiTag>
  </PInputSearch>
</template>
