// packages/components-angular/projects/angular-wrapper/skill/references/components/p-ai-tag/examples/WithinRadioGroup.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
      <p-heading size="small" tag="h3">
        Pick your favorite Fruits
      </p-heading>

      <p-radio-group label="Some Label" name="fruit" value="banana" class="mt-static-sm">
        <p-radio-group-option value="banana">
          <span slot="label">
            Banana
            <p-ai-tag variant="generated" class="ms-static-sm"></p-ai-tag>
          </span>
        </p-radio-group-option>
        <p-radio-group-option value="apple" label="Apple"></p-radio-group-option>
        <p-radio-group-option value="melon">
          <span slot="label">
            Melon
            <p-ai-tag variant="abbreviation" class="ms-static-sm"></p-ai-tag>
          </span>
        </p-radio-group-option>
        <p-radio-group-option value="grapefruit" label="Grapefruit"></p-radio-group-option>
      </p-radio-group>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule], // <-- PDS module is imported here
})
export class ExampleComponent {}

// packages/components-vue/projects/vue-wrapper/skill/references/components/p-ai-tag/examples/WithinRadioGroup.vue
<script setup lang="ts">
  import { PAiTag, PHeading, PRadioGroup, PRadioGroupOption } from '@porsche-design-system/components-vue';
</script>

<template>
  <PHeading size="small" tag="h3">
    Pick your favorite Fruits
  </PHeading>

  <PRadioGroup label="Some Label" name="fruit" value="banana" class="mt-static-sm">
    <PRadioGroupOption value="banana">
      <span slot="label">
        Banana
        <PAiTag variant="generated" class="ms-static-sm"></PAiTag>
      </span>
    </PRadioGroupOption>
    <PRadioGroupOption value="apple" label="Apple"></PRadioGroupOption>
    <PRadioGroupOption value="melon">
      <span slot="label">
        Melon
        <PAiTag variant="abbreviation" class="ms-static-sm"></PAiTag>
      </span>
    </PRadioGroupOption>
    <PRadioGroupOption value="grapefruit" label="Grapefruit"></PRadioGroupOption>
  </PRadioGroup>
</template>
