// packages/components-angular/projects/angular-wrapper/skill/references/components/p-multi-select/examples/Optgroups.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
      <p-multi-select name="options" label="Some Label">
        <p-optgroup label="Some optgroup label 1">
          <p-multi-select-option value="a">
            Option A
          </p-multi-select-option>
          <p-multi-select-option value="b">
            Option B
          </p-multi-select-option>
          <p-multi-select-option value="c">
            Option C
          </p-multi-select-option>
          <p-multi-select-option value="d">
            Option D
          </p-multi-select-option>
          <p-multi-select-option value="e">
            Option E
          </p-multi-select-option>
          <p-multi-select-option value="f">
            Option F
          </p-multi-select-option>
        </p-optgroup>
        <p-optgroup label="Some optgroup label 2">
          <p-multi-select-option value="g">
            Option G
          </p-multi-select-option>
          <p-multi-select-option value="h">
            Option H
          </p-multi-select-option>
          <p-multi-select-option value="i">
            Option I
          </p-multi-select-option>
        </p-optgroup>
      </p-multi-select>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule], // <-- PDS module is imported here
})
export class ExampleComponent {}

// packages/components-vue/projects/vue-wrapper/skill/references/components/p-multi-select/examples/Optgroups.vue
<script setup lang="ts">
  import { PMultiSelect, PMultiSelectOption, POptgroup } from '@porsche-design-system/components-vue';
</script>

<template>
  <PMultiSelect name="options" label="Some Label">
    <POptgroup label="Some optgroup label 1">
      <PMultiSelectOption value="a">
        Option A
      </PMultiSelectOption>
      <PMultiSelectOption value="b">
        Option B
      </PMultiSelectOption>
      <PMultiSelectOption value="c">
        Option C
      </PMultiSelectOption>
      <PMultiSelectOption value="d">
        Option D
      </PMultiSelectOption>
      <PMultiSelectOption value="e">
        Option E
      </PMultiSelectOption>
      <PMultiSelectOption value="f">
        Option F
      </PMultiSelectOption>
    </POptgroup>
    <POptgroup label="Some optgroup label 2">
      <PMultiSelectOption value="g">
        Option G
      </PMultiSelectOption>
      <PMultiSelectOption value="h">
        Option H
      </PMultiSelectOption>
      <PMultiSelectOption value="i">
        Option I
      </PMultiSelectOption>
    </POptgroup>
  </PMultiSelect>
</template>
