// packages/components-angular/src/app/pages/core-initializer.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { componentsReady } from '@porsche-design-system/components-angular';

@Component({
  selector: 'page-core-initializer',
  template: `
    <div class="playground light">
      <p-text-field-wrapper [label]="'Some Label'" [description]="'Some Description'">
        <input [type]="'text'" />
      </p-text-field-wrapper>

      <div *ngIf="allReady">
        <p-text-field-wrapper [label]="'Some Label'" [description]="'Some Description'">
          <input [type]="'text'" />
        </p-text-field-wrapper>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CoreInitializerComponent implements OnInit {
  public allReady: boolean = false;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit() {
    componentsReady().then(() => {
      this.allReady = true;
      this.cdr.markForCheck();
    });
  }
}

// packages/components-react/src/pages/CoreInitializer.tsx
/* Auto Generated File */
import { componentsReady, PTextFieldWrapper } from '@porsche-design-system/components-react';
import { useEffect, useState } from 'react';

export const CoreInitializerPage = (): JSX.Element => {
  const [allReady, setAllReady] = useState(false);
  useEffect(() => {
    componentsReady().then(() => {
      setAllReady(true);
    });
  }, []);

  return (
    <>
      <div className="playground light">
        <PTextFieldWrapper label="Some Label" description="Some Description">
          <input type="text" />
        </PTextFieldWrapper>

        {allReady && (
          <div>
            <PTextFieldWrapper label="Some Label" description="Some Description">
              <input type="text" />
            </PTextFieldWrapper>
          </div>
        )}
      </div>
    </>
  );
};
