// packages/components-angular/src/app/pages/display.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-display',
  template: `
    <div class="playground light" title="should show display with different color variants on light background">
      <p-display [color]="'primary'" style="color: deeppink">The quick brown fox jumps over the lazy dog</p-display>
      <p-display [color]="'inherit'" style="color: deeppink">The quick brown fox jumps over the lazy dog</p-display>
    </div>

    <div class="playground dark" title="should show display with different color variants on dark background">
      <p-display [theme]="'dark'" [color]="'primary'" style="color: deeppink"
        >The quick brown fox jumps over the lazy dog</p-display
      >
      <p-display [theme]="'dark'" [color]="'inherit'" style="color: deeppink"
        >The quick brown fox jumps over the lazy dog</p-display
      >
    </div>

    <div class="playground" title="should show display with different alignments">
      <p-display [align]="'left'">Left</p-display>
      <p-display [align]="'center'">Center</p-display>
      <p-display [align]="'right'">Right</p-display>
    </div>

    <div class="playground" title="should cut off too long text">
      <p-display [ellipsis]="true">
        Text ellipsis - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
        labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
      </p-display>
    </div>

    <div class="playground" title="should apply custom styles for dedicated slotted content">
      <p-display [size]="'medium'">
        <span>
          Some slotted and deeply nested <a [href]="'#'">link</a> and <button>button</button>, <b>bold</b>,
          <strong>strong</strong>, <em>emphasized</em> and <i>italic</i> text
        </span>
      </p-display>
    </div>

    <div class="playground" title="should show display with different slotted tags in same layout as default">
      <p-display [size]="'inherit'" style="font-size: 1rem"><h1>The quick brown fox jumps over the lazy dog</h1></p-display>
      <p-display [size]="'inherit'" style="font-size: 1rem"><h2>The quick brown fox jumps over the lazy dog</h2></p-display>
      <p-display [size]="'inherit'" style="font-size: 1rem"><h3>The quick brown fox jumps over the lazy dog</h3></p-display>
      <p-display [size]="'inherit'" style="font-size: 1rem"><h4>The quick brown fox jumps over the lazy dog</h4></p-display>
      <p-display [size]="'inherit'" style="font-size: 1rem"><h5>The quick brown fox jumps over the lazy dog</h5></p-display>
      <p-display [size]="'inherit'" style="font-size: 1rem"><h6>The quick brown fox jumps over the lazy dog</h6></p-display>
    </div>

    <div class="playground" title="should show display in different sizes">
      <p-display [size]="'medium'">The quick brown fox jumps over the lazy dog</p-display>
      <p-display [size]="'large'">The quick brown fox jumps over the lazy dog</p-display>
      <p-display [size]="'inherit'" style="font-size: 5rem">The quick brown fox jumps over the lazy dog</p-display>
    </div>

    <div class="playground" title="should show display in different sizes on different viewports">
      <p-display [size]="{ base: 'medium', m: 'inherit', l: 'large' }" style="font-size: 5rem">
        The quick brown fox jumps over the lazy dog
      </p-display>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DisplayComponent {}

// packages/components-react/src/pages/Display.tsx
/* Auto Generated File */
import { PDisplay } from '@porsche-design-system/components-react';

export const DisplayPage = (): JSX.Element => {
  return (
    <>
      <div className="playground light" title="should show display with different color variants on light background">
        <PDisplay color="primary" style={{ color: 'deeppink' }}>The quick brown fox jumps over the lazy dog</PDisplay>
        <PDisplay color="inherit" style={{ color: 'deeppink' }}>The quick brown fox jumps over the lazy dog</PDisplay>
      </div>

      <div className="playground dark" title="should show display with different color variants on dark background">
        <PDisplay theme="dark" color="primary" style={{ color: 'deeppink' }}
          >The quick brown fox jumps over the lazy dog</PDisplay
        >
        <PDisplay theme="dark" color="inherit" style={{ color: 'deeppink' }}
          >The quick brown fox jumps over the lazy dog</PDisplay
        >
      </div>

      <div className="playground" title="should show display with different alignments">
        <PDisplay align="left">Left</PDisplay>
        <PDisplay align="center">Center</PDisplay>
        <PDisplay align="right">Right</PDisplay>
      </div>

      <div className="playground" title="should cut off too long text">
        <PDisplay ellipsis={true}>
          Text ellipsis - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
          labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
        </PDisplay>
      </div>

      <div className="playground" title="should apply custom styles for dedicated slotted content">
        <PDisplay size="medium">
          <span>
            Some slotted and deeply nested <a href="#">link</a> and <button>button</button>, <b>bold</b>,
            {' '}<strong>strong</strong>, <em>emphasized</em> and <i>italic</i> text
          </span>
        </PDisplay>
      </div>

      <div className="playground" title="should show display with different slotted tags in same layout as default">
        <PDisplay size="inherit" style={{ fontSize: '1rem' }}><h1>The quick brown fox jumps over the lazy dog</h1></PDisplay>
        <PDisplay size="inherit" style={{ fontSize: '1rem' }}><h2>The quick brown fox jumps over the lazy dog</h2></PDisplay>
        <PDisplay size="inherit" style={{ fontSize: '1rem' }}><h3>The quick brown fox jumps over the lazy dog</h3></PDisplay>
        <PDisplay size="inherit" style={{ fontSize: '1rem' }}><h4>The quick brown fox jumps over the lazy dog</h4></PDisplay>
        <PDisplay size="inherit" style={{ fontSize: '1rem' }}><h5>The quick brown fox jumps over the lazy dog</h5></PDisplay>
        <PDisplay size="inherit" style={{ fontSize: '1rem' }}><h6>The quick brown fox jumps over the lazy dog</h6></PDisplay>
      </div>

      <div className="playground" title="should show display in different sizes">
        <PDisplay size="medium">The quick brown fox jumps over the lazy dog</PDisplay>
        <PDisplay size="large">The quick brown fox jumps over the lazy dog</PDisplay>
        <PDisplay size="inherit" style={{ fontSize: '5rem' }}>The quick brown fox jumps over the lazy dog</PDisplay>
      </div>

      <div className="playground" title="should show display in different sizes on different viewports">
        <PDisplay size={{ base: 'medium', m: 'inherit', l: 'large' }} style={{ fontSize: '5rem' }}>
          The quick brown fox jumps over the lazy dog
        </PDisplay>
      </div>
    </>
  );
};
