// packages/components-angular/src/app/pages/initializer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'page-initializer',
  template: `
    <div class="playground light">
      <p-text-field-wrapper [label]="'Some Label'" [description]="'Some Description'">
        <input type="text" />
      </p-text-field-wrapper>

      <p-text-field-wrapper *ngIf="isEnabled" [label]="'Some Label'" [description]="'Some Description'">
        <input type="text" />
      </p-text-field-wrapper>
    </div>
  `,
})
export class InitializerComponent {
  public isEnabled = false;

  public ngOnInit() {
    setTimeout(() => {
      this.isEnabled = true;
    }, 1000);
  }
}

// packages/components-react/src/pages/Initializer.tsx
import { useEffect, useState } from 'react';
import { PTextFieldWrapper } from '@porsche-design-system/components-react';

export const InitializerPage = (): JSX.Element => {
  const [isEnabled, setIsEnabled] = useState(false);
  useEffect(() => {
    setTimeout(() => setIsEnabled(true), 1000);
  }, []);

  return (
    <>
      <div className="playground light">
        <PTextFieldWrapper label="Some Label" description="Some Description">
          <input type="text" />
        </PTextFieldWrapper>

        {isEnabled && (
          <PTextFieldWrapper label="Some Label" description="Some Description">
            <input type="text" />
          </PTextFieldWrapper>
        )}
      </div>
    </>
  );
};
