// packages/components-angular/src/app/pages/layout.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-layout',
  template: `
    <p-headline [variant]="'headline-2'">Layout</p-headline>
    <hr>
    <p-grid>
      <p-grid-item [size]="2">
        <p-headline [variant]="'headline-4'" [tag]="'h4'">
          &lt;p-grid&gt;<br>
          &lt;p-grid-item&gt;
        </p-headline>
      </p-grid-item>
      <p-grid-item [size]="10">
        <div class="playground light spacing-block">
          <p-grid>
            <p-grid-item [size]="12"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="1"></p-grid-item>
            <p-grid-item [size]="11"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="2"></p-grid-item>
            <p-grid-item [size]="10"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="3"></p-grid-item>
            <p-grid-item [size]="9"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="4"></p-grid-item>
            <p-grid-item [size]="8"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="5"></p-grid-item>
            <p-grid-item [size]="7"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="6"></p-grid-item>
            <p-grid-item [size]="6"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="7"></p-grid-item>
            <p-grid-item [size]="5"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="8"></p-grid-item>
            <p-grid-item [size]="4"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="9"></p-grid-item>
            <p-grid-item [size]="3"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="10"></p-grid-item>
            <p-grid-item [size]="2"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [size]="11"></p-grid-item>
            <p-grid-item [size]="1"></p-grid-item>
          </p-grid>
        </div>
        <div class="playground light spacing-block">
          <p-grid>
            <p-grid-item [offset]="1" [size]="11"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="2" [size]="10"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="3" [size]="9"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="4" [size]="8"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="5" [size]="7"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="6" [size]="6"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="7" [size]="5"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="8" [size]="4"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="9" [size]="3"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="10" [size]="2"></p-grid-item>
          </p-grid>
          <p-grid>
            <p-grid-item [offset]="11" [size]="1"></p-grid-item>
          </p-grid>
        </div>
        <hr>
      </p-grid-item>
    </p-grid>
    <p-grid>
      <p-grid-item [size]="2">
        <p-headline [variant]="'headline-4'" [tag]="'h4'">
          &lt;p-flex&gt;<br>
          &lt;p-flex-item&gt;
        </p-headline>
      </p-grid-item>
      <p-grid-item [size]="10">
        <div class="playground light spacing-block">
          <p-flex>
            <p-flex-item [width]="'full'"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item [offset]="'one-quarter'" [width]="'three-quarters'"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item [offset]="'one-third'" [width]="'two-thirds'"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item [offset]="'half'" [width]="'half'"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item [offset]="'two-thirds'" [width]="'one-third'"></p-flex-item>
          </p-flex>
          <p-flex>
            <p-flex-item [offset]="'three-quarters'" [width]="'one-quarter'"></p-flex-item>
          </p-flex>
        </div>
        <hr>
      </p-grid-item>
    </p-grid>
  `
})
export class LayoutComponent {

}

// packages/components-react/src/pages/Layout.tsx
import {Flex, FlexItem, Grid, GridItem, Headline} from '@porsche-design-system/components-react';
import React from 'react';

export function Layout(){
  return(
    <div>
      <Headline variant={'headline-2'}>Layout</Headline>
      <hr/>
      <Grid>
        <GridItem size={2}>
          <Headline variant={'headline-4'} tag={'h4'}>
            &lt;p-grid&gt;<br/>
            &lt;p-grid-item&gt;
          </Headline>
        </GridItem>
        <GridItem size={10}>
          <div className="playground light spacing-block">
            <Grid>
              <GridItem size={12}/>
            </Grid>
            <Grid>
              <GridItem size={1}/>
              <GridItem size={11}/>
            </Grid>
            <Grid>
              <GridItem size={2}/>
              <GridItem size={10}/>
            </Grid>
            <Grid>
              <GridItem size={3}/>
              <GridItem size={9}/>
            </Grid>
            <Grid>
              <GridItem size={4}/>
              <GridItem size={8}/>
            </Grid>
            <Grid>
              <GridItem size={5}/>
              <GridItem size={7}/>
            </Grid>
            <Grid>
              <GridItem size={6}/>
              <GridItem size={6}/>
            </Grid>
            <Grid>
              <GridItem size={7}/>
              <GridItem size={5}/>
            </Grid>
            <Grid>
              <GridItem size={8}/>
              <GridItem size={4}/>
            </Grid>
            <Grid>
              <GridItem size={9}/>
              <GridItem size={3}/>
            </Grid>
            <Grid>
              <GridItem size={10}/>
              <GridItem size={2}/>
            </Grid>
            <Grid>
              <GridItem size={11}/>
              <GridItem size={1}/>
            </Grid>
          </div>
          <div className="playground light spacing-block">
            <Grid>
              <GridItem offset={1} size={11}/>
            </Grid>
            <Grid>
              <GridItem offset={2} size={10}/>
            </Grid>
            <Grid>
              <GridItem offset={3} size={9}/>
            </Grid>
            <Grid>
              <GridItem offset={4} size={8}/>
            </Grid>
            <Grid>
              <GridItem offset={5} size={7}/>
            </Grid>
            <Grid>
              <GridItem offset={6} size={6}/>
            </Grid>
            <Grid>
              <GridItem offset={7} size={5}/>
            </Grid>
            <Grid>
              <GridItem offset={8} size={4}/>
            </Grid>
            <Grid>
              <GridItem offset={9} size={3}/>
            </Grid>
            <Grid>
              <GridItem offset={10} size={2}/>
            </Grid>
            <Grid>
              <GridItem offset={11} size={1}/>
            </Grid>
          </div>
          <hr/>
        </GridItem>
      </Grid>
      <Grid>
        <GridItem size={2}>
          <Headline variant={'headline-4'} tag={'h4'}>
            &lt;p-flex&gt;<br/>
            &lt;p-flex-item&gt;
          </Headline>
        </GridItem>
        <GridItem size={10}>
          <div className="playground light spacing-block">
            <Flex>
              <FlexItem width={'full'}/>
            </Flex>
            <Flex>
              <FlexItem offset={'one-quarter'} width={'three-quarters'}/>
            </Flex>
            <Flex>
              <FlexItem offset={'one-third'} width={'two-thirds'}/>
            </Flex>
            <Flex>
              <FlexItem offset={'half'} width={'half'}/>
            </Flex>
            <Flex>
              <FlexItem offset={'two-thirds'} width={'one-third'}/>
            </Flex>
            <Flex>
              <FlexItem offset={'three-quarters'} width={'one-quarter'}/>
            </Flex>
          </div>
          <hr/>
        </GridItem>
      </Grid>
    </div>
  );
}
