// packages/components-angular/src/app/pages/modal-footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'page-modal-footer',
  styles: [
    `
      .playground {
        height: 500px;
        padding: 0;
      }
    `
  ],
  template: `
    <div class="playground light" title="should show modal with footer and without close button on light background">
      <p-modal [heading]="'Some Heading'" [open]="'true'" [disableCloseButton]="'true'">
        Some Content
        <p-modal-footer>
          <p-button>Confirm</p-button>
          <p-button variant="tertiary">Cancel</p-button>
        </p-modal-footer>
      </p-modal>
    </div>
  `
})
export class ModalFooterComponent {
  constructor() {
    document.body.style.height = '500px';
  }
}

// packages/components-react/src/pages/ModalFooter.tsx
import {
  PModal as Modal,
  PButton as Button,
  PModalFooter as ModalFooter
} from '@porsche-design-system/components-react';
import React, { useEffect } from 'react';

export const ModalFooterPage = (): JSX.Element => {
  useEffect(() => {
    document.body.style.height = '500px';
  }, []);

  const style = `
    .playground {
      height: 500px;
      padding: 0;
    }
  `;

  return (
    <>
      <style children={style} />
      <div
        className="playground light"
        title="should show modal with footer and without close button on light background"
      >
        <Modal heading="Some Heading" open disableCloseButton>
          Some Content
          <ModalFooter>
            <Button>Confirm</Button>
            <Button variant="tertiary">Cancel</Button>
          </ModalFooter>
        </Modal>
      </div>
    </>
  );
};
