// packages/components-angular/src/app/pages/model-signature.component.ts
/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-model-signature',
  styles: [
    `
      @media only screen and (min-width: 760px) {
        #app,
        :host {
          display: grid;
          grid-template-columns: repeat(2, 50%);
        }
      }
    `,
  ],
  template: `
    <div class="playground light" title="should render for model 718 on light background">
      <p-model-signature [model]="'718'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model 718 on dark background">
      <p-model-signature [model]="'718'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model 911 on light background">
      <p-model-signature [model]="'911'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model 911 on dark background">
      <p-model-signature [model]="'911'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model boxster on light background">
      <p-model-signature [model]="'boxster'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model boxster on dark background">
      <p-model-signature [model]="'boxster'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model cayenne on light background">
      <p-model-signature [model]="'cayenne'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model cayenne on dark background">
      <p-model-signature [model]="'cayenne'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model cayman on light background">
      <p-model-signature [model]="'cayman'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model cayman on dark background">
      <p-model-signature [model]="'cayman'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model macan on light background">
      <p-model-signature [model]="'macan'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model macan on dark background">
      <p-model-signature [model]="'macan'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model panamera on light background">
      <p-model-signature [model]="'panamera'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model panamera on dark background">
      <p-model-signature [model]="'panamera'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model taycan on light background">
      <p-model-signature [model]="'taycan'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model taycan on dark background">
      <p-model-signature [model]="'taycan'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for model turbo on light background">
      <p-model-signature [model]="'turbo'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for model turbo on dark background">
      <p-model-signature [model]="'turbo'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color primary on light background">
      <p-model-signature [model]="'911'" [color]="'primary'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for color primary on dark background">
      <p-model-signature [model]="'911'" [color]="'primary'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color contrast-low on light background">
      <p-model-signature [model]="'911'" [color]="'contrast-low'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for color contrast-low on dark background">
      <p-model-signature [model]="'911'" [color]="'contrast-low'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color contrast-medium on light background">
      <p-model-signature [model]="'911'" [color]="'contrast-medium'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for color contrast-medium on dark background">
      <p-model-signature [model]="'911'" [color]="'contrast-medium'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color contrast-high on light background">
      <p-model-signature [model]="'911'" [color]="'contrast-high'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for color contrast-high on dark background">
      <p-model-signature [model]="'911'" [color]="'contrast-high'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for color inherit on light background">
      <p-model-signature
        [model]="'911'"
        [color]="'inherit'"
        style="filter: invert(24%) sepia(70%) saturate(5969%) hue-rotate(316deg) brightness(102%) contrast(102%)"
      ></p-model-signature>
    </div>
    <div class="playground dark" title="should render for color inherit on dark background">
      <p-model-signature
        [model]="'911'"
        [color]="'inherit'"
        style="filter: invert(24%) sepia(70%) saturate(5969%) hue-rotate(316deg) brightness(102%) contrast(102%)"
        [theme]="'dark'"
      ></p-model-signature>
    </div>

    <div class="playground light" title="should render for size small on light background">
      <p-model-signature [model]="'911'" [size]="'small'"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for size small on dark background">
      <p-model-signature [model]="'911'" [size]="'small'" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should render for size inherit on light background">
      <p-model-signature [model]="'911'" [size]="'inherit'" style="height: 100px"></p-model-signature>
    </div>
    <div class="playground dark" title="should render for size inherit on dark background">
      <p-model-signature [model]="'911'" [size]="'inherit'" style="height: 100px" [theme]="'dark'"></p-model-signature>
    </div>

    <div class="playground light" title="should not exceed parents width">
      <div style="width: 180px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" style="background: lightblue"></p-model-signature>
      </div>
      <br />
      <div style="width: 180px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" [size]="'inherit'" style="background: lightblue; height: 40px"></p-model-signature>
      </div>
    </div>

    <div
      class="playground light"
      title="should not exceed max-width of model-signature itself, although parent provides more width"
    >
      <div style="width: 272px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" style="background: lightblue"></p-model-signature>
      </div>
      <br />
      <div style="width: 272px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" [size]="'inherit'" style="background: lightblue; height: 40px"></p-model-signature>
      </div>
    </div>

    <div class="playground light" title="should not exceed parents height">
      <div style="height: 10px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" style="background: lightblue"></p-model-signature>
      </div>
      <br />
      <div style="height: 10px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" [size]="'inherit'" style="background: lightblue; height: 40px"></p-model-signature>
      </div>
    </div>

    <div
      class="playground light"
      title="should not exceed max-height of model-signature itself, although parent provides more height"
    >
      <div style="height: 100px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" style="background: lightblue"></p-model-signature>
      </div>
      <br />
      <div style="height: 100px; background: lightsalmon">
        <p-model-signature [model]="'cayenne'" [size]="'inherit'" style="background: lightblue; height: 40px"></p-model-signature>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ModelSignatureComponent {}

// packages/components-react/src/pages/ModelSignature.tsx
/* Auto Generated File */
import { PModelSignature } from '@porsche-design-system/components-react';

export const ModelSignaturePage = (): JSX.Element => {
  const style = `
    @media only screen and (min-width: 760px) {
      #app,
      :host {
        display: grid;
        grid-template-columns: repeat(2, 50%);
      }
    }
  `;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: style }} />

      <div className="playground light" title="should render for model 718 on light background">
        <PModelSignature model="718" />
      </div>
      <div className="playground dark" title="should render for model 718 on dark background">
        <PModelSignature model="718" theme="dark" />
      </div>

      <div className="playground light" title="should render for model 911 on light background">
        <PModelSignature model="911" />
      </div>
      <div className="playground dark" title="should render for model 911 on dark background">
        <PModelSignature model="911" theme="dark" />
      </div>

      <div className="playground light" title="should render for model boxster on light background">
        <PModelSignature model="boxster" />
      </div>
      <div className="playground dark" title="should render for model boxster on dark background">
        <PModelSignature model="boxster" theme="dark" />
      </div>

      <div className="playground light" title="should render for model cayenne on light background">
        <PModelSignature model="cayenne" />
      </div>
      <div className="playground dark" title="should render for model cayenne on dark background">
        <PModelSignature model="cayenne" theme="dark" />
      </div>

      <div className="playground light" title="should render for model cayman on light background">
        <PModelSignature model="cayman" />
      </div>
      <div className="playground dark" title="should render for model cayman on dark background">
        <PModelSignature model="cayman" theme="dark" />
      </div>

      <div className="playground light" title="should render for model macan on light background">
        <PModelSignature model="macan" />
      </div>
      <div className="playground dark" title="should render for model macan on dark background">
        <PModelSignature model="macan" theme="dark" />
      </div>

      <div className="playground light" title="should render for model panamera on light background">
        <PModelSignature model="panamera" />
      </div>
      <div className="playground dark" title="should render for model panamera on dark background">
        <PModelSignature model="panamera" theme="dark" />
      </div>

      <div className="playground light" title="should render for model taycan on light background">
        <PModelSignature model="taycan" />
      </div>
      <div className="playground dark" title="should render for model taycan on dark background">
        <PModelSignature model="taycan" theme="dark" />
      </div>

      <div className="playground light" title="should render for model turbo on light background">
        <PModelSignature model="turbo" />
      </div>
      <div className="playground dark" title="should render for model turbo on dark background">
        <PModelSignature model="turbo" theme="dark" />
      </div>

      <div className="playground light" title="should render for color primary on light background">
        <PModelSignature model="911" color="primary" />
      </div>
      <div className="playground dark" title="should render for color primary on dark background">
        <PModelSignature model="911" color="primary" theme="dark" />
      </div>

      <div className="playground light" title="should render for color contrast-low on light background">
        <PModelSignature model="911" color="contrast-low" />
      </div>
      <div className="playground dark" title="should render for color contrast-low on dark background">
        <PModelSignature model="911" color="contrast-low" theme="dark" />
      </div>

      <div className="playground light" title="should render for color contrast-medium on light background">
        <PModelSignature model="911" color="contrast-medium" />
      </div>
      <div className="playground dark" title="should render for color contrast-medium on dark background">
        <PModelSignature model="911" color="contrast-medium" theme="dark" />
      </div>

      <div className="playground light" title="should render for color contrast-high on light background">
        <PModelSignature model="911" color="contrast-high" />
      </div>
      <div className="playground dark" title="should render for color contrast-high on dark background">
        <PModelSignature model="911" color="contrast-high" theme="dark" />
      </div>

      <div className="playground light" title="should render for color inherit on light background">
        <PModelSignature
          model="911"
          color="inherit"
          style={{ filter: 'invert(24%) sepia(70%) saturate(5969%) hue-rotate(316deg) brightness(102%) contrast(102%)' }}
         />
      </div>
      <div className="playground dark" title="should render for color inherit on dark background">
        <PModelSignature
          model="911"
          color="inherit"
          style={{ filter: 'invert(24%) sepia(70%) saturate(5969%) hue-rotate(316deg) brightness(102%) contrast(102%)' }}
          theme="dark"
         />
      </div>

      <div className="playground light" title="should render for size small on light background">
        <PModelSignature model="911" size="small" />
      </div>
      <div className="playground dark" title="should render for size small on dark background">
        <PModelSignature model="911" size="small" theme="dark" />
      </div>

      <div className="playground light" title="should render for size inherit on light background">
        <PModelSignature model="911" size="inherit" style={{ height: '100px' }} />
      </div>
      <div className="playground dark" title="should render for size inherit on dark background">
        <PModelSignature model="911" size="inherit" style={{ height: '100px' }} theme="dark" />
      </div>

      <div className="playground light" title="should not exceed parents width">
        <div style={{ width: '180px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" style={{ background: 'lightblue' }} />
        </div>
        <br />
        <div style={{ width: '180px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" size="inherit" style={{ background: 'lightblue', height: '40px' }} />
        </div>
      </div>

      <div
        className="playground light"
        title="should not exceed max-width of model-signature itself, although parent provides more width"
      >
        <div style={{ width: '272px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" style={{ background: 'lightblue' }} />
        </div>
        <br />
        <div style={{ width: '272px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" size="inherit" style={{ background: 'lightblue', height: '40px' }} />
        </div>
      </div>

      <div className="playground light" title="should not exceed parents height">
        <div style={{ height: '10px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" style={{ background: 'lightblue' }} />
        </div>
        <br />
        <div style={{ height: '10px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" size="inherit" style={{ background: 'lightblue', height: '40px' }} />
        </div>
      </div>

      <div
        className="playground light"
        title="should not exceed max-height of model-signature itself, although parent provides more height"
      >
        <div style={{ height: '100px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" style={{ background: 'lightblue' }} />
        </div>
        <br />
        <div style={{ height: '100px', background: 'lightsalmon' }}>
          <PModelSignature model="cayenne" size="inherit" style={{ background: 'lightblue', height: '40px' }} />
        </div>
      </div>
    </>
  );
};
