// packages/components-angular/src/app/pages/toast-item.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-toast-item',
  template: `
    <div class="playground light" title="should render toast neutral on light background">
      <p-toast-item [message]="'Some neutral message'" [state]="'neutral'"></p-toast-item>
    </div>

    <div class="playground dark" title="should render toast neutral on dark background">
      <p-toast-item [message]="'Some neutral message'" [state]="'neutral'" [theme]="'dark'"></p-toast-item>
    </div>

    <div class="playground light" title="should render toast success on light background">
      <p-toast-item [message]="'Some success message'" [state]="'success'"></p-toast-item>
    </div>

    <div class="playground dark" title="should render toast success on dark background">
      <p-toast-item [message]="'Some success message'" [state]="'success'" [theme]="'dark'"></p-toast-item>
    </div>

    <div class="playground light" title="should render toast multiline message on light background">
      <p-toast-item
        [message]="'Some message with a very long text across multiple lines'"
        style="width: 240px"
      ></p-toast-item>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToastItemComponent {}

// packages/components-react/src/pages/ToastItem.tsx
import { PToastItem } from '@porsche-design-system/components-react';

export const ToastItemPage = (): JSX.Element => {
  return (
    <>
      <div className="playground light" title="should render toast neutral on light background">
        <PToastItem message="Some neutral message" state="neutral" />
      </div>

      <div className="playground dark" title="should render toast neutral on dark background">
        <PToastItem message="Some neutral message" state="neutral" theme="dark" />
      </div>

      <div className="playground light" title="should render toast success on light background">
        <PToastItem message="Some success message" state="success" />
      </div>

      <div className="playground dark" title="should render toast success on dark background">
        <PToastItem message="Some success message" state="success" theme="dark" />
      </div>

      <div className="playground light" title="should render toast multiline message on light background">
        <PToastItem message="Some message with a very long text across multiple lines" style={{ width: 240 }} />
      </div>
    </>
  );
};
