// packages/components-react/src/App.tsx
import { PorscheDesignSystemProvider, type Theme } from '@porsche-design-system/components-react';
import { type JSX, useState } from 'react';
import { Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { routes } from './routes';

export const App = (): JSX.Element => {
  const navigate = useNavigate();
  const [theme, setTheme] = useState<Theme>('light');
  const themes: Theme[] = ['light', 'dark', 'auto'];
  const { pathname } = useLocation();
  const isWithinIFrame: boolean = window.location !== window.parent.location;

  return (
    <>
      {!isWithinIFrame && (
        <>
          <select name="route" value={pathname} onChange={(e) => navigate(e.target.value)}>
            <option disabled value="/">
              Select a page
            </option>
            {routes.map((route, i) => (
              <option key={i} disabled={route.isDisabled} value={route.path} children={route.name} />
            ))}
          </select>

          <select name="theme" value={theme} onChange={(e) => setTheme(e.target.value as Theme)}>
            {themes.map((item) => (
              <option key={item} value={item} children={item} />
            ))}
          </select>
        </>
      )}

      <div id="app">
        <PorscheDesignSystemProvider cdn="auto" theme={theme}>
          <Routes>
            {routes
              .filter((route) => !route.isDisabled)
              .map((route, i) => (
                <Route key={i} {...route} />
              ))}
          </Routes>
        </PorscheDesignSystemProvider>
      </div>
    </>
  );
};

// packages/components-vue/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import '@porsche-design-system/shared/css/styles.css';
import { PorscheDesignSystemProvider, type Theme } from '@porsche-design-system/components-vue';
import { routes } from './router';

const router = useRouter();
const route = ref<string>('');
const theme = ref<Theme>('dark');
const themes: Theme[] = ['light', 'dark', 'auto'];
const isWithinIFrame: boolean = window.location !== window.parent.location;

onMounted(async () => {
  await router.isReady();
  route.value = router.currentRoute.value.path;
});
</script>

<template>
  <select
    v-if="!isWithinIFrame"
    name="route"
    v-model="route"
    @change="router.push(($event.target as HTMLSelectElement).value)"
  >
    <option disabled value="/">Select a page</option>
    <option v-for="(item, index) in routes" :key="index" :value="item.path" :disabled="item.isDisabled">
      {{ item.name }}
    </option>
  </select>

  <select v-if="!isWithinIFrame" name="theme" v-model="theme">
    <option v-for="(item, index) in themes" :key="index" :value="item">{{ item }}</option>
  </select>

  <div id="app">
    <PorscheDesignSystemProvider cdn="auto" :theme="theme">
      <RouterView />
    </PorscheDesignSystemProvider>
  </div>
</template>
