// packages/components-react/src/styles/StylesHoverExample.tsx
import styled from 'styled-components';
import {
  getFocusStyle,
  getHoverStyle,
  gridGap,
  headingMediumStyle,
  spacingFluidMedium,
  textSmallStyle,
  themeDarkBackgroundBase,
  themeDarkPrimary,
  themeLightBackgroundBase,
  themeLightPrimary,
} from '@porsche-design-system/components-react/styles';

// Wrapper
const getWrapperStyle = {
  display: 'flex',
  flexWrap: 'wrap',
  justifyContent: 'center',
  alignItems: 'flex-start',
  gap: gridGap,
  padding: spacingFluidMedium,
} as const;

const WrapperLight = styled.div({
  ...getWrapperStyle,
  background: themeLightBackgroundBase,
  color: themeLightPrimary,
});

const WrapperDark = styled.div({
  ...getWrapperStyle,
  background: themeDarkBackgroundBase,
  color: themeDarkPrimary,
});

// Typography
const Heading = styled.h3({
  ...headingMediumStyle,
  textAlign: 'center',
  width: '100%',
  margin: 0,
});

const Paragraph = styled.p({
  ...textSmallStyle,
  margin: 0,
  maxWidth: '15rem',
});

// Anchor
const NativeAnchor = styled.a({
  ...textSmallStyle,
  ...getHoverStyle(),
  ...getFocusStyle(),
  color: 'inherit',
});

export const StylesHoverExample = (): JSX.Element => {
  return (
    <>
      <WrapperLight>
        <Heading>Hover Light</Heading>
        <NativeAnchor href="#">Some Anchor</NativeAnchor>
        <Paragraph>
          Lorem Ipsum <NativeAnchor href="#">is simply dummy text of the printing</NativeAnchor> and typesetting
          industry.
        </Paragraph>
      </WrapperLight>
      <WrapperDark>
        <Heading>Hover Dark</Heading>
        <NativeAnchor href="#">Some Anchor</NativeAnchor>
        <Paragraph>
          Lorem Ipsum <NativeAnchor href="#">is simply dummy text of the printing</NativeAnchor> and typesetting
          industry.
        </Paragraph>
      </WrapperDark>
    </>
  );
};

// packages/components-vue/src/styles/StylesHoverExample.vue
<script setup lang="ts">
import { Heading, NativeAnchor, Paragraph, Wrapper, WrapperDark, WrapperLight } from './hover.css';
</script>

<template>
  <div :class="[Wrapper, WrapperLight]">
    <h3 :class="Heading">Hover Light</h3>
    <a :class="NativeAnchor" href="#">Some Anchor</a>
    <p :class="Paragraph">
      Lorem Ipsum <a :class="NativeAnchor" href="#">is simply dummy text of the printing</a> and typesetting
      industry.
    </p>
  </div>
  <div :class="[Wrapper, WrapperDark]">
    <h2 :class="Heading">Hover Dark</h2>
    <a :class="NativeAnchor" href="#">Some Anchor</a>
    <p :class="Paragraph">
      Lorem Ipsum <a :class="NativeAnchor" href="#">is simply dummy text of the printing</a> and typesetting
      industry.
    </p>
  </div>
</template>
