// packages/components-react/projects/react-wrapper/skill/references/components/p-model-signature/examples/SafeZone.tsx
import React from 'react';
import { PModelSignature } from '@porsche-design-system/components-react';

export const Example = () => {
  return (
    <>
      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="718"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="911"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="boxster"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="cayenne"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="cayman"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="gt3-rs"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="gt3"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="gts"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="macan"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="panamera"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="taycan"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="turbo-s"></PModelSignature>
      </div>

      <div className="bg-[#ff000033] inline-block me-static-md mt-static-md">
        <PModelSignature safeZone={false} model="turbo"></PModelSignature>
      </div>
    </>
  )
}

// packages/components-vue/projects/vue-wrapper/skill/references/components/p-model-signature/examples/SafeZone.vue
<script setup lang="ts">
  import { PModelSignature } from '@porsche-design-system/components-vue';
</script>

<template>
  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="718"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="911"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="boxster"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="cayenne"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="cayman"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="gt3-rs"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="gt3"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="gts"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="macan"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="panamera"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="taycan"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="turbo-s"></PModelSignature>
  </div>

  <div class="bg-[#ff000033] inline-block me-static-md mt-static-md">
    <PModelSignature :safeZone="false" model="turbo"></PModelSignature>
  </div>
</template>
