// packages/components-vue/projects/vue-wrapper/skill/references/components/p-ai-tag/examples/WithinCheckbox.vue
<script setup lang="ts">
  import { PAiTag, PCheckbox, PFieldset, PText } from '@porsche-design-system/components-vue';
</script>

<template>
  <PFieldset label="Pick your favorite Fruits" labelSize="small" class="flex flex-col gap-static-sm">
    <PText class="-mt-static-md mb-static-sm">
      Slotted description with optional link
    </PText>
    <div class="flex flex-col gap-static-sm">
      <PCheckbox>
        <span slot="label">
          Banana
          <PAiTag variant="generated" class="ms-static-sm"></PAiTag>
        </span>
      </PCheckbox>
      <PCheckbox label="Apple"></PCheckbox>
      <PCheckbox :checked="true">
        <span slot="label">
          Melon
          <PAiTag variant="abbreviation" class="ms-static-sm"></PAiTag>
        </span>
      </PCheckbox>
      <PCheckbox label="Grapefruit"></PCheckbox>
    </div>
  </PFieldset>
</template>

// packages/components-angular/projects/angular-wrapper/skill/references/components/p-ai-tag/examples/WithinCheckbox.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
      <p-fieldset label="Pick your favorite Fruits" labelSize="small" class="flex flex-col gap-static-sm">
        <p-text class="-mt-static-md mb-static-sm">
          Slotted description with optional link
        </p-text>
        <div class="flex flex-col gap-static-sm">
          <p-checkbox>
            <span slot="label">
              Banana
              <p-ai-tag variant="generated" class="ms-static-sm"></p-ai-tag>
            </span>
          </p-checkbox>
          <p-checkbox label="Apple"></p-checkbox>
          <p-checkbox [checked]="true">
            <span slot="label">
              Melon
              <p-ai-tag variant="abbreviation" class="ms-static-sm"></p-ai-tag>
            </span>
          </p-checkbox>
          <p-checkbox label="Grapefruit"></p-checkbox>
        </div>
      </p-fieldset>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule], // <-- PDS module is imported here
})
export class ExampleComponent {}
