// packages/components-angular/projects/angular-wrapper/skill/references/components/p-carousel/examples/JumpToSlide.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CarouselUpdateEventDetail, PorscheDesignSystemModule } from '@porsche-design-system/components-angular';

@Component({
  selector: 'porsche-design-system-app',
  template: `
    <p-carousel [heading]="'Some Heading'" [activeSlideIndex]="activeSlideIndex" (update)="onUpdate($event)">
      <div>Slide 1</div>
      <div>Slide 2</div>
      <div>Slide 3</div>
    </p-carousel>

    <div class="flex gap-fluid-sm mt-fluid-sm">
    @for (_ of [].constructor(3); track _; let i = $index) {
      <p-button
        type="button"
        (click)="onButtonClick($event)"
        [disabled]="activeSlideIndex === i"
        >
        {{ i + 1 }}
      </p-button>
    }
    </div>
    `,
  styles: `
    @use '@porsche-design-system/components-angular/scss' as *;

    p-carousel div {
      display: flex;
      align-items: center;
      justify-content: center;
      background: #00b0f4;
      height: 150px;
      color: $color-primary;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [PorscheDesignSystemModule],
})
export class ExampleComponent {
  activeSlideIndex = 1;

  onUpdate(e: CustomEvent<CarouselUpdateEventDetail>) {
    this.activeSlideIndex = e.detail.activeIndex;
  }
  onButtonClick(e: MouseEvent) {
    this.activeSlideIndex = parseInt((e.target as HTMLButtonElement).innerText) - 1;
  }
}

// packages/components-react/projects/react-wrapper/skill/references/components/p-carousel/examples/JumpToSlide.tsx
import React from 'react';
import { type CarouselUpdateEventDetail, PButton, PCarousel } from '@porsche-design-system/components-react';
import { type MouseEvent, useCallback, useState } from 'react';

export const Example = () => {
  const [activeSlideIndex, setActiveSlideIndex] = useState(1);
  const onUpdate = useCallback(
    (e: CustomEvent<CarouselUpdateEventDetail>) => setActiveSlideIndex(e.detail.activeIndex),
    []
  );
  const onButtonClick = useCallback(
    (e: MouseEvent<HTMLButtonElement> & { target: HTMLButtonElement }) =>
      setActiveSlideIndex(parseInt(e.target.innerText) - 1),
    []
  );

  const slideStyle = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#00b0f4',
    height: '150px',
  };

  return (
    <>
      <PCarousel heading="Some Heading" activeSlideIndex={activeSlideIndex} onUpdate={onUpdate}>
        <div style={slideStyle}>Slide 1</div>
        <div style={slideStyle}>Slide 2</div>
        <div style={slideStyle}>Slide 3</div>
      </PCarousel>

      <div className="flex gap-fluid-sm mt-fluid-sm">
        {Array.from(Array(3)).map((_, i) => (
          <PButton key={i} type="button" onClick={onButtonClick} disabled={activeSlideIndex === i}>
            {i + 1}
          </PButton>
        ))}
      </div>
    </>
  );
};
