// packages/components-vue/projects/vue-wrapper/skill/references/components/p-heading/examples/Semantics.vue
<script setup lang="ts">
  import { PHeading } from '@porsche-design-system/components-vue';
</script>

<template>
  <PHeading tag="h3">
    The quick brown fox jumps over the lazy dog
  </PHeading>

  <PHeading>
    <h3>
      The quick brown fox jumps over the lazy dog
    </h3>
  </PHeading>
</template>

// packages/components-react/projects/react-wrapper/skill/references/components/p-heading/examples/Semantics.tsx
import React from 'react';
import { PHeading } from '@porsche-design-system/components-react';

export const Example = () => {
  return (
    <>
      <PHeading tag="h3">
        The quick brown fox jumps over the lazy dog
      </PHeading>

      <PHeading>
        <h3>
          The quick brown fox jumps over the lazy dog
        </h3>
      </PHeading>
    </>
  )
}
